### ISSUE TITLE
[Shaman][Restoration] Support ancestral protection totem

### ISSUE THREAD

**Issue by hartra344** [WoWAnalyzer/WoWAnalyzer#1011]
- Show amount of reduced damage per cast (statitic)
- Show who got resurrected (statistic)
- Show if the resurrect  was wasted (statistic and suggestion)

**Comment by abelito75** [comment]
Does this still provide DR? If not we can close it when we merge in #3390

**Comment by HawkCorrigan** [comment]
If memory serves it only provides 10% extra max hp.

**Comment by Pewtro** [comment]
@niseko will this be needed/interesting in SL?

**Comment by abelito75** [comment]
no comments have been made and it doesn't look to make DR sooooo closing
