### ISSUE TITLE
Holy Paladin: check beacon uptime

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1015]
Some users forget their beacons... apparently. We're also checking enchants and legendaries so might as well check.

Could also *punish* for casting beacons during the pull. You should pre-pull beacon.

**Comment by torothin** [comment]
I would like to tackle this issue if it is still worth fixing/adding.

**Comment by abelito75** [comment]
So to my knowledge we already do enchants and legionaries are out of the game so the only thing that would need to get done is the beacon checker :)

**Comment by torothin** [comment]
I have a question about how to display the percentage of uptime.  If the paladin dies before the fight ends but beacon was up the entire time the paladin was alive, should the beacon percentage be based on the amount of time the paladin was alive or the length of the entire fight?

**Comment by abelito75** [comment]
You should always do full fight as the metric. If they die they can filter till death and it will work
so if they are alive for 20% of the fight and had beacon up for that full time it should say
20% beacon uptime

**Comment by torothin** [comment]
Current Statistics component:

![image](https://user-images.githubusercontent.com/23178481/70299275-4a332880-17a9-11ea-9167-8e8b0d1bce8d.png)
![image](https://user-images.githubusercontent.com/23178481/70299352-8797b600-17a9-11ea-9c90-c345f0ad877d.png)
![image](https://user-images.githubusercontent.com/23178481/70299400-a7c77500-17a9-11ea-869b-3092e764a1e0.png)
![image](https://user-images.githubusercontent.com/23178481/70299455-caf22480-17a9-11ea-831c-b30e834e4fc9.png)

I want to add something to the overview to say Beacon of whatever was not applied prior to combat but I am not sure what section makes the most sense.  Support abilities, cooldowns, its own section?  Thoughts?

**Comment by torothin** [comment]
![image](https://user-images.githubusercontent.com/23178481/70299820-cd08b300-17aa-11ea-9548-7bd15ede2d71.png)

**Comment by torothin** [comment]
![image](https://user-images.githubusercontent.com/23178481/70299855-e3af0a00-17aa-11ea-8e75-3c9d6249256b.png)

**Comment by torothin** [comment]
![image](https://user-images.githubusercontent.com/23178481/70299901-06412300-17ab-11ea-8386-f32a39d5ad25.png)

**Comment by abelito75** [comment]
I personally think in Overview in the checklist under the tab `Don't tunnel tanks` would be a good spot. But you need to import it into checklist/Module.js and then add a ui element for it in checklist/Component.js

Since the idea would to be more of a checklist item than a stat (there is nothing wrong with it being a stat at all i'd personally keep it since it can be cool)

**Comment by torothin** [comment]
![image](https://user-images.githubusercontent.com/23178481/70347020-7afc7780-1814-11ea-884a-b4aed336c1d7.png)
![image](https://user-images.githubusercontent.com/23178481/70347066-95ceec00-1814-11ea-85cd-3831bec47d47.png)
![image](https://user-images.githubusercontent.com/23178481/70347190-d4fd3d00-1814-11ea-88cb-1ce7a3ec61c7.png)

**Comment by abelito75** [comment]
You might want to add the up time statistics as if they die and don't reapply its bad

**Comment by torothin** [comment]
It would not be difficult to make my own rule that is along the lines of Cast Beacons on tanks prepull.  This looks fine to me just not sure if people will get it in the "dont tunnel the tanks" section.

![image](https://user-images.githubusercontent.com/23178481/70347710-fdd20200-1815-11ea-86a0-1b9ff40f133c.png)

**Comment by abelito75** [comment]
I my head it's the reason you don't tunnel tanks

**Comment by torothin** [comment]
How's this?
![image](https://user-images.githubusercontent.com/23178481/70351035-ddf20c80-181c-11ea-9e0c-dd426ef70f4f.png)

**Comment by abelito75** [comment]
I'd rename it to something like beacon mastery but outside of that looks beautiful :) 
I mainly same something generic so we can add to it later with beacon of virtue if it does become valid for raiding ever

**Comment by torothin** [comment]
This issue can be closed per pull request #3427.
