### ISSUE TITLE
[Beast Mastery] Parsel's Tongue

### ISSUE THREAD

**Issue by Tromal** [WoWAnalyzer/WoWAnalyzer#1020]
When a hunter uses the legendary BM chest, could the site verify the uptime of the buff ?

**Comment by Pewtro** [comment]
Hello, I maintain the hunter modules - Parsel's Tongue is on a to-do list, but slightly put on hold due to getting everything ready for an update aswell as exam season. It's a planned module however

**Comment by Tromal** [comment]
Hi, could you tell me where I could find the to-do list in order to avoid
create duplicates ?

Thanks a lot for this answer and your hard work and good luck for your
exams.

**Comment by Pewtro** [comment]
This is my milestone for BM: https://github.com/WoWAnalyzer/WoWAnalyzer/milestone/5
It's without anything called additional legendaries, but rest assured it's planned - I'll open an issue just for clarity now
