### ISSUE TITLE
Holy Paladin: Add Wasted IoLs to `Use core spells as often as possible`

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1038]
Half the point in HS crit cap is to get IoL to always proc. That makes using it a core spell.

**Comment by abelito75** [comment]
As you can't crit cap anymore is this still valid?

**Comment by MartijnHols** [comment]
Wasting IoL is still a thing, though only for the non-Glimmer build. It will probably come back next expansion as something nice to have.

**Comment by abelito75** [comment]
Lilaith-sama said this isn't a valid issue any more so CY@ NERD
