### ISSUE TITLE
Checklist: Add a tooltip to bars to explain what a filled vs empty bar means and maybe also the thresholds

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1039]
Especially important for "reverse bars" e.g. more wasted = less good

**Comment by Sharrq** [comment]
So this might not be everything you were hoping for, but I added tooltips to the Core Checklist as part of #1262 

Its just a basic tooltip though, but the dev could in theory put some of that info in manually.

**Comment by Sharrq** [comment]
This should be covered by #1262 (Adds a tooltip to the label) and #1274 (Adds a tooltip to the value)

**Comment by MartijnHols** [comment]
Nice, thanks!
