### ISSUE TITLE
Add a "summary" below the checklist

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1042]
I was thinking to make the layout more balanced a bar underneath the checklist like the old maintainer row might look nice. Could fill that with a super simple summary: if <=20% of rules failed = `Good job so far! Keep it up and try to improve those last things.` >=60% = `There are a lot of things to improve. Try following these rules to become more effective. Don't overdo it though; focus on one thing at a time.`

![image](https://user-images.githubusercontent.com/4565223/34320340-5839253e-e7f8-11e7-9247-2adcbc3c08d3.png)

**Comment by MartijnHols** [comment]
I'd really like to give player ratings; D to A+ based on checklist. But people had a good argument when WCL's performance rating already does that better. :(

**Comment by fyruna** [comment]
Do you still want this or not?
