### ISSUE TITLE
Make contributing tutorial videos

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1063]
Related: #1061

I think this could be a good way to explain the project in a concise and easy way.

Possible subjects:

# Installing

Goes through https://github.com/WoWAnalyzer/WoWAnalyzer/blob/master/docs/installing.md, preferably on Windows by default (even better: also UNIX). From installing nodejs to `npm start`.

# Adding a module

Especially showing the adding of the module to the `CombatLogParser` should make things a lot simpler and concise. It appears confusing but it's actually the easiest step.

# Adding the checklist

**Comment by Preheet** [comment]
Hey all, huge fan. I've spoken with Anom (happens to be a guildy of mine) and made a tutorial video (albeit a Fire Mage Guide) about using the website. I'd be very interested in helping spread the word about the site and its features. I also happen to be into graphic design and video editing. Should you guys ever need some help making videos and/or creating artwork, I'd love to help out where I can.

You can reach me on Discord @ PREHEET#2038

Feel free to check out the video below
https://youtu.be/hOp0hha4wY0
