### ISSUE TITLE
Elemental Legendaries

### ISSUE THREAD

**Issue by HawkCorrigan** [WoWAnalyzer/WoWAnalyzer#1065]
- [x] Smoldering Heart
- [ ] Eye of the Twisting Nether
- [ ] Pristine Proto-Scale Girdle
- [ ] Al'Akir's Acrimony
- [ ] Echoes of the Great Sundering
- [ ] ?UR/Soul?
- [ ] Roots of Shaladrasil

**Comment by MartijnHols** [comment]
Legion is practically over
