### ISSUE TITLE
Cannot read property 'enchantableGear' of undefined

### ISSUE THREAD

**Issue by Grimsbain** [WoWAnalyzer/WoWAnalyzer#1118]
When I try to view the Shadow Priest (Urnn) on [this log](https://wowanalyzer.com/report/YCnMz2TXJ8kq1GW3). I get the follow error. All the other characters work just fine.

> TypeError: Cannot read property 'enchantableGear' of undefined
>     at t.check (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1953805)
>     at https://wowanalyzer.com/static/js/main.7b56e228.js:1:79838
>     at Array.map (<anonymous>)
>     at t.value (https://wowanalyzer.com/static/js/main.7b56e228.js:1:79808)
>     at Array.map (<anonymous>)
>     at t.value (https://wowanalyzer.com/static/js/main.7b56e228.js:1:82800)
>     at t.value (https://wowanalyzer.com/static/js/main.7b56e228.js:1:4201103)
>     at l (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1390736)
>     at beginWork (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1392456)
>     at a (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1404581)
>     at o (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1404902)
>     at u (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1405140)
>     at v (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1408684)
>     at E (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1408421)
>     at p (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1407549)
>     at h (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1406939)
>     at Object.enqueueSetState (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1381464)
>     at t.a.setState (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1360415)
>     at https://wowanalyzer.com/static/js/main.7b56e228.js:1:1527732
>     at new Promise (<anonymous>)
>     at t.<anonymous> (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1527704)
>     at r (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1531495)
>     at Generator._invoke (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1532541)
>     at Generator.e.(anonymous function) [as next] (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1531674)
>     at r (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1515110)
>     at https://wowanalyzer.com/static/js/main.7b56e228.js:1:1515256
>     at new Promise (<anonymous>)
>     at t.<anonymous> (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1515054)
>     at t.e (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1527526)
>     at t.<anonymous> (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1517784)
>     at r (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1531495)
>     at Generator._invoke (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1532541)
>     at Generator.e.(anonymous function) [as next] (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1531674)
>     at r (https://wowanalyzer.com/static/js/main.7b56e228.js:1:1515110)
>     at https://wowanalyzer.com/static/js/main.7b56e228.js:1:1515204
>     at <anonymous>
>     in t
>     in Connect(t)
>     in main
>     in div
>     in t
>     in Connect(t)
>     in t
>     in t
>     in t
>     in n
>     in O

**Comment by MartijnHols** [comment]
Thanks for the report, I just fixed the issue and Shadow Priests should import fine again.
