### ISSUE TITLE
[Fire Mage] Add handling for Ignite

### ISSUE THREAD

**Issue by kfinch** [WoWAnalyzer/WoWAnalyzer#1152]
Opening this issue to brainstorm ideas for how to handle Ignite in the Fire Mage analyzer.

The way I see it, we need some way to tie ignite damage to the spell that procced it. There are a bunch of possible ways to implement, here's an outline for one:
- use default behavior of StatTracker to keep a good snapshot of player's mastery rating, and therefore the strength of their ignite at any given moment.
- make an Ignite module that uses mastery rating + other Ignite modifiers / buffs to figure out a spell's ignite strength.
- when calculating the damage of a spell that procs ignite, call out to that module to get the spell's "true damage" including both direct and ignite damage
- this method can easily be checked for correctness ON SINGLE TARGET FIGHTS by calling it on all ignite proccers and seeing how well the predicted ignite damage matches up with the actual ignite damage
- the biggest problem with this method is that it has no real way to account for Ignite's "jumping" behavior when multiple targets are available

**Comment by Sharrq** [comment]
I recall you mentioning you had the beginnings of Ignite handling ... do you still have that? Maybe i can look at what you made previously and finish it or continue it or get an idea of what i need to do

**Comment by kfinch** [comment]
I abandoned it because I lost faith in the method I was using, but it did have some merit. I'll try and look up the branch.

**Comment by kfinch** [comment]
@Sharrq ahh found it, looks like I had a basic implementation of what I described: https://github.com/kfinch/WoWAnalyzer/blob/11aa9426bb5cbb7372b62a7d58ae8fb8660b817f/src/Parser/Mage/Fire/Modules/Core/Ignite.js

**Comment by Sharrq** [comment]
After talking to the Mage Theorycrafters about this, I decided against doing this and opted for not showing damage contribution from items instead as that statistic is not really that helpful and can often be more confusing than helpful. The general consensus was to focus on using the legendaries properly instead of how much damage they contributed.

Plus sims can easily show how much damage a legendary will get you, and the mage sims are maintained very well.

**Comment by MartijnHols** [comment]
![image](https://user-images.githubusercontent.com/4565223/42294728-853afd7c-7fe3-11e8-94f6-9f1a373a0e92.png)
