### ISSUE TITLE
[Resto Druid] ToL prepulls  always count as a head proc

### ISSUE THREAD

**Issue by buimichael** [WoWAnalyzer/WoWAnalyzer#1159]

**Comment by kfinch** [comment]
I mean we technically can't prove what sort of proc it was, but I can make it default to assuming hardcast. Do you have any logs I can test with?

**Comment by buimichael** [comment]
@kfinch https://wowanalyzer.com/report/YfyPQVTxpzvwqRjZ/21-Mythic+Varimathras+-+Wipe+16+(2:48)/Reni
