### ISSUE TITLE
Water Jet cast not being registered

### ISSUE THREAD

**Issue by kfinch** [WoWAnalyzer/WoWAnalyzer#1163]
Was reported in another unrelated PR ...

**Comment by Sharrq** [comment]
This issue here is that pet casts arent picked up by Abilities/AbilityTracker. Trying to hunt through both of these to see where that can potentially be changed to include pet abilities.

**Comment by Sharrq** [comment]
Water Jet is removed in 8.0 Prepatch, so this can be closed.
