### ISSUE TITLE
Clearcasting module shows over 100% clearcasting util

### ISSUE THREAD

**Issue by buimichael** [WoWAnalyzer/WoWAnalyzer#1172]
This fine druid was using MoC.
https://wowanalyzer.com/report/TLBp1V2ZWdhz7YJq/40-Mythic+The+Coven+of+Shivarra+-+Kill+(7:14)/Blazyb/cast-efficiency

**Comment by kfinch** [comment]
-6 expirations, the math checks out!    -_-

**Comment by kfinch** [comment]
Ok, it looks like you actually got more than 100% util... on a few occasions the Clearcasting buff stayed active for more than 3 Regrowths. Also, suspiciously, I see no instances of a Clearcasting refreshbuff event. My best guess is that no event is fired when a new CC procs while the existing one is active, but it still sets your remaining free Clearcasts to 3 again.

**Comment by buimichael** [comment]
@kfinch 

Yeah, that's a bummer. I guess we could use the mana properties and see if there was any mana loss from each regrowth cast  (also make sure to have a check for innervate and symbol of hope). If no mana was used we can assume it was a CC-regrowth.

However, that's not gonna solve the problem with showing the amounts of procc received with CC when MoC is specced I guess.

**Comment by kfinch** [comment]
So I checked, and it looks like all the Regrowths cast within CC benefit from it, meaning that if I see more than 3 casts within I know there was at least one refresh. Can't tell much more tho, I've basically implemented a thing that clamps to 100% util and cinludes a disclaimer. Will push PR soon.
