### ISSUE TITLE
Add avoidance damage reduction display

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1184]
For non-tanks avoidance reduces most of the damage taken, showing how much can give more insight into how good it is and allow us to include it in stat weights for specs with that enabled.

Probably going to have to either find a property that indicates something is AoE damage (probably doesn't exist), or make a custom a list of things affected by Avoidance and only include damage taken from that.

If making a list please consider using the fight config in the Raids directory.

**Comment by Gebuz** [comment]
If anybody wants to make the Whitelist I'll include it when implementing the mitigation module!

**Comment by abelito75** [comment]
Stat weights have been removed by most healers so i'll be removing this as well
