### ISSUE TITLE
[Survival] General ideas

### ISSUE THREAD

**Issue by Pewtro** [WoWAnalyzer/WoWAnalyzer#1217]
For my own sake of remembering and collecting suggestions and more:

- average time left on mongoose fury when aspect of the eagle is used 
- mok uptime, maybe average time left when you refresh, or a list of the times left when you refreshed it
- a blurb on the cobra section about saving it for lust because it scales really well with haste (just hitting dummy no lust snek hit 18 times, lust snek hit 37 times)
- check if the player is Aspect of the Skylord'ing before a MF window (and ensure MF window is at X stacks)
- check if the player lacerates too much
- check for On The Trail uptime

**Comment by artimdal** [comment]
Check if Snake attacks while player has buff
