### ISSUE TITLE
Elemental Shaman T21

### ISSUE THREAD

**Issue by HawkCorrigan** [WoWAnalyzer/WoWAnalyzer#1224]
Tier 21 2Set is bugged when spending the buff on earthquake.

No perfect way to fix it is possible tho because you can't distinguish between different earthquakes in a log when stacking them.

**Comment by HawkCorrigan** [comment]
Probably gonna have to fix it like we did Echoes which would provide a better estimate, even though the number would still not be perfect

**Comment by MartijnHols** [comment]
Legion is practically over
