### ISSUE TITLE
Tracking dots on multiple targets

### ISSUE THREAD

**Issue by Gebuz** [WoWAnalyzer/WoWAnalyzer#1243]
I've had a few requests to show dot uptime on multiple targets, but I don't know how to best display it. A few of the solutions that I've considered are:
* Combined dot uptime as a percentage in a statbox. Basically if you had 50% uptime on one target and 75% on another, it would display 125%.
* List of all enemies and uptime. This could potentially be in a tooltip for the statbox suggested above. Since bosses can have a lot of adds it might make sense to group them by name.
* Timeline showing dot uptime on all targets. It has the issue that it could quickly become very long with many adds.
* Only display uptime only on boss targets, using one of the above methods. Warcraftlog already Categorizes them, I don't know if we can easily get that info though (otherwise we would need to maintain boss names).

Ideas and suggestions are very welcome.

**Comment by sMteX** [comment]
I personally would stay away of summing uptimes on different entities - even averaging would be better, but seeing 332% uptime sounds weird to me. Table of enemies and uptimes would be most correct but how would we present different debuffs we want to "watch"? As for if target is boss or something else - I think there's some black magic (I've used it in https://github.com/WoWAnalyzer/WoWAnalyzer/blob/7263a89e7378a914562c8d6e3df532ef648ae5c9/src/Parser/Warlock/Affliction/Modules/Features/Sniping.js#L68) or majority of them don't have `targetInstance` etc.

**Comment by abelito75** [comment]
This has been fixed iirc
