### ISSUE TITLE
[Death Knight] Runetracker

### ISSUE THREAD

**Issue by Gebuz** [WoWAnalyzer/WoWAnalyzer#1255]
I'm working on implementing a Rune tracker. The way I do it is make 3 fake spells for the runes with 2 charges each to simulate how they recharge in game (I suspect that this is also how it works behind the scenes in game since it used to work like that). I have got the basics working but I have a few considerations concerning the display I would like to discuss.

How should it be displayed on the timeline (if at all)? I had an idea of making a bar that would colour code the number of runes on cooldown (>=3 green, = 4 orange, = 5 red, = 6 darker red for example), but I'm not sure if I should add something like this to the timeline (I don't know how complicated it would be to extend it for one class).

Another way to do it is just displaying the 3 rune pairs cooldown, but that might be confusing since that is not how it is displayed in game. If we choose to do this it would probably make sense to also show them in the cast efficency tab.

Since I plan to make this work for all 3 specs, I'll need to implement Runic Corruption. Are buffs that dynamically reduce cooldown (not through haste) supported? EDIT: looks like they aint, I would probably need to listen to on_toPlayer_buffapplied/removed similar to on_changehaste.

**Comment by yajinni** [comment]
Hm i dont know. Maybe one single fake spell that is triggered every time a rune fills. And you can mouse over it for a tool tip showing the exact number of use/depleted ones at the time?

**Comment by jjs451** [comment]
I think it might make the timeline too noisy.  A chart showing number of available runes over time would be more helpful.  There's not so much interest in knowing the exact number of runes on cooldown as there is knowing how much time is spent capped on runes.  I like using the fake spells to simulate the recharge, there should hopefully be a way to pull out the cast efficiency information from those to figure out how long someone was capped on runes.  

You can look at UllrsFeatherSnowshoes.js to see an example of dynamically reducing cooldown.  

I've got a module that shows runes spent like a standard class resource module but never merged it because its not terribly helpful on its own.

**Comment by yajinni** [comment]
I agree knowing how much time spent capped and such is more important.
But there will be a rare time where someone takes a bunch of damage. and u want to see did they use thier runes efficiently to that point or not. For tanks that might have some usage.

**Comment by Gebuz** [comment]
I like the chart idea, it should give a good visual of how often runes were overcapped and I suppose seeing the recharge time isn't important. A statbox and suggestions for time spent overcapped is first on the list, I didn't mention it in the OP since I'm fairly confident that should be easy to get from cast efficiency.

The problem with runic corruption (and blood 4p21) is that it isn't cooldown reduction, it just speeds up the recharge time in the same way haste does, so the UllrsFeatherSnowShoes approach wouldn't work. Anyway I think I know how to do it (listen to on_toPlayer_buffapplied/removed similar to on_changehaste).

**Comment by Gebuz** [comment]
Adding a link to my current to do list to show what I plan to implement:
https://github.com/Gebuz/WoWAnalyzer/projects/2

**Comment by Gebuz** [comment]
How is this display? Anything you want changed?
![image](https://user-images.githubusercontent.com/6773230/35687169-508c2d78-076e-11e8-9a23-5f3a8353e7c4.png)

**Comment by jjs451** [comment]
Graph looks good.  The tooltip looks a little noisy with so much text but that's also good information so I'm good with it.

I'm linking a branch where I setup a rune tracker like the standard class resource trackers you see around the site.  You may want to incorporate all, some, or none of it.  It just shows what runes were spent on for unholy.  I could never figure out how to properly track rune gain.  Actually now that I think about it I think the only value we can get from that branch is a list of how runes were spent and that doesn't really relate to your work.  Each spec can do that on its own.    

https://github.com/jjs451/WoWAnalyzer/tree/rune-tracker/src/Parser/DeathKnight/Unholy/Modules/Runes

**Comment by Gebuz** [comment]
Yeah I thought tooltip might be too much to, I'll try to find a better way to display that. I'll also add runes gained ( and spent probably), should be pretty easy to estimate passive gain now that I track the CDs :p
