### ISSUE TITLE
Interface updates

### ISSUE THREAD

**Issue by sMteX** [WoWAnalyzer/WoWAnalyzer#1260]
I've received a suggestion for little updates on the interface. 

1) The items, stats on pull and talents could be collapsible (just as Checklist Rules are), if the person doesn't want to see them
![image](https://user-images.githubusercontent.com/5068584/35419010-f82694e4-0235-11e8-9e0d-2c4b10fe561f.png)
![image](https://user-images.githubusercontent.com/5068584/35419015-fd7be8ae-0235-11e8-9b11-7fcbbe36ece9.png)

2) Another idea would be to join them + the gear tab to something similar to this (which could also be collapsible):
![image](https://user-images.githubusercontent.com/5068584/35419042-2234b202-0236-11e8-90e9-04e64d78347e.png)

I personally like option 1 a lot, and option 2 as well, my only concern would be that it would take up a lot of space, or suddenly a lot of space would be empty if it was collapsed. Just leaving it as a suggestion.

**Comment by yajinni** [comment]
I think the gear tab needs rework. I like this idea. I also like being able to see the names of the gear or slot without mousing over.

**Comment by MartijnHols** [comment]
Unfortunately the Warcraft Logs API does not provide item names and since we also do not have a complete item database we are unable to show item names.

**Comment by fyruna** [comment]
Collapsing the stats on pull isn't a bad idea, I'm not sure if it's way too prominent atm.

**Comment by MartijnHols** [comment]
The plan is to add a character tab to the main tabs with stats on pull, talents and gear all in one location and free up the space from the rest of the page. #211
