### ISSUE TITLE
Can't view two players with the same name

### ISSUE THREAD

**Issue by ACmage0042** [WoWAnalyzer/WoWAnalyzer#1271]
When trying to view a report for a log that has two players with the same name, it will always pick one of the players in the list and never show you the other player. 

So for example - https://wowanalyzer.com/report/YkpZHwDvT7mc61fq/7-Mythic+Kin'garoth+-+Kill+(7:44)
When i click on Swoof (Windwalker) it will show me the analysis for him. then when you go to click Swoof (Demonology) It loads the Windwalker again. 

The url when you click on a player only shows the name not the realm data as well, and i'm not sure if the log data carries that over.

**Comment by kfinch** [comment]
We don't get realm data, but we do get a unique ID for telling them apart. This should be solvable.

**Comment by MartijnHols** [comment]
We can solve this by prepending the player id in front of the player name like we do for fights. A PR would be welcome. Please do ensure the server's path regex also works.

**Comment by CubeLuke** [comment]
I started looking into this as a nice issue to get started with. @MartijnHols , how concerned should we be about allowing pre-existing urls to work for this? Meaning, should we just allow [https://wowanalyzer.com/report/YkpZHwDvT7mc61fq/7-Mythic+Kin'garoth+-+Kill+(7:44)/Swoof](https://wowanalyzer.com/report/YkpZHwDvT7mc61fq/7-Mythic+Kin'garoth+-+Kill+(7:44)/Swoof) to work similarly to [https://wowanalyzer.com/report/YkpZHwDvT7mc61fq/7-Mythic+Kin'garoth+-+Kill+(7:44)/4-Swoof](https://wowanalyzer.com/report/YkpZHwDvT7mc61fq/7-Mythic+Kin'garoth+-+Kill+(7:44)/4-Swoof) as a default? Or should we just move forward with the format of `playerId-playerName` as the new format?

**Comment by MartijnHols** [comment]
Backwards compatibility would be greatly preferred.
