### ISSUE TITLE
Move documentation to the Wiki

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1290]
Our documentation is currently partially in [docs](https://github.com/WoWAnalyzer/WoWAnalyzer/tree/master/docs) and [the wiki](https://github.com/WoWAnalyzer/WoWAnalyzer/wiki). We need to move everything to the wiki for easier maintenance.

**Comment by fyruna** [comment]
I've moved over all the documentation to Wiki. The images are still being used as they can only be moved to the wiki if you push it from a local repo.

**Comment by MartijnHols** [comment]
👍  thanks
