### ISSUE TITLE
Not pulling all fights

### ISSUE THREAD

**Issue by Rehok** [WoWAnalyzer/WoWAnalyzer#1322]
Fails to import a fair amount of pulls 

Warcraft Log Report: https://i.imgur.com/EiH1ST2.png

What i get when import it: https://i.imgur.com/TyZXd9V.png

If i click refresh (button not the entire website) it loads up the rest

**Comment by MartijnHols** [comment]
We cache API responses due to WCL's restrictive rate limit. You can refresh the list if it is incomplete with the refresh button in the fights list.

**Comment by Pewtro** [comment]
Is usually because we've cached an earlier version afaik so it requires the user to click refresh to fetch the remaining.
