### ISSUE TITLE
Charts Squashed on Mobile

### ISSUE THREAD

**Issue by emallson** [WoWAnalyzer/WoWAnalyzer#1343]
<img alt="stagger plot on mobile" src="https://cdn.discordapp.com/attachments/316864385052049420/410160804222992404/Screenshot_20180205-145140.jpg" height="250px"/>

Charts in general seem to break on mobile (not tall enough). They seem to work when you request the desktop site, at least in chrome mobile.

**Comment by Pewtro** [comment]
@emallson is this something we need to look more into, or is it improved visibility with the new charts you were testing out?

**Comment by emallson** [comment]
New charts should help. Some of it will persist. Will have to do mobile
testing but its low prio compared to desktop/tablet.

**Comment by abelito75** [comment]
Is this still an issue? 
Is this issue preventable?
