### ISSUE TITLE
[Disc Priest] Castigation

### ISSUE THREAD

**Issue by Pastaaa** [WoWAnalyzer/WoWAnalyzer#1353]
Hey Guys =) 

Most of my Logs, the Castigation healing "module" shows the same amount of Healing contribute as the fourth penance bolt (castigation adds a additional bolt) at the atonement sources tap. 
e.g. https://wowanalyzer.com/report/CwZkzp4yM8GrjtWa/8-Heroic+Felhounds+of+Sargeras+-+Kill+(3:24)/Past%C3%A0/atonement-sources . Both say 30k hps, so all fine here. 

But i got a few logs where its so freaky different, e.g my last night varimathras hc kill.
https://wowanalyzer.com/report/CwZkzp4yM8GrjtWa/21-Heroic+Varimathras+-+Kill+(3:34)/Past%C3%A0

![castigation](https://user-images.githubusercontent.com/32820288/35966231-7d6220b0-0cbd-11e8-85fd-d745fa03aecf.jpg)

7k Hps vs 80k.  Hope someone can figure out the problem

**Comment by abelito75** [comment]
I'm not sure if this is still valid but i haven't heard anything about it (i believe the talent just isn't taken anymore) but since the first bolt is 25% higher I'd assume its not a full bug and just rng. Going to close it. If it is a bug we reopen
