### ISSUE TITLE
[Resto Druid] Chameleon Song uptime estimate incorrect

### ISSUE THREAD

**Issue by muphrid15** [WoWAnalyzer/WoWAnalyzer#1369]
See the following:

https://wowanalyzer.com/report/bfXkVDtYRZd6HABj/25-Heroic+Aggramar+-+Kill+(6:06)/4-Hatsya
https://www.warcraftlogs.com/reports/bfXkVDtYRZd6HABj#fight=25&type=auras&source=4

The total duration of Incarnation is approximately 84 seconds, and the two events are 42 seconds long each. That should be exactly 1 cast of Incarnation + 1 proc of Chameleon Song each, and Chameleon Song should be valued at 24 seconds of uptime.

Instead, the analyzer computes its uptime at 18 seconds.

While ToL buff extension appears supported in the code, I suspect that the issue is shifting out of ToL and back into ToL during one of the extended ToLs. This appears to trigger an extra cast of Incarnation in the logs.

**Comment by muphrid15** [comment]
Sorry, just got the helm this past week, so this is the only event I've personally experienced.

**Comment by kfinch** [comment]
Well this has at least helped me notice that I had mixed up which buff was 'Currently in ToL' and which one was 'Has the capacity to shift to ToL', so I'll fix that.

**Comment by kfinch** [comment]
Ok I found something similar happening on your Imonar kill. It appears that an Incarnation 'cast' event is fired upon reentering Incarnation... even an Incarnation that was procced from the helm. This is about the most obnoxious way of doing things I can imagine. I'll think about solutions.
