### ISSUE TITLE
Player Selection List Player Name Wrapping Issue

### ISSUE THREAD

**Issue by CubeLuke** [WoWAnalyzer/WoWAnalyzer#1372]
There appears to be some styling issue with the columns for players in the playerSelectionList, as seen below in the following image. It's occurring with the static player selection and the overlay. The last player in the first column will wrap into the second column

![image](https://user-images.githubusercontent.com/10378593/36076986-2ffe1ba4-0f32-11e8-99a5-1f9d8c723eda.png)

**Comment by Gebuz** [comment]
It only seems to happen when there is an odd number of players in the category.
