### ISSUE TITLE
Cooldown Thoughtput Tracker improvement suggestions

### ISSUE THREAD

**Issue by Gebuz** [WoWAnalyzer/WoWAnalyzer#1415]
One of the more common problems I see in logs is poor spell choice or high downtime during cooldowns. I think we could display it better visually to the player if we had a timeline with the GCD and cast time showing aswell as the spells cast to make downtime more obvious. I thought about just displaying them as buffs on the timeline tab, but I think showing only the cooldown window will do a better job highlighting it, and there is also the risk of trying to show too much info on the timeline tab. It would also be nice to have the option to highlight the mistakes somehow, like making "bad" casts' icons red (with a tooltip explanation maybe?) and adding red bars during downtime. 

Along with that it would also be nice with a downtime stat specificly during each cooldown usage, possibly excluding utility spells. I think having a suggestion for "X Bad cooldown uses" that links directly to a timeline showing spells cast and downtime during the cooldown would help make it more obvious to the user how important playing correctly during the cooldown window is, and what they did wrong. Maybe have a toggle on the cooldown tab that shows/hides good cooldown uses aswell to highlight the bad ones.

I think most of my ideas would apply to most specs. I'd love to hear other people's opinions and ideas on how to best display it and if there is anything else you could highlight during cooldown uses.

**Comment by Pewtro** [comment]
I think this is solved through the new timeline and adding meta information to bad casts?

**Comment by abelito75** [comment]
I agree with putput this is solved closing.
