### ISSUE TITLE
Show a death log if the player died

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1511]

**Comment by Gebuz** [comment]
Considering WCL already has a pretty detailed deathlog, what are we looking to show here, and how detailed? Could it be solved by a link taking you to the death line in the events tab and toggling off irrelevant events or do we want focus on cooldowns used/available at the time of death?

**Comment by MartijnHols** [comment]
Showing available spells would be cool, mostly just interested in showing more info. Linking to event view might be a good option, or maybe the timeline. I was thinking a new view that specializes though.

**Comment by MartijnHols** [comment]
Ok showing a death log on our site would probably be silly. A direct link to the appropriate death log(s) on WCL would be nice.

**Comment by MartijnHols** [comment]
Implemented by @joshinat0r
