### ISSUE TITLE
M+ support: use initial combatantinfo to separate fights

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1579]
The idea is to fabricate fight start/end events or otherwise separate fights in order to make it so M+ can be parsed boss to boss.

**Comment by abelito75** [comment]
Depending on how logs work for those we could use timefiltering for it. If logs don't have it then we might want to give Khira a ring and see if he can do this easily. Plus with the new build power we could add other key features in so m+ log checking for bosses at least could be much better

**Comment by MartijnHols** [comment]
Timefiltering should work pretty well though I think we should not be adding support for M+. We have enough trouble keeping things up-to-date without having to worry about those buffs and bugs,
