### ISSUE TITLE
Extract `changebuffstack`/`changedebuffstack` out of the Entities module

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1582]
The Entities module currently does two or more things, this is a big part of it being ugly and needing a big rewrite. A good first step would be to promote `changebuffstack` to its own module.

Beware: I think this might currently also work for enemy units, this would have to be researched and if this is the case it might have to support that use case OR remove it (if it's not used a lot, which I don't expect it is, then removal in favor of manual handling might be better). I looked into this briefly and I'm fairly confident this isn't the case, but this might be different when this is picked up.

**Comment by abelito75** [comment]
Is this still an issue?
