### ISSUE TITLE
Add "Bad talents" to suggestions.

### ISSUE THREAD

**Issue by buimichael** [WoWAnalyzer/WoWAnalyzer#16]
This might be a bad idea since some "bad" talents and talent combination might be considered good/decent in some use cases.

Some encounters may even require you to spec a "bad talent", however this can be solved with checking the encounter ID. However that would in the long term be hard to maintain.

**Comment by MartijnHols** [comment]
Thanks for the suggestion. Adding suggestions or checklist rules for bad talents is up to contributors. There's already a precedent with talents such as Judgment of Light. I don't think a core change will help this and it if you have anything specific in mind I suggest making a separate issue per talent so I am closing this issue.
