### ISSUE TITLE
Add back the Mana usage chart

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1601]
In https://github.com/WoWAnalyzer/WoWAnalyzer/commit/16b3f3ac4a66be892dd31052f13989d963e4f877 all remaining charts using the deprecated Chartist library were removed so the dependency on this package could finally be removed.

In order to provide this functionality again, it needs to be re-implemented using the Chart.js library instead. The differences in chart libraries shouldn't be big.
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=57402077)](https://www.bountysource.com/issues/57402077-add-back-the-mana-usage-chart?utm_source=57402077&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by YogeshSharma0201** [comment]
This issue was resolved in #1633.
