### ISSUE TITLE
Horizontal Page Overflow / Death Position

### ISSUE THREAD

**Issue by kayla-glick** [WoWAnalyzer/WoWAnalyzer#1628]
I noticed when viewing one player's log that there was horizontal scroll on the page and a large blank section off to the right side of the main content. After investigating further, I found that the culprit is the `<div class="death">` element in the **Timeline** section.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/12898988/39322424-d53f5b32-4957-11e8-9c30-7c0bd0dfb843.png">

**Comment by MartijnHols** [comment]
Good investigative work, thanks!

Do you have a log where this can be verified?

**Comment by kyle-glick** [comment]
https://wowanalyzer.com/report/2KCapkwHBhMGYPtZ/3-Normal+Varimathras+-+Wipe+1+(1:42)/1-Matabear/timeline

Original Log
https://www.warcraftlogs.com/reports/2KCapkwHBhMGYPtZ/#fight=3&source=1

I noticed that Matabear dies at 1:07, which is what the death element says, but it's not showing up on the timeline because of whatever is causing its position to bug out.

**Comment by Pewtro** [comment]
Yeah it's a mac only issue. 

Unable to reproduce on Win10 Edge, Opera and Chrome
Can reproduce on Mac OSX High Sierra 10.13.4 Chrome, Opera and Safari.

**Comment by MartijnHols** [comment]
Yeah I believe it's an issue on Mac OSX and the provided solution probably solves this, but I'd like to try and understand the cause before proceeding to ensure we're not missing anything.

The `gm-scroll-view` element is contained in a `gm-scrollbar-container`;

![image](https://user-images.githubusercontent.com/4565223/39326410-28bcac8c-4995-11e8-8f7d-5958a8832e52.png)

Which gets position relative already;

![image](https://user-images.githubusercontent.com/4565223/39326442-41101c56-4995-11e8-86a1-d3f93c3a2394.png)

If I remember correctly iOS - and thus probably Mac OS too - dislike scrolls in scrolls and try to stretch them out. I'm guessing this is what might be happening here. This might lead to other issues such as the scrollbar not appearing or working.

Unfortunately I don't have a device where I can reproduce this and verify correct behavior.

**Comment by Pewtro** [comment]
I'll see if I can get some testing done sunday

**Comment by MartijnHols** [comment]
this has been fixed
