### ISSUE TITLE
Holy Priest: add divinity uptime to analyzer

### ISSUE THREAD

**Issue by cptwonton** [WoWAnalyzer/WoWAnalyzer#1646]
divinity uptime is hugely important, the idea is to use your holy words (sanctify, serenity) as liberally as possible, in order to keep the divinity (+10% heal) uptime as high as possible so that boosting all your other heals by 10% for 6 seconds is able to outweigh any differnce between a suboptimal, liberal holy word vs holding a holy word for a better time.

**Comment by enragednuke** [comment]
This has been part of the holy priest analyzer for over 7 months. 

https://github.com/WoWAnalyzer/WoWAnalyzer/blob/master/src/Parser/Priest/Holy/Modules/PriestCore/Divinity.js

![image](https://user-images.githubusercontent.com/9220151/39926693-eba60578-556a-11e8-9dd3-fe9d96b36a57.png)
