### ISSUE TITLE
[Discipline][BFA Prepatch] Mastery: Reverence

### ISSUE THREAD

**Issue by rp4rk** [WoWAnalyzer/WoWAnalyzer#1661]
**Description:**
Mastery: Reverence is the new mastery for Discipline Priests in Battle for Azeroth. Instead of directly increasing the amount of healing Atonement does, it increases healing done to targets with Atonement. 

The passive is currently tuned at 1.2% per point of mastery.

**Ability Link:** https://beta.wowdb.com/spells/271534-mastery-reverence

**Open Questions:**
~~Should this be built into an overall larger pull request including stat weights?~~

**Acceptance Criteria:**
- [x]  HPS from mastery is viewable.

**Comment by karlpralow** [comment]
New Mastery: Your healing and absorption is increased by 10.0 (actually 9.6 in game) % on targets with Atonement.

**Comment by MartijnHols** [comment]
Should this be built into an overall larger pull request including stat weights?

Multiple smaller please!

**Comment by rp4rk** [comment]
Pull request opened.

**Comment by rp4rk** [comment]
Merged, cheers fellas.
