### ISSUE TITLE
[Discipline][BFA Prepatch] Luminous Barrier Talent

### ISSUE THREAD

**Issue by rp4rk** [WoWAnalyzer/WoWAnalyzer#1664]
**Description:**
Luminous Barrier is a new addition in Battle for Azeroth. It applies a medium-sized shield to all players in your party or raid. It will be crucial to maximise this shield as the talent replaces Power Word: Barrier.

**Ability Link:** https://beta.wowdb.com/spells/271466-luminous-barrier

**Acceptance Criteria:**
- [x] The analyzer shows how much absorption was wasted, and recommends replacing at a given threshold.

**Comment by karlpralow** [comment]
See PR #1677
