### ISSUE TITLE
Send people to another subdomain when parsing a log from a different patch

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1668]
E.g.
on www: -> bfa for BFA dungeons
on bfa -> www for Legion dungeons

In the future:
www -> legion for Legion dungeons

Extra:
Also recognize having an artifact weapon or whatever will be unique for the prepatch and send people to a future pre-prepatch subdomain.

**Comment by MartijnHols** [comment]
I think this should be solved by looking at talents and / or traits;

- Legion logs have Legion traits and talents active
- Prepatch logs have BFA traits and talents active
- BFA logs have BFA traits and talents active

Looking at instance would be unreliable since you can go back and do content.
Looking at date would be unreliable since different zones get different patch release dates.

**Comment by MartijnHols** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=58014862)](https://www.bountysource.com/issues/58014862-send-people-to-another-subdomain-when-parsing-a-log-from-a-different-patch?utm_source=58014862&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by MartijnHols** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=58014862)](https://www.bountysource.com/issues/58014862-send-people-to-another-subdomain-when-parsing-a-log-from-a-different-patch?utm_source=58014862&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by ndudnicz** [comment]
Since BFA will be released at the exact same date and time in every zones [(battle net post)](https://worldofwarcraft.com/en-us/news/21849061/battle-for-azeroth-one-launch-to-rule-them-all), BFA logs timestamps would also be > 1534197600 (08/14/2018 12:00AM CEST).

**Comment by MartijnHols** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=58014862)](https://www.bountysource.com/issues/58014862-send-people-to-another-subdomain-when-parsing-a-log-from-a-different-patch?utm_source=58014862&utm_medium=shield&utm_campaign=ISSUE_BADGE) (increased)

**Comment by sahalsaad** [comment]
Hi, I interested working on this. May I know where should I start? Thanks!

**Comment by sahalsaad** [comment]
Hi @MartijnHols ,

Sorry, I'm not wow player. I don't think I can work on this since I lack of testing data(report link) unless there is somewhere I can get the report link.

**Comment by Pewtro** [comment]
Hi @sahalsaad , 

This website has a lot of report IDs for you to use - https://www.warcraftlogs.com

Here is an example:
https://www.warcraftlogs.com/reports/k32Pc8CxBqtnDhM6

**Comment by MartijnHols** [comment]
@Alastair-Scott implemented this. Please don’t forget to claim the bounty.
