### ISSUE TITLE
Implement leech healing from damage in BaseHealerStatValues

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1686]
In (early) BFA having 0 Leech will be fairly common, so to make the stat more accurate it could be worth it. A simple way to do this is to include Leech from damage done.

Example log: https://bfa.wowanalyzer.com/report/wJYtQ6Lqj2NV8nvk/6-Normal+Taloc+-+Kill+(8:57)/29-Dreamguard/mana

**Comment by abelito75** [comment]
Closing as most healing specs have ditched this.
