### ISSUE TITLE
Trinket: WQ - Zandalari Loa Figurine

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1687]
![image](https://user-images.githubusercontent.com/4565223/40075049-9d409664-587b-11e8-965e-7028bd9e2ee5.png)
![image](https://user-images.githubusercontent.com/4565223/40075137-d5306022-587b-11e8-97ab-11b3c9cc9829.png)

**Comment by fyruna** [comment]
I'll add a ItemTracker for this trinket asap.

**Comment by fyruna** [comment]
Log to use: https://www.warcraftlogs.com/reports/fn9RM6AX7VxcJytv
