### ISSUE TITLE
Trinket: WQ: (Zandalari) Dinobone Charm

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1688]
![image](https://user-images.githubusercontent.com/4565223/40075072-a9060696-587b-11e8-80dd-32d0f9a091a5.png)

https://beta.wowdb.com/items/158155-dinobone-charm
https://www.warcraftlogs.com/reports/n1VyFWwJjXDhxr4A/#fight=1&type=summary&source=2

**Comment by Teladra** [comment]
https://www.warcraftlogs.com/reports/n1VyFWwJjXDhxr4A/ logs on holy paladin with Dinobone Charm. I believe they changed the name of this trinket to only Dinobone Charm
![image](https://user-images.githubusercontent.com/40807178/42242750-9eae5c9e-7f17-11e8-93ca-2b7888ca3059.png)

**Comment by abelito75** [comment]
Are these trinkets still needed?
