### ISSUE TITLE
Trinket: WQ: Pearl Diver's Compass

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1689]
![image](https://user-images.githubusercontent.com/4565223/40075109-b96fe25e-587b-11e8-9fcc-5faa369e477b.png)
![image](https://user-images.githubusercontent.com/4565223/42240117-8c135cbc-7f06-11e8-98c6-8967de4585ea.png)

**Comment by abelito75** [comment]
Are these trinkets still needed?
