### ISSUE TITLE
Trinket: Atal'Dazar: Revitalizing Voodoo Totem

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1692]
![image](https://user-images.githubusercontent.com/4565223/40075199-03044928-587c-11e8-9b38-0cccd7d56da4.png)
![image](https://user-images.githubusercontent.com/4565223/40075203-060afff4-587c-11e8-99bd-008c9f683e9c.png)
![image](https://user-images.githubusercontent.com/4565223/40075213-08e57272-587c-11e8-9c9a-591adb5b92e2.png)

**Comment by Anatta336** [comment]
M+ log with a MW Monk using the trinket:
https://www.warcraftlogs.com/reports/mtnTNQd3jYZcykCH#fight=4&source=38&type=summary
Healing appears to be attributed to spellId 266018:
http://www.wowhead.com/spell=266018/touch-of-the-voodoo
