### ISSUE TITLE
Trinket: Shrine of the Storm: Conch of Dark Whispers

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1693]
![image](https://user-images.githubusercontent.com/4565223/40075235-185ee896-587c-11e8-9a26-81c3c643b2e2.png)
![image](https://user-images.githubusercontent.com/4565223/40075240-1b74f75a-587c-11e8-9ffb-eef36f24019f.png)
![image](https://user-images.githubusercontent.com/4565223/40075242-1dfc590a-587c-11e8-899a-5a2e929f5e13.png)
https://bfa.wowhead.com/item=159620/conch-of-dark-whispers&bonus=4777:1482

**Comment by MartijnHols** [comment]
I implemented this trinket's buff in stat tracker already; when adding a statistic for this trinket please replace the hard-coded spell ids with the appropriate spell/item objects.

https://github.com/WoWAnalyzer/WoWAnalyzer/blob/e5d9b81e22f85618352d23043bdd79eb14a78c1a/src/Parser/Core/Modules/StatTracker.js#L305-L308

**Comment by Teladra** [comment]
https://www.warcraftlogs.com/reports/n1VyFWwJjXDhxr4A/ logs with Conch of Dark Wispers on holy paladin
