### ISSUE TITLE
Trinket: Siege of Boralus: Hadal's Nautilus

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1694]
![image](https://user-images.githubusercontent.com/4565223/40075250-295cb8a8-587c-11e8-840c-ba16fe3c764b.png)
![image](https://user-images.githubusercontent.com/4565223/40075252-2c0b8840-587c-11e8-8d86-5d1ab78ac527.png)
![image](https://user-images.githubusercontent.com/4565223/40075256-2e3acda6-587c-11e8-8128-2c65135b869f.png)

**Comment by Anatta336** [comment]
M+ log with a Destruction warlock using the trinket:
https://www.warcraftlogs.com/reports/bmgDAF2NpkCL3aV1#fight=last&source=1
Damage appears to be done by spellId 270925:
http://bfa.wowhead.com/spell=270925/waterspout
