### ISSUE TITLE
Trinket: Tol Dagor: Ignition Mage's Fuse

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1697]
![image](https://user-images.githubusercontent.com/4565223/40075335-5f924df2-587c-11e8-9327-dc9b0451af7b.png)

**Comment by MartijnHols** [comment]
I implemented this trinket's buff in stat tracker already; when adding a statistic for this trinket please replace the hard-coded spell ids with the appropriate spell/item objects.

https://github.com/WoWAnalyzer/WoWAnalyzer/blob/e5d9b81e22f85618352d23043bdd79eb14a78c1a/src/Parser/Core/Modules/StatTracker.js#L309-L312

**Comment by Anatta336** [comment]
M+ log with a Holy paladin using the trinket:
https://www.warcraftlogs.com/reports/bmgDAF2NpkCL3aV1#fight=last&source=2
BuffId appears to be 271115:
http://bfa.wowhead.com/spell=271115/ignition-mages-fuse

**Comment by MartijnHols** [comment]
Mythic Vectis Holy Paladin using the trinket: https://wowanalyzer.com/report/rxDjbR7VKmJLdWHk/3-Mythic+Vectis+-+Kill+(7:50)/1-Kvaernq

**Comment by 5chmidt** [comment]
I'll start working on this item.

**Comment by Juko8** [comment]
This was implemented in #3165
