### ISSUE TITLE
Trinket: Waycrest Manor: Balefire Branch

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1698]
![image](https://user-images.githubusercontent.com/4565223/40075360-6c8527c8-587c-11e8-8246-00ea362a8852.png)
![image](https://user-images.githubusercontent.com/4565223/40075368-6ea27d8a-587c-11e8-8385-fca2563c9726.png)
![image](https://user-images.githubusercontent.com/4565223/40075373-70fda33e-587c-11e8-9ab3-99bcf735ead4.png)

**Comment by Anatta336** [comment]
M+ log with a MW monk using the trinket:
https://www.warcraftlogs.com/reports/mtnTNQd3jYZcykCH#fight=4&source=38&type=summary
Buff appears to be 268998:
http://bfa.wowhead.com/spell=268998/kindled-soul

**Comment by MartijnHols** [comment]
Do none of the stat scaling methods work? Trinket effects don’t consistently use the same formula for stats, sometimes it’s the primary stat, then secondary stat and other times a trinket specific formula. They should all be implemented.
