### ISSUE TITLE
Trinket: The Underrot: Vial of Animated Blood

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1720]
trinket: https://bfa.wowhead.com/item=159625/vial-of-animated-blood&bonus=4777:1482 / https://beta.wowdb.com/items/159625-vial-of-animated-blood
log: https://www.warcraftlogs.com/reports/fn9RM6AX7VxcJytv/#fight=9&source=83&type=auras&ability=268836&view=events

![image](https://user-images.githubusercontent.com/4565223/40273506-538fa2d2-5bc1-11e8-8a3c-8951bc35bbf8.png)

Looking at the log I think this will require custom handling to handle it properly in the stat tracker. I think it applies 3 stacks on use, while logs suggest it only has 1 stack upon application.

Each stack probably has 1/3 the in-game shown amount of stats.

**Comment by Anatta336** [comment]
M+ log with Arms warrior using the trinket:
https://www.warcraftlogs.com/reports/bmgDAF2NpkCL3aV1#fight=last&source=4
Buff appears to be 268836:
http://bfa.wowhead.com/spell=268836/blood-of-my-enemies

**Comment by 5chmidt** [comment]
Does anyone know if this is linear decay?  Looking at the [log](https://www.warcraftlogs.com/reports/bmgDAF2NpkCL3aV1#fight=last&source=4&type=auras&target=4&view=events&ability=268836) it looks like initial use will apply the full amount, then it will decay twice then drop off.   

My thought he is:
Seconds 0-6 full strength
Seconds 6-12 strength * 0.5
Seconds 12-18 strength * 0.25

I can't find how much strength is applied from the logs, and I don't have the trinket myself to verify.
Thanks,
