### ISSUE TITLE
Death log improvements

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1737]
Some ideas:

- Enable by default for all specs (e.g. by hiding the columns that need configuration)
- Documentation
- Link back to WCL
- Show who healed you
- Show who damaged you
- Prettify the slider (same for Low Health Healing tab)
- I think it should sort the personals based on the timeline sort order; for Holy Paladins this is the list but things like cleanse, steed and blessings are lower prio and less often relevant
![image](https://user-images.githubusercontent.com/4565223/40579405-e2c34dfe-6126-11e8-97e4-8e00744d6826.png)
(also I like things having static ordering regardless of their state)
- Make the damaging ability a spell link so it's tooltipable

**Comment by joshinat0r** [comment]
Might be interesting primarily for tanks: 
The death is currently showing defensive debuffs on targets (like warriors demo shout) if the event was a damage event. We could expand on that and add buffs on the target for mechanics like KJs Felclaws. 
And when talking about felclaws, might be important to add stacks to all buffs&debuffs.

But just adding that to the current layout would make it really cluttered, so it could use a rework (esp when we want to add who healed/damaged the player aswell)

**Comment by MartijnHols** [comment]
Actor could be hidden behind a tooltip

**Comment by joshinat0r** [comment]
added with #1748 :
- abilities have now spell-links
- the amount reveals who healed/damaged you (and shows how much absorbed/overhealing was done, should also help explaining what O and A means)
- cooldowns are now ordered by their timelineIds, regardless of their cooldown-state
- link to take the user to WCLs death-pane

**Comment by MartijnHols** [comment]
All important things were implemented, so closing this issue.
