### ISSUE TITLE
Better cast efficiency for spells with cast time and resets

### ISSUE THREAD

**Issue by Gebuz** [WoWAnalyzer/WoWAnalyzer#1747]
Currently cast time spells like Healing Rain and Ebonbolt can not reach 100% cast efficiency because they will always have a time off cooldown between the spell coming off cooldown and the cast completing. It can probably be solved by adding a cast time prop to abilities and accounting for that when calculating the cast efficiency. To be completely accurate it would have to account for the haste at the time of the cast.

Spells like Mangle that has a chance to reset on other casts can not reach 100% cast efficiency either because it always needs the full GCD from the cast that procced it to run its course before it can be cast. I'm not sure exactly what the best way to solve this would be, but it would likely include summing up the duration of all the GCDs after a proc and accounting for those same way as the cast times above.

This changes would mean that cast efficiency is no longer equal to 100%-timeOnCooldown, so we need to make sure that we don't display it as "Time on cooldown" when using the efficiency.

**Comment by Gebuz** [comment]
I've been thinking about how this could be done.

Channel time:
 - if a spell does not have multiple charges add averageCastTime to averageCooldown when calculating the cast efficiency here:
https://github.com/WoWAnalyzer/WoWAnalyzer/blob/eb8fcfd489ac1bd7c0a695c6657cfe07a0c27885/src/Parser/Core/Modules/CastEfficiency.js#L129
 - Make a function to get the average cast time for a given ability. Should be as simple as adding the times between any casts and the previous begincast events and dividing by the total number of begincast events.
 - Consider copying the cast bar down to the cooldown line on the timeline to visually indicate the efficiency.

GCD and resets:
 - if a spell is on the GCD and does not have multiple charges, add AverageTimeOnGCD to averageCooldown when calculating the cast efficiency. (Note that a spell could have both a cast time and resets like Lava Burst)
 - we need: Reset times ('endcooldown' events where start + expectedDuration > end), GCD going at the time (need a buffer here in case the "reset buff" is applied before the cast event).
 - how to handle partial GCDs (off the GCD procs like lava surge from dot ticks). Maybe have a prop for it  in ability.js so we can handle it differently. Check if there was a GCD active at the time of the proc and if there was add only the time from proc to end of GCD. Could also ignore the prop and just use this whenever it is outside the buffer window, but would add +-bufferMS in inaccuracy.
 - consider copying the GCD (or partial GCD) bar down to the cooldown line on the timeline to visually indicate the efficiency.

I'm not sure how to handle spells that does not start their cooldown until the buff is consumed (Warrior of Elune for instance). Technically it goes on cooldown as soon as it is cast, but for cast efficiency it should really be using the minimum time which in the case of Warrior of Elune would be 2 GCDs (which can be reduced by empowerments <.<) + cooldown.

**Comment by Gebuz** [comment]
![image](https://user-images.githubusercontent.com/6773230/41505723-fe506298-720e-11e8-917f-9b8de9d1b824.png)
So to understand this correctly, would you still want "Time on CD" and not "Usage" to be displayed in the abilities tab? I'm thinking maxCasts should definitely be adjusted to account for cast time.

**Comment by Gebuz** [comment]
Cast time implementation so far:
https://github.com/Gebuz/WoWAnalyzer/commit/142e649f8f089b91061778d9c31c80868f1ed5b0

**Comment by MartijnHols** [comment]
Yeah maxCasts should be adjusted, I was thinking about what shows in the suggestion and is used for the checklist value. The abilities tab could show "usage" instead of "time on cooldown", or maybe "Used cast time available".

**Comment by Gebuz** [comment]
Naming it is pretty tricky and tooltip gets pretty long. "Usage" I feel would be a bit weird when it doesn't match the casts (1/1 cast and 80% usage sounds weird to me, would be logical if it was 100%). "Unavailable" is probably the most correct word to describe it, but it's also the least user friendly. Maybe the best would be to keep the name "Time on Cooldown" and simply explain the details in the tooltip, something along the lines of "A spell is also considered on cooldown if it does not have multiple charges and is unavailable due to cast time or waiting for the GCD after a reset to finish."

**Comment by MartijnHols** [comment]
1/1 casts should be 100% usage, we decided on that with cast efficiency 2.0. If it doesn't do that, that's a bug. It can do 80% with 1/2, which would mean you only had about 20% of the fight to cast it a second time. Maybe that too is too strict and we should go even further with the *efficiency* and be more forgiving. It would reduce the comments people have about us not being as accurate on fights with downtime.

"Potential Cast Time Usage" could be a thing. I know it seems a lot more complex, but that could be a strength as it creates no illusions that it's simple. But this still feels like the wrong solution. I do like your Time on Cooldown proposal as well, though that would be slightly more misleading (I'm also thinking about the suggestions which don't include those tooltips).

How about "Cast Efficiency" or "Efficiency" and making the max not max casts but the configured recommended efficiency? The creates no illusions about the underlying implementation of the efficiency and probably is closer to what users expect to see in the bar in the abilities tab.
Then we could have things at 120% efficiency, which I think most of the time would be nice too. 
We could still show Time on Cooldown as a separate column, or remove it completely.

**Comment by Gebuz** [comment]
One problem I see with having it as a percent of the suggestion is that it makes it very subjective. I think it's better if we keep it very clear what is suggestions and what is objective efficiency.

One thing to keep in mind is that it is only a few abilities that are actually affected by this, which I think is a good argument for keeping it as "Time on Cooldown" and just adding the extra details to the tooltip.

Otherwise I like "Potential Cast Time Usage", althought it might be a bit too complex of a name for the users.

I've made a PR #1797 for adding Cast time and On the GCD resets. I realized I couldn't think of a single off the GCD proc that resets a cooldown without charges (but it would be pretty easy to extend it to also account for those if necessary). I'm still considering how to handle spells that start their cooldown on a buff expiration like Warrior of Elune.

**Comment by MartijnHols** [comment]
This was implemented and can be closed right?

**Comment by Gebuz** [comment]
Yup, I still need to find a solution for Warrior of Elune, but accounting for how long the buff SHOULD be up before being consumed is basically impossible as it depends on the situation (I can't just do X time after cast). So I'll likely just leave WoE as it is for now and pray blizzard changes it to start cooldown on cast instead.
