### ISSUE TITLE
[Holy Priest] Track resets of Desperate Prayer

### ISSUE THREAD

**Issue by joshinat0r** [WoWAnalyzer/WoWAnalyzer#1749]
Holy Priests have a [trait](http://www.wowhead.com/spell=238100/times-and-measures) that resets [Desperate Prayer](http://www.wowhead.com/spell=19236/desperate-prayer) on damage taken.
Currently not implemented, not even sure if its trackable in the combatlog.

**Comment by enragednuke** [comment]
Last I checked the resets were not tracked in combat logs, so it's not possible to implement this.

Albeit this was over half a year ago, but I don't remember hearing anything about it being changed since.
