### ISSUE TITLE
Raid Overview Feature

### ISSUE THREAD

**Issue by Evantually** [WoWAnalyzer/WoWAnalyzer#1758]
This is a feature I would like to work on with some help. The idea is to make an overview of all the wipes over the course of the raid night separated by boss. For example, this would have a list of the encounters split by boss similar to how the attempts currently are listed and selected. For the report itself I would like a format similar to the checklist/suggestions:

"15 of 20 attempts you did not maintain your DoTs on the boss." The dropdown would display the uptimes for all attempts.
"13 of 20 attempts you failed to use your supportive abilities." The dropdown would again display the average for all attempts.

**Comment by Sharrq** [comment]
Its an interesting idea. Not sure if the WCL Query Limitations would prohibit pulling that amount of data though. Worth looking into though imo

**Comment by Sharrq** [comment]
Also just to add, Wipefest already provides some of this functionality (showing all the wipes and what people died to .... though it doesnt show (afaik) the player's performance over the course of a night

**Comment by plnd2ez** [comment]
Thanks Sharrq. I did check out Wipefest to see what information is already on there, and that is really good for tracking the big mistakes. The idea of this feature I think tracks more closely to the purpose of WoWAnalyzer being a personal parse-improvement tool.

I've tried sifting through the code to determine where to start on this, and currently reading through pieces of the wiki. I have the fork set up and ready to start making modifications, but don't know what's required for what I'm proposing. All my experience in coding thus far has been relatively tame.

**Comment by Sharrq** [comment]
Before you get too far, you might want to talk to Zero about it. I know there are query limitations to WCL as far as the number of queries and such we can do. So you might want to confirm whether this is possible within our query limitations before you spend too much time on it.

**Comment by MartijnHols** [comment]
Unfortunately I think we can’t afford the queries required to achieve this without further changes to combat hitting the rate limit. Think things such as a request queue, restricting API calls during heavy load, etc.

**Comment by Evantually** [comment]
Closing issue as this doesn't seem possible with the current limitations.

Thank you all for the feedback.
