### ISSUE TITLE
[Bug] Searching in events with fabricated events enabled causes a crash

### ISSUE THREAD

**Issue by Gebuz** [WoWAnalyzer/WoWAnalyzer#1795]
How to reproduce:
Go to the Events tab, enable fabricated events and type anything into the search bar.
![image](https://user-images.githubusercontent.com/6773230/41668390-843b5460-74af-11e8-8fa3-d4192f437e77.png)

**Comment by scottymcraig** [comment]
Cannot confirm this bug.  Tested on [this page](https://wowanalyzer.com/report/DzM82hYxkP7cNT6v/16-Heroic+Imonar+the+Soulhunter+-+Kill+(4:23)/18-Raxah/events).  Turned Fabricated events on.  Tried to search and it searched fine.

Can you maybe let us know which URL you were on when this happened?

**Comment by Gebuz** [comment]
It was happening in literally every log for me. Looks like it doesn't happen anymore though, so I'll close this.

**Comment by MartijnHols** [comment]
Likely spec specific, to do with fabricated events
