### ISSUE TITLE
Update all specs for prepatch

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1796]
Let's try to update all specs for prepatch. The essential things are: no crashes, abilities should be accurate, and checklist/suggestions should be helpful. Once all specs have the essentials done we can start thinking about fixing GCDs, cooldown resets and implementing checklists.

**Any help on some of the specs that aren't maintained would be greatly appreciated.** It doesn't have to take a lot of time. It helps to have a character of the class at max level so you can go through the spellbook. For the suggestions it might help to join the class Discord and look at manual log reviews and reproduce their suggestions.

- Death Knight
  - [x] Blood @joshinat0r
  - [x] Frost
  - [ ] Unholy
- Demon Hunter
  - [ ] Havoc
  - [ ] Vengeance
- Druid
  - [x] Balance @Gebuz 
  - [x] Feral @Anatta336
  - [x] Guardian @Gebuz
  - [ ] Restoration
- Hunter
  - [ ] Beast Mastery
  - [ ] Marksmanship
  - [ ] Survival
- Mage
  - [x] Arcane @Sharrq
  - [x] Fire @Sharrq 
  - [x] Frost @Sharrq 
- Monk
  - [x] Brewmaster @emallson
  - [x] Windwalker @Juko8 
  - [x] Mistweaver @anom0ly
- Paladin
  - [x] Holy @MartijnHols
  - [x] Protection @joshinat0r
  - [x] Retribution @Juko8
- Priest
  - [x] Discipline @rp4rk @karlpralow 
  - [x] Holy @niseko
  - [x] Shadow @MartijnHols
- Rogue
  - [x] Assassination @MartijnHols
  - [x] Outlaw @MartijnHols
  - [x] Subtlety @MartijnHols
- Shaman
  - [x] Elemental @HawkCorrigan
  - [x] Enhancement @HawkCorrigan 
  - [x] Restoration @niseko
- Warlock
  - [x] Affliction @sMteX
  - [x] Demonology @sMteX
  - [x] Destruction @sMteX
- Warrior
  - [x] Arms @MartijnHols
  - [x] Fury @MartijnHols
  - [x] Protection @joshinat0r

*Ticks mean it's taken care of or being taken care of.*

**Comment by Sharrq** [comment]
Frost Mage is done as far as functionality. Just waiting for number tuning to determine whether the rotation is changing at all

**Comment by MartijnHols** [comment]
I plan on going through as much as I can after finishing up the premium stuff.

**Comment by Sharrq** [comment]
Im close to finishing fire, and arcane should be easy seeing as there is barely anything there. I can try and help with some other specs once i finish those.

**Comment by Gebuz** [comment]
Balance was ready before yesterdays build :( 
Not much to change though so will be ready soon. I'll likely have to remove Empowerment tracking because it is currently impossible to track the random procs and for some reason the combatlog doesn't show the stacks (!??!). Kinda sucks cause it's one of the most important statistics.

**Comment by Juko8** [comment]
Everything essential in Windwalker is ready for BfA. 

I've considered putting some work on the Retribution analyzer, what is the status on that @CollCrom ? Just asking to avoid doing duplicate work.

**Comment by CollCrom** [comment]
@Juko8 I stopped play a big ago and its looking unlikely I will be playing in BFA so feel free to work on it =]

**Comment by joshinat0r** [comment]
Blood Death Knight is finished (at least Analyzer wide, need to remove traits + update changelog-spellLinks)

Working on Prot Warrior right now, majority of work is already done but still needs minor adjustments for rage gen from damage taken and adjustments to uptime thresholds.

Planning on picking up Prot Paladin after Warrior is finished unless someone else is already planning to / working on it.

**Comment by MartijnHols** [comment]
@CollCrom Thanks for letting us know! 💯 

Nice to see so many specs are being taken care of! 🥇 

The focus of this issue is on the essentials only, I think it's important this step is ready preferably before patch release. I'll try to squeeze in updating some of the specs no longer being maintained so at least their core is right. I only have half the classes at max level, so I'm not sure if I can do some of the others. I guess I still have a 110 boost. 😝

**Comment by niseko** [comment]
Resto Shaman should be pretty much done apart from minor things, might need to change some stuff for 110 values instead of level 120 for the prepatch.

Thinking about picking up holy priest by Tuesday if there's nothing done for it by then, as that's quite in a dire state right now - at least for the essentials as I haven't played the spec since ToV :grimacing:

**Comment by Anatta336** [comment]
Feral Druid doesn't need much for prepatch support which I'd be happy to take care of. The spec as a whole is still missing things, which are gradually getting added in.

**Comment by MartijnHols** [comment]
Paladin, Monk, Hunter, Priest and Shaman, so those I could get to when I have time. I have one 110 boost, though using it on something I won't be playing would feel like a waste. Might do Rogue.

**Comment by HawkCorrigan** [comment]
I'll do Ele Shaman
Just got beta access so I'm tying to break everything I can and start implementing stuff now

**Comment by emallson** [comment]
Brewmaster is up-to-date for current beta, aside from some of the more advanced BS that depends on knowing stagger %s.

**Comment by Sharrq** [comment]
Im doing Arcane also, its almost done.

**Comment by Gebuz** [comment]
Guardian done: #1816

**Comment by MartijnHols** [comment]
I just updated Outlaw; turns out new chars on beta are 110 automatically. I might do some other Rogue specs when I get more time.

**Comment by MartijnHols** [comment]
# How to update a spec for the prepatch

1. In-game: On beta/ptr go to a training dummy
2. In-game: Switch to the spec you wish to work on
3. In-game: Ignore all talents for now
4. In-game: Make sure you have some Haste (0-10% is generally good).
5. In-game: Execute this command (/reload to deactivate it)*1:
```
/run GCDE=GCDE or CreateFrame('FRAME', 'GCDE');GCDE:RegisterEvent('UNIT_SPELLCAST_SUCCEEDED');GCDE:SetScript('OnEvent', function (_,_,_,_,id) print(select(1,GetSpellInfo(id))..":",(select(2,GetSpellCooldown(id)))*1000);end);
```
5. In-game: Move the client to a different monitor
6. In-game: Open spellbook
7. Editor: Open the Abilities module for your spec
8. Editor: Move to the top of the file, go into the `spellbook` method and start at the top of the array (move everything down a few lines (enter) so you know what's new and what's old)
9. In-game: Start with the first spell and work your way to the last thing in the spellbook (include EVERYTHING)
10. Editor: Add the spell.
    1. Editor: CTRL-F the name of the spell to see if it already exists. If it does, cut & paste that object to the top.
    2. Editor: If it's a new spell copy another spell and change its `spell` property. The spell you're adding might not exist yet in the SPELLS file, in that case open the SPELLS file for your class and add it.
11. Editor: Configure the spell. See the [[Abilities|Module:-Abilities|]] wiki for info about all the available properties.
    1. In-game: Use the spell. The macro will print the GCD of the ability. If it's a nice round number, it's generally a static GCD. If it's something like `1431` (and your Haste is low) it's safe to assume it has a base GCD of 1500 that scales with Haste. `963` would suggest 1000ms-haste, `1000` would suggest static.
    2. Editor: Configure the GCD. Set it to `null` for spells off the GCD.
    3. In-game: Check the cooldown: No cooldown = remove the property. White cooldown = static cooldown (doesn't scale with Haste). Green cooldown = scales with Haste. A 6.9s CD would suggest a 7 sec base CD before Haste.
    4. In-game: don't forget to look for charges!
    5. It generally makes it easier to forget about talents until you've added all base spells.
12. In-game: Check the passives; if they do any form of cooldown reduction (CDR) you will have to account for that. Sometimes you need a module to account for CDRs. One example of such a module is the Subtlety's DeepeningShadows module.
13. In-game: Open talents and go through them one by one. Look for talents that modify abilities or give new abilities. Add the talent-abilities like the other spells but toggled by an `enabled` property, and account for the rest via conditionals (e.g. ternaries).
14. Browser: Go to https://www.wowhead.com/class-changes-in-battle-for-azeroth, scroll down to the spec selection and open the page for your spec. Make sure any abilities removed aren't in the list anymore, and you applied all changes listed.
15. Git: Commit changes and make a PR.
16. Git: Create a new branch (base it on your current branch).
17. Editor: Go through all modules, remove anything to do with traits and update everything to match the new game version (e.g. add/remove abilities from a resource tracker).
18. Git: Commit changes and make another PR.

*1. `UNIT_SPELLCAST_SUCCEEDED` only works for instant casts, replace it with `UNIT_SPELLCAST_START` for cast time abilities.

**Comment by anom0ly** [comment]
Just did a PR for MW and that is all merged. Should be good to go for pre-patch.
