### ISSUE TITLE
[BFA] [Destruction] Finish updating for BFA

### ISSUE THREAD

**Issue by sMteX** [WoWAnalyzer/WoWAnalyzer#1807]
Destruction hasn't received a lot of changes to be honest, so it's basically just look at the shard tracking system:
- [x] ideally replace it with ResourceTracker, but I'm afraid it might not be possible if the fragment generating events are still not being shown by WCL
- [x] if it isn't possible to replace entirely, try to combine SoulShardEvents with the ResourceTracker instead
- [x] if this isn't possible either, just revise the numbers if they're correct and leave it be

- [x] ~also, newest BFA build removed Infernal's shard cost and tweaked Soul Fire to have shorter CD (reduced furthermore by spending shards) and not cost a shard~
- [x] ~verify the behavior of BFA Fire and Brimstone talent, change in code~

(both of them added as a TODO to fix later)

**Comment by Gebuz** [comment]
Just an FYI, resource tracker also has support for invisible generation events:
https://github.com/WoWAnalyzer/WoWAnalyzer/blob/c81403a4dba387b3e984642cbf14fda4b9913228/src/Parser/Core/Modules/ResourceTracker/ResourceTracker.js#L62
so you can do whatever you do now to track it and add it through that.
