### ISSUE TITLE
Trinket: WQ - Gilded Loa Figurine

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1854]
![image](https://user-images.githubusercontent.com/4565223/42239999-18ae14ce-7f06-11e8-8863-2d48f6e6c3d5.png)
http://bfa.wowhead.com/item=158153/gilded-loa-figurine&bonus=0

**Comment by MartijnHols** [comment]
Looks like it's the same as #1687 except it has a different passive secondary stat.

**Comment by niseko** [comment]
quite sure its the same item, and they renamed it a while ago. if you use the item ID shown in the screenshot of #1687 you get the gilded one  -> https://bfa.wowhead.com/item=158153/gilded-loa-figurine

**Comment by MartijnHols** [comment]
In that case implementing this issue might involve making sure & then renaming the module implemented in #1687.

**Comment by Anatta336** [comment]
M+ log with a Discipline priest wearing the trinket:
https://www.warcraftlogs.com/reports/hCf4n9Nbqt6PzZpA#fight=12&source=4
BuffId looks to be 273974:
http://bfa.wowhead.com/spell=273974/will-of-the-loa

**Comment by niseko** [comment]
#1880
