### ISSUE TITLE
Add static cd / base cd props to Abilities

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1857]
The CD prop's approach of having to do the calculation manually is old. It solves the same problem as the `gcd` prop. We should use a solution similar to the `gcd` prop's solution instead.

One thing I dislike about the `gcd` prop is using `null` for "not on the gcd". I think we should either use `gcd: 0,`  or `gcd: { static: 0 },` instead. This is something to consider for the cd prop too.

**Comment by abelito75** [comment]
Is this still an issue?
