### ISSUE TITLE
Setup automated SpellData extraction whenever a game build is pushed

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1884]
simc generates SpellData from actual game data. When SpellData is changed, they update giving a nice clean diff of the changes. Example: https://github.com/simulationcraft/simc/commit/84d4e140c66eab54b32ca7116fa261b2ffdebe16 Having an easy way to see accurate spell changes could allow us to be informed quicker and make updating easier, any commits will trigger a message in the #updates channel (or perhaps a new channel; #game-updates), and opens up new (future) options of using this data in our analysis to reduce the amount of manual configuration needed.

This spell data can be used for other things as well, for example:

- (Further) automating talent/spell generation (SPELLS folder)
- Improve accuracy (wowhead/wowdb are generally less accurate)
- Custom spell pages/tooltips (though low prio since Wowhead has gotten pretty good)

The following is a required deliverable for this issue:

**A Docker image that fetches the latest game data and runs spell extraction on it, leading to JSON files for the spells with 1 JSON file per spell, grouped in folders by their type. Must fully work on the command line, without anything preinstalled (i.e. must run in Travis).**

Old requirements:

> I'm thinking steps to implementation would be something like:

> 1. Setup a new repo in the organization (any admin can do this), called something like "GameData" (I'd want ItemData at a later point too, so SpellData would be incomplete - item data won't be required for the bounty). Better name suggestions welcome. NOTE: For development you should make a repo on your own profile
> 2. Get spell extraction working locally
> 3. Setup a WoWAnalyzer GitHub bot user that has write access to the new repo
> 4. Setup a script to either check the CDN for changes (polling) OR listen to a webhook (slightly > preferred) from something like Blizztrack - this should run in a separate Docker container.
> 5. When script is called make a new commit to the GameData repo: `git commit --allow-empty -m "New build available: 8.0.1.27075 (travis-extract)"`
> 6. This commit triggers a new TravisCI build (note: you have to check for `travis-extract` to be in the commit message so it doesn't lead to an endless loop)
>    1. The Travis build pulls the latest game data from the CDN
>    2. It runs the spell extraction
>    3. It commits the new spell data (e.g. commit message `Spell data for patch 8.0.1.27075`)
>    4. It pushes the new spell data

**Comment by MartijnHols** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=60881451)](https://www.bountysource.com/issues/60881451-setup-automated-spelldata-extraction-whenever-a-game-build-is-pushed?utm_source=60881451&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Pewtro** [comment]
A worthwhile thing to note that was actually raised to me is that hotfixes don't show in the CDN. 
They'll only show in a DBCache pull from a player that has logged into the game (after hotfixes are applied) then logged out and retrieved and extracted. This is how SimC gets the hotfixes.

**Comment by MartijnHols** [comment]
Updated the OP to further limit the scope.

With @Pewtro's information, another requirement would be that the Docker image could be run locally on top of an existing game installation.

**Comment by MartijnHols** [comment]
Increased to $500: [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=60881451)](https://www.bountysource.com/issues/60881451-setup-automated-spelldata-extraction-whenever-a-game-build-is-pushed?utm_source=60881451&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by MartijnHols** [comment]
Closing to reclaim the Bountysource bounty due to changes to their ToS.

Not reopening since this issue has not had any progress and needs to be rethought.
