### ISSUE TITLE
Trinket: Uldir: Inoculating Extract

### ISSUE THREAD

**Issue by niseko** [WoWAnalyzer/WoWAnalyzer#1909]
![image](https://user-images.githubusercontent.com/2842471/42801161-eadd741a-899e-11e8-9d83-82fcdd910124.png)
https://beta.wowdb.com/items/160649-inoculating-extract

**Comment by 5chmidt** [comment]
Tested with this log:
https://www.warcraftlogs.com/reports/9x3DjdRvQAJzLmnt#fight=10&type=healing&source=8

The trinket is only used once during the encounter but the healing is accurately recording on production build.  Is there anything else that needs to be done here, or can this be closed?

**Comment by Pewtro** [comment]
Thanks for noticing 👍
