### ISSUE TITLE
Trinket: Uldir: Vigilant's Bloodshaper

### ISSUE THREAD

**Issue by niseko** [WoWAnalyzer/WoWAnalyzer#1912]
![image](https://user-images.githubusercontent.com/2842471/42801285-52f24fbc-899f-11e8-92f0-f2e0bd52f88a.png)
https://beta.wowdb.com/items/160651-vigilants-bloodshaper

**Comment by sMteX** [comment]
Was already implemented https://github.com/WoWAnalyzer/WoWAnalyzer/blob/master/src/parser/shared/modules/items/bfa/raids/uldir/VigilantsBloodshaper.js
