### ISSUE TITLE
Implement browser search

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1940]
Add "search" so you can type wowanalyzer in the omnibar, hit TAB and then paste url to parse it

**Comment by MartijnHols** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=61144935)](https://www.bountysource.com/issues/61144935-implement-browser-search)

**Comment by abelito75** [comment]
This needs to be closed right?
