### ISSUE TITLE
Remove / Update artifact ability suggestions

### ISSUE THREAD

**Issue by emallson** [WoWAnalyzer/WoWAnalyzer#2006]
Notably Fire Mages and Havoc DHs are having their artifact ability show up as a suggestion when they haven't taken the relevant talent. Example:

- [x] [Fire](https://www.wowanalyzer.com/report/B28fkqv4hF3YZWCH/14-Mythic+Aggramar+-+Kill+(7:11)/15-Iitroxic)
- [x] [Havoc](https://www.wowanalyzer.com/report/B28fkqv4hF3YZWCH/14-Mythic+Aggramar+-+Kill+(7:11)/23-Archdh)

Looks like Havoc doesn't have the ability anymore period and also is lacking a maintainer, so I may hit that one myself.

**Comment by ronaldpereira** [comment]
Havoc is now updated :)
