### ISSUE TITLE
[Balance Druid] Implement Azerite traits

### ISSUE THREAD

**Issue by Gebuz** [WoWAnalyzer/WoWAnalyzer#2027]
https://github.com/WoWAnalyzer/WoWAnalyzer/wiki/%5BBFA%5D-Implementing-Azerite-Traits

#### Bonus damage
Check # of hits vs. number of possible hits on DS and Sunblaze, both should be 100%.
- [x] Dawning Sun: http://bfa.wowhead.com/spell=276153/dawning-sun
- [x] High Noon: http://bfa.wowhead.com/spell=279070/high-noon
#### Bonus damage and empowerment proc
- [x] Power of the Moon http://bfa.wowhead.com/spell=273389/power-of-the-moon
#### It's own spell
Check # of hits vs. number of possible hits. Might not be possible for LS due to being unable to determine source. Streaking Stars procs on any offensive cast (including Starfall, FoN, FoE, it simply targets the last target you cast a targeted spell on). Solar Wrath procs both on cast AND on hit, so you can weave spells in between.
- [ ] Lunar Shrapnel: http://bfa.wowhead.com/spell=278507/lunar-shrapnel
- [x] Streaking Stars: http://bfa.wowhead.com/spell=272871/streaking-stars
#### Int buff
Currently the buff does not show stacks, which means it would need to call a query to get the number of casts done by the target of the innervate. Poked a guy about it so hopefully it'll have stacks added soon.
- [ ] http://bfa.wowhead.com/spell=279642/lively-spirit

**Comment by abelito75** [comment]
I'll start working on this

**Comment by abelito75** [comment]
As of right now all that reminds in Lunar Shrapnel and Lively Spirit as Sunblaze was removed from the game. Lively spirits is already implemented for resto druid so one might be able to steal that code or generalize it for all specs

**Comment by Gebuz** [comment]
The lively spirit module only works when innervate is cast on the druid themselves, so sadly it wont work for balance. Logs currently doesn't show stacks of lively spirit, so it's a pita to implement (requires tracking of all spells cast by the target of innervate, which needs a massive whitelist of class skills that triggers it).
I remember asking blizz to show the stacks in the log back in uldir, but seeing as it's not fixed yet I wouldn't get my hopes up. I remember empowerment stacks being broken to not showing stacks during since shortly after legion release (ToV patch iirc), and it was only fixed with BFA. So chances are it wont be fixed until azerite traits are gone.

Atleast it's rarely used by balance anymore.

**Comment by Gebuz** [comment]
iirc it's only healing spells (and disc dps spells?), so for instance a moonfire (mana) or swipe (energy) doesn't give stacks. Might need to double check that though, it's been a while since I've used it so I'm honestly not sure about disc dps spells or other healer's dps spells with mana cost.
