### ISSUE TITLE
[Restoration Shaman] Azerite traits creating inaccuracies in the StatValues module

### ISSUE THREAD

**Issue by niseko** [WoWAnalyzer/WoWAnalyzer#2083]
Azerite traits that buff existing spells will give inaccurate stat value results. For Restoration Shaman, traits which are doing that are:
- https://bfa.wowhead.com/spell=272989/soothing-waters
- https://bfa.wowhead.com/spell=273597/ebb-and-flow

Since they buff the amount of healing the spell does, but that part isn't interacting with / coming from Intellect at all, it will wrongly attribute the traits healing to Intellect, while that part only scales with item level and secondaries.
The plan is to catch those heals if you have the relevant azerite traits, calculate the azerite part (tooltip + 40% + secondaries), "remove" that part and send the reduced heal through the StatValues module normally, while sending the azerite part through under a different spellId which doesn't have intellect scaling included.

https://bfa.wowhead.com/spell=272989/soothing-waters provides a small extra challenge as only the initial heal gets increased, not all healing events.
https://bfa.wowhead.com/spell=273597/ebb-and-flow is distance based, thus also needs special treatment on top.

This can also be used to get their value for #2009

**Comment by Pewtro** [comment]
Goodbye BFA, goodbye azerite.
