### ISSUE TITLE
StatTracker: Armor Specialization

### ISSUE THREAD

**Issue by niseko** [WoWAnalyzer/WoWAnalyzer#2085]
Buffs that get applied / removed which give a primary stat are increased by 5% by the Armor Specialization, which is included in the pull-stats, but currently not added for temporary buffs.

**Comment by MartijnHols** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=62010792)](https://www.bountysource.com/issues/62010792-stattracker-armor-specialization)
