### ISSUE TITLE
Azerite Traits with fixed damage/healing values

### ISSUE THREAD

**Issue by joshinat0r** [WoWAnalyzer/WoWAnalyzer#2088]
Some azerite traits deal a fixed amount of damage (like [Zealotry](https://www.wowhead.com/spell=278615/zealotry) for ret pallys), but only using the value from our azerite-calculation might lead to wrong numbers. 
All % damage modifiers on targets and player would cause numbers that are off, ~~which means we need a module that will keep track of those buffs and debuffs.~~

Things that the module should account for:
- multipliers on player
- multipliers on bosses
- armor if the damage type of the trait is physical (would also need to account for shifting K-values of bosses)
- versatility

Tracking other buffs might be more difficult, such as the raid wide target debuffs applied by monks and demon hunters as we dont have them in the events. The same thing applies to healers and target specific % healing modifiers (like Vampiric Blood).

**EDIT**
As Gebuz mentioned, a proper solution to account for untrackable buffs (untrackable as in we don't want to make new API calls) is to calculate the expected damage of the spell. Check [this](https://github.com/WoWAnalyzer/WoWAnalyzer/issues/2088#issuecomment-414596614) comment on how we would calculate the expected hit size.

**Comment by Gebuz** [comment]
What we could do is calculate the expected hit size and then multiply that based on the actual hit. For instance, let's say I have a trait that adds X dmg to Solar Wrath. I cast Solar Wrath, and calculate that it should hit for Y dmg. If the hit matches that and also hits for Y I can simply contribute the damage the trait added to that. If it hits for more or less, let's call it Z, I just get the multiplier (Z/Y) and multiply the trait damage by that. 
```this.totalDamage += traitBonusDamage * actualDamage / expectedDamage```

**Comment by HawkCorrigan** [comment]
I started doing such a thing (damageModifyTracker) a while back and the general complaint was that it would generate more api calls.
IF I understood it correctly you would need an additional api call per enemy to get debuffs on them.

**Comment by joshinat0r** [comment]
I think getting the expected hit size right is a lot of work. It would be important to have all stats right, as in: keep track of mastery for tanks (to increase AP), all primary stat proc's from trinkets and azerite traits and spec specific stuff (like Shaman's mastery if affected). That's quite some work.

And yeah, making new API calls would give us the events we need to track them, but I think we might get issues with the API-limit, especially with BfA launch.

**Comment by Gebuz** [comment]
You would likely need to track stats correctly since the dmg bonus from azerite traits is still affected by vers, mastery and crit (where it applies that is). The only stat that doesn't increase the damage is INT/STR/AGI.
`effectiveTraitDamage = (spellPower * spellPowerCoef + traitBonusDamage) * vers * mastery * ..etc `

**Comment by joshinat0r** [comment]
I know that primaries don't increase the damage from the trait, but we need to track primaries to get the base damage of the spell right.
`this.totalDamage += traitBonusDamage * actualDamage / expectedDamage`
And `expectedDamage` needs to have primaries to calculate AP, right?.

Crit shouldn't be much of an issue, the `hitType` in the event object has one for crit hits iirc.
And I doubt that we'll have the StatTracker on Uldir launch filled with all stat procs.

**Comment by Gebuz** [comment]
Yes, you need to track all stats correctly, but my point is you'll need to track everything except primary stats correctly anyway, even if you find another way to deal with dmg modifiers on the player/target. So we are basically looking at making a complete whitelist of all dmg mods in the game vs. making the stattracker accurately track primary stats so we can calculate expected damage correctly. On top of that, as you mentioned we wont be able to get healing modifiers on the target because we don't want to make any extra API calls, so the whitelist wouldn't work for healing anyway. Besides, we'll want the statTracker to be as accurate as possible anyway.

**Comment by joshinat0r** [comment]
Thought I'd give it a shot starting such a module and already found the next issue 😅 

The formula for damage is:
`(Attack Power + Weapon DPS * 6) * AP Coefficient * Damage Multiplier`

- Attack Power is simply str or int
- The AP Coefficient could be added to `Abilities.js`
- Damage multipliers would need to include the spec's aura, if a spell scales with mastery (eg. shadow damage for Unholy DKs done via abilities, AP increases from mastery for tanks) and then damage multipliers from other buffs and debuffs.

But the "real issue" is weapon DPS (casters don't have WDPS since they have a good amount of int on their weapons instead). We don't get info's about the WDPS in the combatant-infos, means we'd have to get them from somewhere else. 

- I checked how the WoW-Armory displays those items, but they have the data for the tooltips already in the DOM, so its probably already done server-side.

- Already checked the Bnet-API but their items endpoint doesn't allow bonusIDs.
[This weapon](https://eu.api.battle.net/wow/item/163119?locale=en_GB&apikey=n6q3eyvqh2v4gz8t893mjjgxsf9kjdgz) should be iLvl 360, but the API returns an item with iLvl 865 and useless WDPS infos. The response also doesn't include some value that shows the scaling, there is maybe some kind of fixed scaling on WDPS (like there is for primaries or secondaries).

- The only alternative afaik would be wowheads XML API, which returns [this](https://www.wowhead.com/item=163119?xml&bonus=1492:4786) for the weapon. But I get some misleading values from there, the iLvl is displayed as 370 in the XML and as 350 in the JSON-data, while the reported iLvl from WCL is 360. The tooltip we display in the character-pane (from WoWDB) and WCLS (from wowhead) shows the WDPS for the 370 version. WoWDB and wowhead show at least for this weapon with the same bonusIDs the same WDPs.  **Long story short**: I'm not sure about how accurate the data is.

**Comment by Gebuz** [comment]
I remember talking about weapon DPS and AP here: #2068. According to this it should be possible to just get the AP from the cast event and that should include weapon DPS already.

For AP/SP coefs wouldn't it be easier to just add them as constants in the extending module than having to add them to Abilities.js?

```
const SUNFIRE_COEF = 0.35;
const BALANCE_SPEC_DMG_AURA = -0.18; // Should probably import this from './constants.js'. 
// Or maybe we should add spec auras to game/SPECS.js?

class HighNoon extends AzeriteTraitDPS {

  get formular() {
    return function(spellPower, attackPower, vers, mastery, crit) {
      return SP * SUNFIRE_COEF * (1 + BALANCE_SPEC_DMG_AURA) * (1 + vers) * (1 + mastery);
    }
  }
}
```

**Comment by joshinat0r** [comment]
I didn't knew that the cast event had a `attackPower`-prop, that makes things a lot easier.
Appears like Commanding Shout (+10% AP) and mastery for tanks are already included, will do this evening some testing if I'm able to get matching numbers with live. PTR/beta logs might have older modifiers.

Already asked in WCLs discord if its possible to get the AP/SP in the damage-events (its currently always "0"), would make it easier to calculate damage from DoTs since they have no cast event (would have to track the last cast to get a more or less accurate number).

Not sure about the AP coef / spec aura, I think it makes more sense if its in the spellbook. It's already the config for spells.
Adding the spec-modifier to `SPECS.js` might work, we just have to save them as object, eg. [Blood](https://www.wowhead.com/spell=137008/blood-death-knight) has two different modifiers and I'm pretty sure there are specs that have even more. But I personally would prefer to have them in the spellbook for each spell aswell, but I don't really care too much where its stored.

**Comment by Gebuz** [comment]
I forgot about different abilities having different auras, probably better to not add them to SPECS.js then. Spellbook is fine, especially if you think it's likely they will be used by other modules at some point. After giving it a bit of though I think they might be needed in the statvalues module healers use #2083.

About the AP from the events, just remember that most non dot abilities snapshots on cast, in which case using the AP from the cast would be correct. For dots, using the most recent cast's AP value should be good enough most of the time if it is not possible to get it with the damage event.

**Comment by Dambroda** [comment]
I agree, the only downside is having to track the coefficients. But even compared to what I did for whiteout, that still requires you to keep spelldata up to date (the spec aura). The only advantage to calculating the damage directly would be if the damage does not scale with all effects that affect the spells base damage, because then you enable or disable them one by one. In the case of Whiteout I believe it does get affected by all of those things, so I'll be modifying it once we agree on how we want to track coefficients.

**Comment by sMteX** [comment]
In #2744, the method used by Anatta and Putro in Feeding Frenzy module is refactored into an importable helper method in `parser/core/calculateBonusAzeriteDamage.js`.

**Comment by Pewtro** [comment]
Goodbye BFA, Goodbye Azerite.
