### ISSUE TITLE
Clicking the header logo on error screen does nothing

### ISSUE THREAD

**Issue by oBusk** [WoWAnalyzer/WoWAnalyzer#2129]
When getting the error reported at #2128, I tried to click the header logo to go "home" back to the start page. The URL is changed, but nothing happens. The `< Back` button works as expected.

So when being at a page with an error, like https://wowanalyzer.com/report/notARealReport or https://wowanalyzer.com/report/DXmVJKzL7RaB1Mw3 you can't click the header logo to go to start page.

**Comment by MartijnHols** [comment]
Thanks for the report, this will be fixed once I finish my work on #2202

**Comment by MartijnHols** [comment]
Since #2202 was merged, this should be fixed
