### ISSUE TITLE
Proper pets handling & enemies refactor

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#213]
We have combatants and enemies modules, but are still missing a pets module. This is becoming increasingly important with pet-reliant specs being added. 

Meanwhile the enemies module (and to a lesser extent combatants) are kinda messy. They need a refactor.

**Comment by shighman** [comment]
I started on the pets one based on enemies, i am working on some BrM stuff right now unless someone has done it by then i will revisit that.
