### ISSUE TITLE
Show a "Degraded experience" toaster when a module is disabled due to an error

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2174]

**Comment by MartijnHols** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=63291570)](https://www.bountysource.com/issues/63291570-show-a-degraded-experience-toaster-when-a-module-is-disabled-due-to-an-error)

**Comment by MartijnHols** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=63291570)](https://www.bountysource.com/issues/63291570-show-a-degraded-experience-toaster-when-a-module-is-disabled-due-to-an-error)

**Comment by MartijnHols** [comment]
Would be nice to have this in the `next` branch.

**Comment by MartijnHols** [comment]
Updated to $100: [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=63291570)](https://www.bountysource.com/issues/63291570-show-a-degraded-experience-toaster-when-a-module-is-disabled-due-to-an-error)

**Comment by buimichael** [comment]
@MartijnHols Could you explain in detail how this should be done? What should be the trigger of the toaster? Should it be generally per spec or module? 

What do you have in mind?

**Comment by MartijnHols** [comment]
The parser has error handling so that if a module has an error it gets caught silently and the module and all modules that depend on it get disabled. If this happens for anything I’d like there to be a single small info box on the page that explains the degraded experience and perhaps shows a list of disabled modules (since this could be lengthy this should probably be hidden behind a click).

**Comment by Zeboot** [comment]
@buimichael are you working on this one? If not I'll throw something together but if you're already working on it / gonna do it no worries

**Comment by buimichael** [comment]
@zeboot nope, go ahead :)

**Comment by Remixt** [comment]
I'm working on this right now, but I'm new to the project.

**Comment by Sharrq** [comment]
There is already an open PR for this, so i wouldnt start anything. Likely to be closed shortly.

**Comment by MartijnHols** [comment]
This has been implemented
