### ISSUE TITLE
Trinket: T'zane's Barkspines

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2175]
https://www.wowhead.com/item=161411/tzanes-barkspines&bonus=4798:1477

![image](https://user-images.githubusercontent.com/4565223/45387001-13597b80-b615-11e8-8a22-be5a673bdd46.png)

http://localhost:3000/report/zxXDd7CJFbLQpHGM/12-Mythic+Zek'voz+-+Wipe+11+(2:02)/3-Oof

**Comment by MartijnHols** [comment]
Has already been added to the StatTracker, those buff/item ids should be replaced with their respective objects once added.

Interesting stats is probably average crit gained. Uptime could be in tooltip. Should be added to the Abilities config too, so cast efficiency is checked.

**Comment by abelito75** [comment]
Are these trinkets still needed?
