### ISSUE TITLE
Just a small suggestion about Frost Mages

### ISSUE THREAD

**Issue by XDRage** [WoWAnalyzer/WoWAnalyzer#2184]
The Frost Mage proc efficiency tab doesn't take into consideration that you can cast Comet Storm into Winter's Chill (it has a slight lag before damage comes so the shatter bonus affects most of it, definitely does more damage than simple Frostbolt into Winter's Chill). Just a suggestion though :) Maybe I'm wrong and it's an overall dps loss but it doesn't feel like it at least.

**Comment by Sharrq** [comment]
I talked to the theorycrafters in the Mage Discord about this and they confirmed that it is an extremelly small increase (like less than half a percent) and is heavily influenced by distance to target and haste, so it would be bad advice overall to ask people to do this.

So I am not going to be adding this. Thanks for the suggestion though!
