### ISSUE TITLE
[Havoc] Recommends using Fel Rush rotationally even if not speced into Momentum

### ISSUE THREAD

**Issue by kaedys** [WoWAnalyzer/WoWAnalyzer#2188]
Fel Rush is only used rotationally of you're speced into Momentum.  For other talent builds, it is a DPS loss to use Fel Rush for damage, and thus its time on cooldown should not be noted as an issue unless speced into Momentum.

**Comment by Pewtro** [comment]
Thanks for the report! 

Havoc doesn't have an active maintainer at the moment, so it might be some time before this is changed along with anything else needing updating. If you want to, you should give it a shot in adjusting it yourself

**Comment by Pewtro** [comment]
Fixed with #2190
