### ISSUE TITLE
Add an analyzer for Deadly Navigation average crit

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2197]
https://www.wowhead.com/spell=268907/weapon-enchant-deadly-navigation#used-by-item

Permanently enchant a weapon to sometimes increase Critical Strike by 50 for 30 sec, stacking up to 5 times. Upon reaching 5 stacks, all stacks are consumed to grant you 600 Critical Strike for 10 sec.

Average crit + uptime in the tooltip

**Comment by Juko8** [comment]
This was added in #2355
