### ISSUE TITLE
Add an analyzer for Quick Navigation average haste

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2198]
https://www.wowhead.com/spell=268894/weapon-enchant-quick-navigation

Permanently enchant a weapon to sometimes increase Haste by 50 for 30 sec, stacking up to 5 times. Upon reaching 5 stacks, all stacks are consumed to grant you 600 Haste for 10 sec.

- Average haste + uptime in the tooltip
- Add haste buffs to stat tracker

**Comment by Pewtro** [comment]
This PR had it in if anyone needs inspiration: https://github.com/WoWAnalyzer/WoWAnalyzer/pull/2121

It ended up being combined with a lot of other things, and it wasn't really that pretty code-wise (nor visually as it was lumped in with items, when in reality it should probably be under normal statistics)

**Comment by MartijnHols** [comment]
I think I'd expect to find it in items when analyzing a log; it's part of an item, not a base spell or anything

**Comment by 5chmidt** [comment]
I think this has been merged into master.
![image](https://user-images.githubusercontent.com/3276248/57988611-5b5f5680-7a5e-11e9-8fd6-af6099376ce9.png)
Can this item be closed?
