### ISSUE TITLE
Holy Paladin: Azerite Trait: Grace of the Justicar

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2199]
Since it beacon transfers it's not as simple as WCL's indicator

**Comment by 5chmidt** [comment]
I can start working on this item.
Here is an example log with the trait equipped:
https://www.warcraftlogs.com/reports/9Gh6XMafg7TCFdpj#fight=4&type=healing&source=7&ability=278785&view=events
