### ISSUE TITLE
Holy Paladin: Azerite Trait: Radiant Incandescence

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2200]
Since it beacon transfers it's not as simple as WCL's indicator

**Comment by 5chmidt** [comment]
I will start working on this item.  After my trials and tribulations last week with beacon transferring, hopefully this will go more smoothly.
Here is a log that features the trait:
https://www.warcraftlogs.com/reports/vGfw7dYhM1m6n3J4#fight=8&type=healing&source=13&ability=278147&view=events

**Comment by 5chmidt** [comment]
I think this issue is good to close.
