### ISSUE TITLE
Holy Paladin: Show Avenging Crusader total healing

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2201]
Since it beacon transfers it's not as obvious as WCL's value

**Comment by MartijnHols** [comment]
Also need to look into AC's interaction with stat weights since blizz's combat logging of it is funny, with it splitting crits into a separate spell and all

**Comment by MartijnHols** [comment]
and need to include it in _healing time_

**Comment by 5chmidt** [comment]
I can start working on this item.  I think I know how to handle the beacon transfer part and the total healing value.  I'm not sure where the 'healing time' statistic or where I should tie in with stat weights.  Any advice would be greatly appreciated.

Here is a log that will work for testing:
https://www.warcraftlogs.com/reports/fLmqF8W6Vh1d4GJv#fight=12&type=healing&source=7&view=events&sourcebuffs=216331

**Comment by MartijnHols** [comment]
Healing time is used for the active time display, I think currently it doesn't consider CS/J casts as healing time

**Comment by 5chmidt** [comment]
I looked into the healing time file in: 'src/parser/paladin/holy/modules/AlwaysBeCasting.js'
It does not seem to be functioning correctly.  

Here is the log I was testing with: [log link](https://www.warcraftlogs.com/reports/fLmqF8W6Vh1d4GJv#fight=12&type=healing&source=7&view=events&sourcebuffs=216331)

This log uses Judgement of Light talent.  When I cloned master I got a percent healing time of: -49.8% time spent healing (>70.00% is recommended)
This matches the healing time on the live version.

When I comment out:
`    if (this.selectedCombatant.hasTalent(SPELLS.JUDGMENT_OF_LIGHT_TALENT.id)) {
      this.constructor.HEALING_ABILITIES_ON_GCD.push(SPELLS.JUDGMENT_CAST.id);
    }`

Which should be pushing Judgement to count as healing time, it does not count as healing time.
The healing time is still -49.8%.

I looked at other healing specs to see how other people are implementing this, but they all are just using a static list of spell ids.

**Comment by 5chmidt** [comment]
When I added:
`SPELLS.JUDGMENT_CAST_HOLY.id,`
to the static list of healing spells I got the following result:
-41.18% time spent healing (>70.00% is recommended)

It shows that I am spending less time healing after added my judgement casts to the list.
Am I missing something obvious here?

**Comment by MartijnHols** [comment]
The suggestion might have broken when I inverted the statistic from downtime to active time. Will have to investigate.

**Comment by 5chmidt** [comment]
This can be closed, I forgot to point to it in PR #3142.
