### ISSUE TITLE
UHDK abilities and legion leftovers

### ISSUE THREAD

**Issue by edyrmUH** [WoWAnalyzer/WoWAnalyzer#2226]
![aewfaegae](https://user-images.githubusercontent.com/43398090/45731493-292aeb80-bb95-11e8-8137-18cdfe52da67.png)

some fights like fetid tell you to use AoE abilities on an entirely single target fight. And as you see at the top it still mentions the cold heart legendary on chains of ice.

**Comment by Pewtro** [comment]
This has since been fixed.
