### ISSUE TITLE
[Havoc Demon Hunter] Azerite Traits

### ISSUE THREAD

**Issue by joshinat0r** [WoWAnalyzer/WoWAnalyzer#2246]
Havoc Demon Hunter specific azerite traits

- [ ] Burning Soul
- [ ] Eyes of Rage
- [ ] Furious Gaze
- [ ] Infernal Armor
- [ ] Revolving Blades
- [ ] Seething Power
- [ ] Soulmonger
- [x] Thirsting Blades
- [ ] Unbound Chaos

**Comment by torothin** [comment]
After looking into this issue I have found that the following traits are done:
Eyes of Rage
Furious Gaze
Revolving Blades

**Comment by torothin** [comment]
Thirsting Blades is being worked on.
