### ISSUE TITLE
[Vengeance Demon Hunter] Azerite Traits

### ISSUE THREAD

**Issue by joshinat0r** [WoWAnalyzer/WoWAnalyzer#2247]
Vengeance Demon Hunter specific azerite traits

- [ ] Burning Soul
- [ ] Cycle of Binding
- [ ] Essence Sever
- [ ] Gaping Maw
- [ ] Infernal Armor
- [ ] Revel in Pain
- [ ] Rigid Carapace
- [ ] Soulmonger

**Comment by torothin** [comment]
Going to work Infernal Armor first then Revel in pain based on the popularity of those two traits.
