### ISSUE TITLE
[Priest] Bug in Discipline Normalizer(s)

### ISSUE THREAD

**Issue by Gebuz** [WoWAnalyzer/WoWAnalyzer#2278]
Looks like `AtonementSuccessiveDamage.js` incorrectly thinks dmg sources that does not proc atonement should proc it:
![image](https://user-images.githubusercontent.com/6773230/46005376-6b808b00-c0b5-11e8-9097-d9456c14802c.png)
It also looks like it thinks damage events onto the priest should be considered?
![image](https://user-images.githubusercontent.com/6773230/46006335-8c49e000-c0b7-11e8-9d71-6e212da7c48e.png)
![image](https://user-images.githubusercontent.com/6773230/46006348-953ab180-c0b7-11e8-9faf-4508acc0b855.png)
![image](https://user-images.githubusercontent.com/6773230/46005305-425ffa80-c0b5-11e8-8330-feb5ddc4672e.png)

There is also some other bugs which I have no idea what is caused by:
![image](https://user-images.githubusercontent.com/6773230/46005190-0331a980-c0b5-11e8-95a5-2a4f2bf92d8a.png)
![image](https://user-images.githubusercontent.com/6773230/46005221-10e72f00-c0b5-11e8-9002-4d7a034ed431.png)
![image](https://user-images.githubusercontent.com/6773230/46005287-37a56580-c0b5-11e8-8692-ce9a7616acf3.png)

log: https://wowanalyzer.com/report/H3gch7BX6pb1Wmyx/48-Mythic+Fetid+Devourer+-+Wipe+42+(5:46)/12-Nalan%C3%AD/events

**Comment by DylanDirlam** [comment]
#2473 Fixes this issue and can be closed
