### ISSUE TITLE
monk syntax error 

### ISSUE THREAD

**Issue by macCormack** [WoWAnalyzer/WoWAnalyzer#2301]
Ran across a syntax error while trying to view the statistics at this link [https://wowanalyzer.com/report/YQRAP1hv6NZG9ax7/5-Heroic+Fetid+Devourer+-+Kill+(3:11)/14-Fiisting](https://wowanalyzer.com/report/YQRAP1hv6NZG9ax7/5-Heroic+Fetid+Devourer+-+Kill+(3:11)/14-Fiisting)
the error message was 
`SyntaxError: Unexpected end of JSON input
    at https://wowanalyzer.com/static/js/Monk.98c764e1.chunk.js:1:524460`

**Comment by Pewtro** [comment]
Can you link the log?

**Comment by macCormack** [comment]
Just linked sorry.

**Comment by Pewtro** [comment]
It works now - it's simply the bnet api breaking, nothing we can fix sadly.
