### ISSUE TITLE
You died suggestion: add a link to the death recap

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2307]
I point users to *the death recap below*, but it should really be a link as that's much easier to follow.

![image](https://user-images.githubusercontent.com/4565223/46255241-1ec4f780-c49b-11e8-8b4c-b12c060175bc.png)

**Comment by yishengjiang99** [comment]
Taking a crack at this, should I use the makeAnalyzerUrl() function? 
Also what's the best way to access the report variable from inside of an Analyzer component?

**Comment by MartijnHols** [comment]
Yeah `makeAnalyzerUrl` would probably be needed, but an important this would be to jump down the page to the panel, so perhaps we need a hash link to jump to the details?

You could access the report from an Analyzer via `this.owner.report`.

**Comment by darthelit** [comment]
Is this still WIP? I was going to try my hand at this and get acquainted with the codebase.

**Comment by MartijnHols** [comment]
@yishengjiang99
