### ISSUE TITLE
[User Experience] Mobile Safari view is formatted poorly. 

### ISSUE THREAD

**Issue by emptyrivers** [WoWAnalyzer/WoWAnalyzer#234]
Note the text flies out of the bounding box: https://cdn.discordapp.com/attachments/155805795085189120/353617181931732992/image.png

I understand this could easily be rated low-priority, but given that you have a mobile view at all, this is quite bad UX.

**Comment by MartijnHols** [comment]
Thanks for the report. I'm open to ideas on how to fix this.

**Comment by MartijnHols** [comment]
Hey we recently changed the layout of the tabs so that there should be enough space to show all the data. I think our mobile view is actually pretty good right now. Please let us know if you're still experiencing issues.
