### ISSUE TITLE
Quick Navigation Timings are wrong

### ISSUE THREAD

**Issue by Gamewalker** [WoWAnalyzer/WoWAnalyzer#2351]
Quick Navigation sets the stack size and stack buff uptime to a 0 stack if the "removebuff" event QUICK_NAVIGATION_BUFF_SMALLis triggered. If the buff runs out before it gets up to 5 Stacks, its working like intended but if the buff reaches 4 Stacks and receives another stack, there is no applybuff event anymore. The Stack count is set to 0 and the QUICK_NAVIGATION_BUFF_SMALLis applied. Here we set the uptime to 0 instead of 5 and get a total uptime of SUM(0:MAX_STACK) + MAX_STACK

STACK ++small buff
STACK ++small buff
STACK ++small buff
STACK ++small buff
STACK small buff = 0; ++big buff 

Dont know how to fdix it the right way, dirty workaround could be the substration of MAX_STACK buff runtime of 0 stack buff runtime.

Sorry for my bad english, I can help to understand it better if needed in discord: Gamewalker#1367

**Comment by Gamewalker** [comment]
<img width="505" alt="quick" src="https://user-images.githubusercontent.com/241821/46351557-f20a0f00-c657-11e8-896b-352c16095c59.PNG">

screenshot for better understanding.
0 should be 3:05 - 1:39

**Comment by Pewtro** [comment]
![image](https://user-images.githubusercontent.com/29204244/46351861-b4f24c80-c658-11e8-9bd2-3f0f94e2ef1e.png)
You like this better?

**Comment by Pewtro** [comment]
See #2352 , which will fix this issue.

**Comment by Gamewalker** [comment]
I think this is the simplest solution and for the purpose ok, not the prettiest
