### ISSUE TITLE
[Druid] Be well prepared checklist missing

### ISSUE THREAD

**Issue by ssscassio** [WoWAnalyzer/WoWAnalyzer#2392]
Must add **Flask used** and **Food used** to _Be well prepared_ checklist for druid on all specs.
Maybe **All items enchanted** and **Using high quality enchants** too.

**Comment by Pewtro** [comment]
This is due to the druids not being updated to the new checklist format, once they're updated to the checklist2 format, it'll automatically be added and functional.
