### ISSUE TITLE
Add support for Assassination Rogue

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2411]
Since I do not know Assassination Rogue, I can not specify a definition of done. If you think it's ready to be marked as supported, you'll have to somehow convince us of this as well.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=64450029)](https://www.bountysource.com/issues/64450029-add-support-for-assassination-rogue)

**Comment by yishengjiang99** [comment]
I disagree with capping combo points from toxic blade. I think you should use toxic blade at 4 or 5 combo points.

**Comment by Gebuz** [comment]
I've started working on Assassination rogue, if anybody else is/was planning to do this, feel free to hit me up on discord (Gebuz##5801) so we don't overlap.

**Comment by tmshneeki** [comment]
> I disagree with capping combo points from toxic blade. I think you should use toxic blade at 4 or 5 combo points.

This is incorrect information.  You should never overcap combo points.  The only situation where you would use toxic blades at 5 combo points would be if you were running Deeper Stratagem talent which is a no go for assassination.

**Comment by MartijnHols** [comment]
Hey! This spec has been marked as supported, does that mean this issue can be closed? By closing it the bounty can be claimed on BountySource.

**Comment by Gebuz** [comment]
I should've closed it when I marked it as complete back in December. I haven't touched my rogue since bod, but afaik the basics should still be correct. I don't really wanna take the money, so if you wanna keep it open for further Dev on assa or move them to another bounty or something else that'd be cool by me.

**Comment by tyndivelspaz** [comment]
Working on this as part of #3743 
I'll make sure these points are addressed in it as well.
