### ISSUE TITLE
[Arcane Mage] Rethink/Redo AP Pre Req Checks

### ISSUE THREAD

**Issue by Sharrq** [WoWAnalyzer/WoWAnalyzer#2425]
Got some feedback from the Mage Discord, the Arcane Power Module checks to make sure you meet the following pre-reqs before you cast Arcane Power.

- You had 4 Arcane Charges
- You had more than 40% Mana (unless you have the Overpowered Talent)
- You cast Rune of Power immediately before AP (if you have RoP talented)

The problem, is it only tells you that you cast AP without meeting the pre reqs x times ... it doesnt say WHICH pre-reqs you failed on. 

Additionally, got some feedback that a 50% utilization score for missing one pre req out of 2 casts is a bit harsh. Might count pre reqs separately so its like 5/6 for failing one prereq as opposed to 1/2 for failing one cast ... though would need to adjust the % based on the number of pre-reqs actually checked. i.e. if you have OP and not RoP then you are only checking 1 thing, if you have OP and RoP you are checking 2 things, and if you dont have OP and have RoP you are checking 3.

Finally, should take another look at the acceptable delay on RoP. It is set at 200ms because the thought is that AP lasts 10 seconds, RoP lasts 10 seconds ... they should be cast at the same time always. But one player did RoP > Potion > AP and it dinged him for it cause there was an 800ms delay. Ill have to talk to the Mage Discord to find out if a strict delay is warranted or if it should be loosened up a bit.

**Comment by Sharrq** [comment]
Talked to the Theorycrafters in the Mage Discord ... Using Potion in between RoP and AP is a mistake, but apparently macro'ing your trinkets (like Balefire) with AP is a very very slight DPS loss (somewhere around 0.5%), I will do a little more research for that to see what the delay is if you macro a trinket in there as I dont recall whether on use trinkets are on the GCD or not.

**Comment by Dambroda** [comment]
I agree that they should be checked differently, but I would consider weighting the mistakes by how bad they messed up. For example, I wouldn't consider having 39% mana instead of 40% the same level of mistake as not casting RoP beforehand. In fact I may change that mana requirement completely, due to mastery. Instead of checking their mana % when casting AP, check to see if during AP they ever had to stop casting AB due to mana issues. Maybe their mastery is so high that they can actually start AP at 30% and not run OOM. So instead of checking their actions against the guidelines, we can check to see if they actually made a mistake. Doing this might even fix another potential issue when calculating haste. If you're going to have a big haste buff, you get more AB casts off during AP meaning you needed more mana to begin with.

**Comment by Sharrq** [comment]
Sure i could weigh the mana % based on how far below 40 they were ... but that is a whole level of granularity that i dont want to get into. I really dont want to get so incredibly detailed that im checking if they were under 40, if they were between 35 and 40, if they were between 30 and 35, if they were under 30, etc.

The analyzer already looks at whether they went OOM during AP. Its not 100% accurate, but it takes a best guess and the wording of the suggestion even indicates that you "might have" gone OOM during AP, based on how much mana they had remaining and how expensive the next cast would be (since i cant get their mana level outside of a cast event and I cant see that they are trying to cast but cant).

The 40% threshold is in all of the guides and therefore is the number that i used. I wanted it to be consistent with the guides.

**Comment by Dambroda** [comment]
Fair enough. Which guides are you using to determine what the %'s should be though? Altered-time and IV say 50 or 30(OP)

**Comment by Sharrq** [comment]
Hmm, maybe they updated it. Ill have to dig through my DMs but im pretty sure Dutchmagoz said 40% was right previously.

**Comment by Sharrq** [comment]
![image](https://user-images.githubusercontent.com/1304554/46841303-a3155580-cd8c-11e8-94ca-05a7f4035914.png)

**Comment by Dambroda** [comment]
Thats pretty much right when the xpac came out, so ima guess it's just been updated since then; it would be weird to make a suggestion that contradicts what all the guides say

**Comment by Sharrq** [comment]
He also spent a good amount of time telling me it doesnt matter where you conserve as long as you dont go oom during ap, so the 40% is mostly guestimate afaik
