### ISSUE TITLE
SyntaxError: expected expression, got '<' on multiple logs for my shaman

### ISSUE THREAD

**Issue by BrocoliCosmique** [WoWAnalyzer/WoWAnalyzer#2433]
Hello,

Since last week I can't view my character (Ypp-Uldaman) on any of my reports through wowanalyzer.

Examples for each spec : 
Elemental : https://wowanalyzer.com/report/jrkmVDngTqa83yLw/1-+Le+Filon+-+Kill+(34:42)/3-Ypp
Enhancement : https://wowanalyzer.com/report/AJrGqLFjHhkamYgz/1-+Le+Filon+-+Kill+(49:21)/5-Ypp
Restoration : https://wowanalyzer.com/report/Pvzw49gmDnHhXaAM/2-+Port-Libert%C3%A9+-+Kill+(21:22)/5-Ypp 

These reports work fine for every other player involved, so it may be something related to my gear ?

Best regards and thanks for this tool !

**Comment by joshinat0r** [comment]
You already tied incognito mode in your broswer? These reports all work for me, so it sound to me like some cache issue. Try incognite or force-reload the page (CTRL + F5).
If thats still happening, check your addons. Some of them cause issues with our app when a specific bundle gets blocked by that addon.

**Comment by BrocoliCosmique** [comment]
I'm getting the same error from 2 browsers but not on my phone which is not on the same network.
So it looks like it is indeed a networking issue.
Thanks for the heads up !
