### ISSUE TITLE
[Hunter] 8.1 Azerite traits

### ISSUE THREAD

**Issue by Pewtro** [WoWAnalyzer/WoWAnalyzer#2533]
## Beast Mastery
- [x] Dire Consequences: https://ptr.wowhead.com/spell=287097/dire-consequences
## Marksmanship
- [x] Surging Shots: https://ptr.wowhead.com/spell=287707/surging-shots
## Survival
- [x] Primeval Intuition: https://ptr.wowhead.com/spell=288573/primeval-intuition
## General
- [ ] Nature's Salve: https://ptr.wowhead.com/spell=287940/natures-salve

**Comment by leozhekov** [comment]
Primeval intuition has been added with PR [#3217](https://github.com/WoWAnalyzer/WoWAnalyzer/pull/3217)

**Comment by Juko8** [comment]
Dire Consequences merged with #3328

**Comment by Pewtro** [comment]
Don't think Nature's Salve is that interesting to implement, at least not at the moment.
