### ISSUE TITLE
Remove/Replace `Use your defensive cooldowns.` checklist rule for Prot Paladins

### ISSUE THREAD

**Issue by emallson** [WoWAnalyzer/WoWAnalyzer#2544]
The checklist rule is more misleading than useful. It is generally unwise to be using your defensive CDs (close to) on cooldown because then you won't have them when you need them.

**Comment by Gebuz** [comment]
Wouldn't it be better to just lower the thresholds? Not casting them at all, especially short cooldowns like divine protection, should be a major issue?

**Comment by emallson** [comment]
I think Ardent Defender might continue to make sense with a low (<50%) cast efficiency, but the others are either too long of a CD or too situational.

For reference, GoAK is a 5m CD. BrM has Fort Brew which plays a similar role at a ~4m CD, and I don't check that one because if you don't save it for oshit moments you have nothing.
