### ISSUE TITLE
Soft Mitigation Checks -- Void Lash?

### ISSUE THREAD

**Issue by emallson** [WoWAnalyzer/WoWAnalyzer#2546]
More generally: what do we do about "tankbusters" for which some tanks don't have effective AM?

For example, BDK and BrM can mitigate void lash by death striking or using ISB, but Prot Paladins can't mitigate every one (afaik) and generally shouldn't, as the cooldowns are better used elsewhere.

**Comment by yajinni** [comment]
Shouldnt most tanks be able to spare atleast 1 cd per taunt rotation to mitigate SOME of the damage? Most can not mitigate the whole 3 hit combo. But atleast the first 2 or last 2 hits should have something to lessen the blow. Personally i would consider 2/3 hits mitigated in some fashion a successful check.

**Comment by emallson** [comment]
on mythic, i rotate an external CD from a healer with dampen harm on my monk. (the external doesn't count). on heroic i don't bother because it doesn't deal enough damage.

which i guess brings me to my concern: this is a soft **mitigation** check---against which most tanks don't have mitigation they can use outside of big CDs. On N/H it doesn't do enough damage that you need to use big CDs, and on mythic there are other solutions (like externals) that don't show up.

**Comment by yajinni** [comment]
For well geared or hardcore raiders yeah heroic you can probably get away without anything. But i think thats a smaller subset of people than your average casual person who SHOULD be popping a personal CD for that stuff. Those higher end people would on thier own know that they dont need to worry about it or know they are using an external for it. I feel like we should be trying to build good habits for people and if they want to ignore them for the sake of thier own strategy then so be it.

**Comment by joshinat0r** [comment]
I had a similar argument with Gebuz a few days ago when I added the immune-check to it. I also added parry & dodge to it, because it's to me just a statistic that's showing how the stuff hit me and if I had something up during it.
The soft-mit check isn't in the checklists and has no suggestion if you reach less than 100%, so I always took it as a "nice to know"-stat and not a "you need to have 100%"-suggestion.

But I do think that we should add externals to the module, and make the DR-effects more specific (like SotRing on Void Lash or using AMS on physical damage).

**Comment by emallson** [comment]
if we're making it more specific, isb really shouldn't count against magic damage (it does so little it's basically just an extra 25% hp). That then puts brm in an awkward spot because you actually can't mitigate 100% on your own.

idk, I'm of the opinion that a frequent magic nuke like void lash shouldn't be counted a mitigation check

**Comment by yajinni** [comment]
I suppose. Coming from a DK where i can have vampiric blood and antimagic shell for every rotation of it i can mitigate alot of it. Other tanks i guess might not be able to have something on the regular.

**Comment by emallson** [comment]
@hpabst's PR that splits tankbusters into phys/mag covers 99% of the problems with PR #2818. anyone that knows to call for externals also likely knows enough to judge the missed ones as having externals.

**Comment by emallson** [comment]
Or not, whoops. Missed that this doesn't split the `statistic()`. I'll get around to that someday
