### ISSUE TITLE
Opening an expandable statistic does not trigger a resize.

### ISSUE THREAD

**Issue by Streammz** [WoWAnalyzer/WoWAnalyzer#2564]
Currently, A react component Masonry is used to create a neat and more compact layout for the results view, however I've found out that if expandable statistic boxes are used, and you expand this box, the layout does not update, and components end up overlapping eachother.

As an example, here is a Beast Mastery statistic screen, with everything still unexpanded:
https://www.warcraftlogs.com/reports/XGd2Z9YmfQKBAMFb/#fight=12&source=104
![2018-1101_11-44-49](https://user-images.githubusercontent.com/626948/47847454-94d6ba00-ddcb-11e8-96f4-012518cd8af2.png)

If I now open the Bestial Wrath statistics, it increases the size of the statistic and ends up hiding the statistic right below it.
![image](https://user-images.githubusercontent.com/626948/47847491-b2a41f00-ddcb-11e8-8c73-90aea59924b1.png)

You can still feintly see the statistic behind it due to the transparency:
![image](https://user-images.githubusercontent.com/626948/47847511-c0f23b00-ddcb-11e8-827f-288c593aa604.png)

However, if I manually resize the window a tiny bit after opening it, it fixes itself:
![image](https://user-images.githubusercontent.com/626948/47847610-09a9f400-ddcc-11e8-8434-b56b8596222d.png)

While I think that it isn't necesserily something that will prevent the users from looking at the data they want to see, it should probably be changed.

**Comment by MartijnHols** [comment]
This is by design, the interface jumping around on expansion would feel off.
