### ISSUE TITLE
Move support for cast cooldowns into core module

### ISSUE THREAD

**Issue by sMteX** [WoWAnalyzer/WoWAnalyzer#2600]
In the spirit of keeping code repetition the least, we might try and move the logic for cast cooldowns (which I originally added for Warlocks and then it got copied into a few other places) back into the core module (if it doesn't interfere in any way). 

Affected specs: 
- Affliction Warlock (Summon Darkglare)
- Demonology Warlock (Nether Portal, Grimoire: Felguard, Summon Demonic Tyrant, maybe Summon Vilefiend)
- Destruction Warlock (Summon Infernal, Havoc)
- Windwalker Monk (Storm, Earth & Fire, Touch of Death)
- Arms Warrior (Warbreaker, Colossus Smash)
- Arcane, Frost, Fire Mage (Mirror Image)

**Comment by Gebuz** [comment]
Now also Arms (Warbreaker, Colossus Smash)

**Comment by Dambroda** [comment]
What logic is this referring to?

**Comment by Gebuz** [comment]
CooldownThoughtputTracker.js, all the specs listed implements static duration cds, when it should really be implemented once in the core version.

**Comment by Dambroda** [comment]
What is the difference is between things like Mirror Image vs Arcane Power that puts one in the core module and the other not? I still don't really understand what is meant by "implements" static duration cds, we do a lot more than track the CD of Mirror Image. What exactly would be moved?

**Comment by Gebuz** [comment]
https://github.com/WoWAnalyzer/WoWAnalyzer/blob/master/src/parser/mage/frost/modules/features/CooldownThroughputTracker.js
line 36 to 68 is duplicated across all those specs' CooldownThoughtputTracker.js, when it should be just implemented once in the core version instead.

**Comment by Dambroda** [comment]
Oh, so this is about *on_cast* cooldowns not being supported in the core module. That is a lot different than what the title and descriptions made it seem lol. In that case yeah I agree cast cooldown support should be core

**Comment by sMteX** [comment]
Yeah, the point was that initially, cooldown tracker was tracking *buffs* on player, whereas I wanted to have some of them tracked also on cast (which usually meant they don't place buffs or debuffs or anything). I'll try to rename the issue name to something more meaningful

**Comment by abelito75** [comment]
This sounds like it was completed a long while ago. Closing
