### ISSUE TITLE
[SPriest][BFA] Azerite Traits for Shadow

### ISSUE THREAD

**Issue by TJMoats** [WoWAnalyzer/WoWAnalyzer#2612]
- [x] Chorus of Insanity
- [x] Death Throes 
- [ ] Depth of the Shadows
- [ ] Searing Dialogue
- [ ] Spiteful Apparitions 
- [ ] Thought Harvester 
- [ ] Whispers of the Damned

**Comment by Pewtro** [comment]
Goodbye BFA, Goodbye Azerite.
