### ISSUE TITLE
[Outlaw] Azerite Traits

### ISSUE THREAD

**Issue by HawkCorrigan** [WoWAnalyzer/WoWAnalyzer#2654]
#### It's own damage source:
- [ ] Ace Up Your Sleeve

#### Increases damage of another ability:
- [ ] Snake Eyes (check ?buff? after RtB)
- [ ] Deadshot
- [ ] Storm Of Steel

#### Stat buffs:
- [ ] Brigand's Blitz
- [ ] Paradise Lost

**Comment by tmshneeki** [comment]
I've just PR'd the implementation of all Azerite Traits (split into spec specifics).  

Being new to all of this I would love to team up with someone to learn how to move on from simply having the traits added.

If someone's able to guide me through how to do it with one of them then I can happily do the others myself.  Grab me on Discord - Shneeki

**Comment by HawkCorrigan** [comment]
Hey I am just gonna put some links here.
I would suggest starting with Deadshot for example. It is "just" a flat damage bonus for an ability.
It should boil down to checking if the player has the corresponding buff and then just calling the bonusDamage function to get the actual value.
https://www.wowhead.com/spell=272935/deadshot

This is my implementation for a "similar" trait for Ele shaman.
https://github.com/WoWAnalyzer/WoWAnalyzer/blob/e5d5844fe1d5430054c70cc27e5932be5ab61233/src/parser/shaman/elemental/modules/azerite/LavaShock.js

If you wanna try it out yourself those should be enough to get a general idea on how to implement them. If you get stuck anywhere just ping me on discord or here.

**Comment by tmshneeki** [comment]
That's Deadshot done now if you want to put a big tick beside it.
