### ISSUE TITLE
[Hunter] Wrong death statistic

### ISSUE THREAD

**Issue by Pewtro** [WoWAnalyzer/WoWAnalyzer#2670]
Whenever a hunter uses feign death, it will incorrectly register as time spent dead - however there is no cast event for feign death. 

My idea is to lower timespent dead whenever the hunter is dead for less than 1second.

**Comment by HawkCorrigan** [comment]
Can you check for battle rezzes?
If so then you could just say "If he "dies" and dpses later in the fight without a brezz he prolly just feigned"

**Comment by Pewtro** [comment]
Oh yeah, that's a second idea. The module can detect if someone "magically" resurrects, so a safe bet if that happens very shortly after a death, it's a feign to dodge some mechanic - and then it can be detected that way.

**Comment by Gebuz** [comment]
iirc using a Soulstone doesn't trigger any events, so might be a good idea to check if the hunter had a Soulstone buff before "dying".

**Comment by Sharrq** [comment]
Looks like WCL has a thing to tell whether the death event was a feign death or not ... maybe you can use that somehow?

![image](https://user-images.githubusercontent.com/1304554/50783898-b80d6200-1271-11e9-8d8a-2a87a2c49d69.png)
