### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Marcarrian** [WoWAnalyzer/WoWAnalyzer#2682]
I have this log https://www.warcraftlogs.com/reports/pfVdXnQqJGTaZkmB 
Steps to reproduce:

1. Paste the posted log in https://wowanalyzer.com/
2. Select Normal Taloc (or any other boss fight)
3. Click on the Player Marcarrian (Frost)
4. The Error Cannot read property 'length' of undefined now occurs.

Clicking on any other player shows the expected result.

**Comment by niseko** [comment]
Thanks for the report, fixed my error with #2684 and the log should work now.
