### ISSUE TITLE
Add a way to precisely determine phases

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2706]
We need a way to determine boss phase start/end. Preferably down to the level of knowing when ad waves spawn within a phase (micro phases).

WCL fights endpoint does list phases, but not timings of them. Kihra mentioned possibly exposing this in the API but I wouldn't expect that any time soon without constant nagging. Alternatively we could try the Wipefest API but that adds latency, another point of failure and no guarantees. Long story short it would be nice if we can figure out a way to determine this ourselves. But then how to make this well maintainable?

We could do 1 extra API call to determine this but that would be troublesome for high traffic moments. We could gracefully downgrade to non-phase support then, but that might make usage of this much harder. Maybe the API call is worth it given the gain. Plus Kihra mentioned possibly adding support for "additional queries" support in the events API, which could help us reduce this back to 1 call when that arrives.

**Comment by kfinch** [comment]
For the extra API call issue, could add a "show phases" button and not make the call until user presses it.

**Comment by MartijnHols** [comment]
1 extra API call is acceptable. I do like that idea as phase selection will probably be behind a toggle anyway, but micro phases (which lets us know when adds are up) will be required before parsing.

**Comment by MartijnHols** [comment]
Fixed in #2923
