### ISSUE TITLE
Trinket: World Boss: Ancient Knot of Wisdom

### ISSUE THREAD

**Issue by niseko** [WoWAnalyzer/WoWAnalyzer#2824]
https://ptr.wowhead.com/item=166793/ancient-knot-of-wisdom&bonus=1502:5479

![image](https://user-images.githubusercontent.com/2842471/49835829-b64e9c80-fda0-11e8-9e98-5637e7c5338a.png)

**Comment by 5chmidt** [comment]
I can start working on this.  Here is the log a found to test with.
https://www.warcraftlogs.com/reports/t2ZK6pQvgLGqj7by#fight=1&source=13
