### ISSUE TITLE
Add Sea Giant's Tidestone haste to StatTracker

### ISSUE THREAD

**Issue by sMteX** [WoWAnalyzer/WoWAnalyzer#2833]
Seeing as it just dropped for me, we might add support for it.

https://www.wowhead.com/item=165664/sea-giants-tidestone

Also grants haste on use, which should be important to add to StatTracker.

**Comment by 5chmidt** [comment]
I can start working on this. 
Do you have any logs using it that I can test with?

**Comment by sMteX** [comment]
The arcane mage here - Bluemyself, seems to have it https://www.warcraftlogs.com/reports/ABH7D8W1Qaqv96mt#fight=2&type=summary&source=9

**Comment by 5chmidt** [comment]
Perfect, thanks.

**Comment by sMteX** [comment]
Fixed with #2861 and #2862
