### ISSUE TITLE
[BrM] Present Mitigation Value a la Teachings of the Red Crane sheet

### ISSUE THREAD

**Issue by emallson** [WoWAnalyzer/WoWAnalyzer#2880]
The [TotRC spreadsheet](https://www.peakofserenity.com/bfa/mistweaver/spreadsheet/) evaluates the performance of different traits and trinkets based on an actual log. I want to replicate that functionality for brewmasters in the analyzer. The goal here is to tell two things:

1. How much "effective healing" was provided by each stat, and how does that compare to the amount of stats from gear?
2. How much EHP was provided by each stat, and how does that compare to the amount of stats from gear?

where "effective healing" is either damage mitigated or healing done.

See [`feature/brm-sheet`](https://github.com/emallson/WoWAnalyzer/compare/master...emallson:feature/brm-sheet) for the current codebase.

Stats to Evaluate:

*EHRPS:*

- [x] Armor
- [x] Agility (Dodge)
- [x] Agility (Stagger)
- [x] Agility (GotOx)
- [x] Mastery (Dodge)
- [x] Mastery (GotOx)
- [x] Versatility (DR)
- [x] Versatility (Healing)
- [x] Crit (Celestial Fortune)
- [x] Crit (Critical Heals)
- [ ] Haste (extra Purifies)
- [ ] Validate splitting of heals (compare to holy paladin; lower priority because our heals are pretty shit)

*EHP:*

- [ ] HP
- [ ] Armor
- [ ] Agility
- [ ] Versatility
- [ ] Avoidance (?)

**Comment by abelito75** [comment]
I know TotRC is just a reference but since it has been sacked for about a year you might want to change the name and remove the link :P also is this still not fully done or naw

**Comment by abelito75** [comment]
Is this still something looking to be completed?
