### ISSUE TITLE
Cleanup Havoc Demon Hunter

### ISSUE THREAD

**Issue by sMteX** [WoWAnalyzer/WoWAnalyzer#2888]
Havoc DH is supposed to be 8.0.1 compatible but yet there is ton of now obsolete legendary code (Delusions of Grandeur, Mo'arg Bionic Stabilizers, Raddon's Cascading Eyes, Anger of the Half-Giants) that can potentially break the site.

Also Vengeance DH has 1 reference to legendaries too - Abilities, L75 (Demon Spikes) refers to Oblivion's Embrace.

**Comment by yajinni** [comment]
Hey not exactly sure what you mean about the VDH stuff, can you clarify for me?

**Comment by sMteX** [comment]
Sure - https://github.com/WoWAnalyzer/WoWAnalyzer/blob/e7e7e3574c7bbe2294e3c502c7f9e6f0475960ce/src/parser/demonhunter/vengeance/modules/Abilities.js#L78 this line still refers to the legendary

**Comment by yajinni** [comment]
Omg read that as talents lvl 75 demon spikes and was super confused. You meant abilities files line 75 lol damn ok will fix lol
