### ISSUE TITLE
Add a self-healing statistic for healer specs

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2911]
Healers that self-heal more than others with targeted heals is often a bad thing. This would highlight this issue.

It should probably only include direct heals, things like Light of Dawn can not reasonably be affected.

**Comment by Styrofoam12** [comment]
Currently working on an implementation of this (for on holy paladin first). Should it have some breakdown of which spells you used on yourself? Potentially a small graph light the "filler" section along with the list next to it?

**Comment by MartijnHols** [comment]
Do you think it would be useful to a lot of users? I imagine the rate (percentage) is what matters, and the details being in WCL would be sufficient. I try to avoid showing information that's unnecessary most of the time to reduce distractions.

You could include a drilldown link to WCL in the statistic. `master` has a warcraft link prop in the statistics, while in `next` it's been renamed to drilldown.

**Comment by Styrofoam12** [comment]
That's a good point, thanks for the input.

**Comment by abelito75** [comment]
I might be wrong but this statistic could easily display hurtful information. 
I'll let other chip in but if a fight has a mechanic that does large ST damage and the healer gets it they will probably be casting self heals which might make this statistic harmful if its goal is to point that out as an issue...
From my pov blizzard always seems to try to though in some single damage into a fight that could easily force self healing as the best option

**Comment by MartijnHols** [comment]
A statistic can hardly be hurtful. It just shows what happened, and leaves interpretation to the user. If you consistently self heal more than others, your co-healers or in comparison to other healers of the same class on the same fight, this might indicate an issue. Tunneling on keeping yourself alive and topping yourself off while others are lower health and/or dying would be an issue.

**Comment by abelito75** [comment]
I might be confused them. I assumed that this would highlight an issue so it would be a suggestion/checklist item for healers. If that isn't the case and all it does is show how many ST heals you casted on healers vs on non healers its w/e

**Comment by MartijnHols** [comment]
I think this would be especially interesting with @emallson's plan to show reference stat values for other logs.
