### ISSUE TITLE
Create a `removebuff` normalizer for buffs that expired after the fight

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2921]
That way we no longer have to check for this everywhere.

Needed for 3.0.

**Comment by PatrM** [comment]
Hey @MartijnHols , is this still open to work on? I'd love to start help working on WoWAnalyzer and use this issue to get into it :)

**Comment by MartijnHols** [comment]
Yes it’s up for grabs
