### ISSUE TITLE
Trinket: incandescent sliver

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2929]
We'd like a module to track the value of this trinket, averaged out over the entire fight. This will allow us to see the actual in-game value and compare it with other trinkets.

My suggestion: For this particular trinket it would be nice to see the average crit and mastery gained during the fight as well as the average stacks. If you can think of a great way to indicate the "nearby allies" effect that would be very nice to have too. Maybe include in the tooltip the names (with class colors) of the other players in the raid that also have this trinket.

https://www.wowhead.com/item=165571/incandescent-sliver&bonus=4798:1507

![image](https://user-images.githubusercontent.com/4565223/50929044-92907c00-145c-11e9-98f8-ac58003357d9.png)

**Comment by Sharrq** [comment]
looks like this was resolved already.
