### ISSUE TITLE
Convert Maelstrom trackers to ResourceTracker

### ISSUE THREAD

**Issue by sMteX** [WoWAnalyzer/WoWAnalyzer#2936]
The code is a *little* cryptic and I think it would benefit nicely from the general ResourceTracker - after all, there's a reason why it's generalized.

**Comment by MikeCook9994** [comment]
It looks like this has been done already and the issue wasn't closed. 

https://github.com/WoWAnalyzer/WoWAnalyzer/tree/master/src/parser/shaman/shared/maelstromchart

MaelstromTracker extends ResourceTracker and that's the class used for the resource breakdown and by the chart.

**Comment by HawkCorrigan** [comment]
Yup
Probably didn't see the issue when I did that.
Thanks
