### ISSUE TITLE
Convert modules using `item()` into `statistic()`

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2939]
`item()` got deprecated. There are only 40 usages of it in next. I'd like to convert all these usages to `statistic()` so that `item()` can be removed completely. The goal is to convert all of the item objects to the format that is already required by statistic. [Here is an example commit.](https://github.com/WoWAnalyzer/WoWAnalyzer/commit/89473cee6b0f65f66bad696ce8ec56862e29f0b2#diff-a0070669e44d826e4825a77af12b7320)

Using `statistic()` gives us much more freedom to style the item statistics.

I think this is about 1 hour of work for anyone experienced with the project, more if you're not.

**Comment by MartijnHols** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=68486321)](https://www.bountysource.com/issues/68486321-trinket-ward-of-envelopment)

**Comment by egormesyats** [comment]
#2955
