### ISSUE TITLE
Implement time filtering (phase selection)

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2940]
# Requires considerable knowledge of the project. It is recommended to _not_ attempt this as your first issue but to get familiar with the project first through easier things.

Now that #2706 has been completed, giving us info about when the fight's phases are, the next step is to implement time filtering. i.e. to be able to parse only the events within the select time frame.

I'll write the full specifications later. The gist of it is:

- Be able to filter the results by the selected time period.
- Modules have to properly show the right info for the time period. No leakage from outside the time period unless it would make the resulting stat more accurate.
- Normalizers should obviously continue to work, as best as possible.
- Provide a phase selection dropdown in the results page that applies a filter by the fight start and end timestamps.
- it should have cooldown and buff info from outside the phases

**Comment by MartijnHols** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=68697545)](https://www.bountysource.com/issues/68697545-implement-phase-selection-filtering)

**Comment by MartijnHols** [comment]
Increased:
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=68697545)](https://www.bountysource.com/issues/68697545-implement-phase-selection-filtering)

**Comment by mul1sh** [comment]
@MartijnHols this bounty looks interesting 🙂  let me try it out

**Comment by MartijnHols** [comment]
Increased:
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=68697545)](https://www.bountysource.com/issues/68697545-implement-phase-selection-filtering)

**Comment by mul1sh** [comment]
@MartijnHols I've been getting familiar with the project and I think I fully understand it now, will do my PR tomorrow 🙂
