### ISSUE TITLE
(Ele Shaman) Dark Knowledge (NPC spell) shows up in "Wasted Maelstrom"

### ISSUE THREAD

**Issue by Fonjask** [WoWAnalyzer/WoWAnalyzer#2958]
Report (Normal, Alliance): https://wowanalyzer.com/report/hAx6LgfNYPRzjMWn/7-Normal+Opulence+-+Kill+(7:24)/54-Fonjex/maelstrom

On Opulence: https://www.wowhead.com/npc=145261/opulence#comments

Healers with the Amethyst of the Shadow King: https://www.wowhead.com/spell=284558/amethyst-of-the-shadow-king

When they heal someone they apply Shadow-Touched: https://www.wowhead.com/spell=284556/shadow-touched

Any time a Shadow-Touched player takes Shadow damage, it triggers Dark Knowledge: https://www.wowhead.com/spell=290648/dark-knowledge&dd=14&ddsize=30

Which shows up in the "Maelstrom wasted" category. 
![See image](https://user-images.githubusercontent.com/1679047/51844460-9e61b680-2315-11e9-9652-4a6e8e0535fb.png)

**Comment by HawkCorrigan** [comment]
This is awesome.
That prolly marks the moment where I should switch over to the general resource tracker...


Anyway I'll see if I can find a bandaid fix today or if just switching over completely can be done over the next two days.

First and foremost, thanks for the report.

**Comment by abelito75** [comment]
This looks to be fixed :) gonna close it
