### ISSUE TITLE
Add role counts to raid composition page

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2961]
![image](https://user-images.githubusercontent.com/4565223/51935953-6a66be00-2407-11e9-9797-60385a055858.png)

| Tanks | Healers | Melee DPS | Ranged DPS |
| --|--|--|-- |
| 2 | 3 | 5 | 10 |

**Comment by tmshneeki** [comment]
I'm going to try and get this done in the next day or two with help from a friend as my first project.  Stay tuned! @florianschut

**Comment by florianschut** [comment]
![image](https://user-images.githubusercontent.com/9513884/53303503-38604480-386b-11e9-9077-4deeefa09466.png)

I've been having a bash at this as my first JS task, any feedback on the looks of this mockup?

**Comment by tmshneeki** [comment]
I believe this is now done by @florianschut ?

**Comment by MartijnHols** [comment]
Indeed
