### ISSUE TITLE
Add average item level and average heart level to raid composition page

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2962]
![image](https://user-images.githubusercontent.com/4565223/51935953-6a66be00-2407-11e9-9797-60385a055858.png)

| Item level | Heart level | ...roles |
| --|--|-- |
| 373 | 23 | #2961 |

**Comment by florianschut** [comment]
I'll have a look at this assuming no more changes are needed to #3020 😃

**Comment by florianschut** [comment]
iLvL is already in, I want to try to add HoA level to it this weekend but want to do that simultaneously with moving the calculations to the RaidCompositionDetails.js to keep PlayerLoader.js clean and the details self-contained... I do need to wrap my head around the react stuff as that is what ground me to a halt with this last week... If this is inconvenient regarding the release of next poke either here or on Discord.

**Comment by Scotsoo** [comment]
Done! Added in my latest commits!

**Comment by MartijnHols** [comment]
Thanks!
