### ISSUE TITLE
NEXT: Fetch heart level from Blizz API and add it to raid composition page

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2963]
![image](https://user-images.githubusercontent.com/4565223/51936270-19a39500-2408-11e9-8dec-c83d05bc4a6c.png)

The data is not yet available in the API data available. You should be able to get it with the `items` field from the Blizzard character API. We do not fetch that yet, you'll have to implement that. We don't care about most of the rest of the items field data, although maybe the character page uses it?

**Comment by 4Ply** [comment]
Assuming this is still unassigned; I plan to work on this as my first contribution to this project. 

Can I confirm that you refer to the itemLevel of the "Heart of Azeroth" item?

**Comment by MartijnHols** [comment]
It's actually about the azerite power level rather than the item level.

**Comment by 4Ply** [comment]
@MartijnHols Oh, then I shall update the PR tonight

**Comment by 4Ply** [comment]
@MartijnHols I believe this can be marked as closed.

https://next.wowanalyzer.com/report/2Yjwczk8KRnyVvrt/6-Heroic+Champion+of+the+Light+-+Kill+(3:30)
