### ISSUE TITLE
Add a "raid buffs" overview to the raid composition page

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2964]
![image](https://user-images.githubusercontent.com/4565223/51936432-7737e180-2408-11e9-98be-7f03df6a75ca.png)

Raid buffs such as:
- PW:S
- Battle Shout
- Arcane Intellect
- Mystic Touch
- Chaos Brand
- Bloodlust
- Combat ress
- Healer cooldowns
  - Aura Mastery
  - Spirit Link Totem
- External cooldowns?

The list goes on.

**Comment by Johnogram** [comment]
Has anyone started this?

Would love to contribute to this project and seems like a good starting point for me :)

**Comment by MartijnHols** [comment]
There has been no mention of anyone doing any work on this yet! Good luck, let us know if you need any help. Here or [on Discord](https://wowanalyzer.com/discord).

**Comment by darthelit** [comment]
Are you still working on this @Johnogram ? I was going to try and bash this one out over the weekend.

**Comment by Johnogram** [comment]
Haven't had time to get anywhere so feel free to take it over 👌

**Comment by darthelit** [comment]
Making progress. Should be done soon

**Comment by tmshneeki** [comment]
@darthelit I know that @florianschut was either working or looking at working on this too.  He is away on vacation for another couple of days but perhaps try to tie up with him

**Comment by darthelit** [comment]
Oh. Well.... If that is the case then I will stash what I'm doing now and wait for confirmation.

**Comment by florianschut** [comment]
@darthelit it’s true that I had a brief look at at it as I was working on an other feature on the player selection page but I never started nor did any further research so by all means continue! Sorry I could respond earlier, as Shneeki mentioned I’m currently abroad and not behind a pc much...

**Comment by darthelit** [comment]
I haven't been able to put much effort into this issue recently unfortunately. I have a branch on my fork that has everything but the UX hashed out if anyone wants to have a look and pick this up from where I left off.
