### ISSUE TITLE
Mistweaver Monk Usage of Thunder focus tea

### ISSUE THREAD

**Issue by luomiao55** [WoWAnalyzer/WoWAnalyzer#3005]
With the new Azerite Powers for Mistweaver Monk called Secret Infusion, it is better to use Enveloping Mist after thunder focus tea (to obtain high critical chance) and than cast Essence font to gain lots of healing. Casting renewing mist after thunder focus tea does not fully use of this Azerite power.  Hence, use enveloping mist after casting thunder focus tea can not be called mistake after  casting thunder focus tea

**Comment by anom0ly** [comment]
In a raid this is almost never the case. The trade off of mana of an EvM for a potential in increasing your crit for EF is not worth it. 

So the current suggestion still stands, at REM for throughput and Viv for mana conservation being the two best TFT options, even with SI.
