### ISSUE TITLE
Havok DH: Death Sweep not counted as Blade dance

### ISSUE THREAD

**Issue by leeter** [WoWAnalyzer/WoWAnalyzer#3013]
During a meta or Demonic phase Blade dance changes into Death Sweep. The analyzer seems to misread this as missing cooldowns on blade dance, even though the cooldown is actually being used.

**Comment by yajinni** [comment]
there are some complications because of its nature that i am working on for this. will update once i have explored some more possible fixes for this issue.

**Comment by torothin** [comment]
I believe this issue was completed 3/28/2019 by Yajinni.  At least that is what the Havoc DH changelog says.
