### ISSUE TITLE
[Retribution Paladin]Inquisition Tracker

### ISSUE THREAD

**Issue by LordSkeletor** [WoWAnalyzer/WoWAnalyzer#3054]
I quickly realized this was far beyond what I am capable of doing. Here is a mock-up image of what I was trying to achieve. I didn't fill in all the time remaining columns because I figured the point was made. 

-Cast is what cast it was.
-Holy Power used is the amount of resource used as it is variable from 1-3 Holy Power.
-Time remaining is how much time was left of the buff if any was remaining.

![](https://i.imgur.com/K8suPlt.png)

**Comment by Juko8** [comment]
I think that having it listed as cast #1, 2, 3, 4 and so on is somewhat redundant, and it'd be more useful to see the timestamps of each cast.

I could potentially take a look at creating this, but i'd like to get an update on how are we feeling about marking casts as inefficient in the case of <3 holy power spent or early refreshing?

**Comment by LordSkeletor** [comment]
Casts might be a bit redundant, the HP used and Time Remaining are the only 2 things that really need to be there. Other modules seems to list the cast number so I was just going with that for consistency.

Refreshing early casts as inefficient is a good idea. We would probably want some level of buffer time though for cases such as making sure it has enough remaining time for Wings. As far as inefficient for using less  than 3HP I think it's probably not a great idea. In some cases refreshing at 1 or 2 is OK such as an intermission is coming up soon or the fight is ending.

**Comment by Pewtro** [comment]
Fixed in #3517
