### ISSUE TITLE
Show concordance of legionfall uptime

### ISSUE THREAD

**Issue by buimichael** [WoWAnalyzer/WoWAnalyzer#31]
This necessarily doesn't have to do with anything with your play style. Although it can be interesting to see how much this golden trait has contributed to.

**Comment by MartijnHols** [comment]
I saw a Concordance of Legionfall display on the Shaman Discord that I'm pretty sure was done with this tool. Josh mentioned the guy who posted it is Exorsus Resto Shaman who maintains ERT. Hoping we can use that as basis.

![image](https://cloud.githubusercontent.com/assets/4565223/26501240/4bc90ff4-4239-11e7-9ba4-f7fb222200ae.png)

**Comment by fyruna** [comment]
Working on this as we speak. Feedback is welcome!
![image](https://user-images.githubusercontent.com/5927637/31575615-36f0fa08-b0eb-11e7-9a13-96c3080f0c1e.png)

**Comment by buimichael** [comment]
Fixed in #514
