### ISSUE TITLE
[BrM] ISB Cast Efficiency is sometimes > 100%

### ISSUE THREAD

**Issue by emallson** [WoWAnalyzer/WoWAnalyzer#3100]
https://wowanalyzer.com/report/hnYgGBNQbVH3m8CT/10-Heroic+King+Rastakhan+-+Kill+(6:40)/Wuhua/overview
![image](https://user-images.githubusercontent.com/4909458/55597831-88111600-571d-11e9-9ee0-2bc0c8af714c.png)

**Comment by HawkCorrigan** [comment]
Same issue as discussed in discord

Cast Efficiency continues recharging stacks after the fight ends.

**Comment by emallson** [comment]
Might not be---the one we were talking about on discord had fewer casts than available casts. This one doesn't.

**Comment by abelito75** [comment]
Was this fixed with your changes @emallson

**Comment by Pewtro** [comment]
Since Ironskin Brew is removed in Shadowlands, we can probably close this
