### ISSUE TITLE
[CoS] Death recap for insatiable torment

### ISSUE THREAD

**Issue by Dambroda** [WoWAnalyzer/WoWAnalyzer#3110]
https://www.wowhead.com/spell=285652/insatiable-torment

Can't heal yourself with this debuff, someone suggested death recap might be updated to indicate this (healthstones/pots shouldnt appear, etc)

**Comment by fyruna** [comment]
@Dambroda are there any logs that can be used to track this?

**Comment by Dambroda** [comment]
This was reported to me on discord, I unfortunately do not have any sample logs :(

**Comment by Pewtro** [comment]
Is this still relevant, it's the previous tier, right?
