### ISSUE TITLE
[Discipline Priest] Atonement sources module doesn't recognize Shadowfiend as source with Lightspawn glyph

### ISSUE THREAD

**Issue by florenciella** [WoWAnalyzer/WoWAnalyzer#3146]
![image](https://user-images.githubusercontent.com/5898030/58060958-c70df600-7b28-11e9-9ac6-09a438082e80.png)
https://www.warcraftlogs.com/reports/VrFHpmDfk4thBjTL#fight=25&type=healing&source=9
The above screenshot is from the kill in the log I linked, as you can see no Melee healing is recorded in the module, even though it is present in the log. It is present in the module for the other discipline priest in the raid, and the only difference I can think of is the presence of the Lightspawn glyph.

**Comment by DylanDirlam** [comment]
Fixed and can be closed
