### ISSUE TITLE
[Holy Paladin] Glimmer of Light

### ISSUE THREAD

**Issue by 5chmidt** [WoWAnalyzer/WoWAnalyzer#3168]
With the [Glimmer of Light build](https://questionablyepic.com/glimmer-of-light/) showing up as the [top mythic healing build](https://www.warcraftlogs.com/zone/statistics/22#metric=hps&dataset=95&class=Healers) I think it would be helpful to add a statistic tracker that would track things that are important to the build like: Holy Shocks/minute, average glimmer buffs up, beacon transfer, and a check to see if glimmer buffs are being overwritten early. 

Here is a log that uses the build optimally:
https://www.warcraftlogs.com/reports/TX4nzPy8WwrfLv97#fight=19&type=healing&source=5

and one that does not:
https://www.warcraftlogs.com/reports/KZR2NMDJhLpQT4kX#fight=15&type=healing&source=8

**Comment by 5chmidt** [comment]
I have started working on this item and have found that:
`    this.addEventListener(this.beaconHealSource.beacontransfer.by(SELECTED_PLAYER), this.onBeaconTransfer);`
is not functioning the way I anticipated.  When looking for the original spell id, I am using:
`const spellId = event.originalHeal.ability.guid;`
but am an not seeing the id for [Glimmer of Light](https://www.wowhead.com/spell=287286/glimmer-of-light) coming through onBeaconTransfer.  The transfer is showing Glimmer of Light healing transfer for beacon healing sources on master.  
@MartijnHols, is there a better way I should be checking the beacon healing source?

My WIP branch can be found here:
https://github.com/WoWAnalyzer/WoWAnalyzer/compare/master...5chmidt:dev/glimmer_of_light

**Comment by MartijnHols** [comment]
It might be a different id from what you're looking at. It's showing up in the beacon heal sources tab so it shouuld be in the beacon transfer events.

**Comment by 5chmidt** [comment]
@MartijnHols, that was exactly it. Thanks.

The last aspect I want to track is: up time lost due to early refreshes of glimmer of light.  I am calling:
    `this.addEventListener(Events.refreshbuff.by(SELECTED_PLAYER).spell(SPELLS.GLIMMER_OF_LIGHT_BUFF), this.onRefresh);`
I want to get the remaining duration from the event object when onRefresh was called.  I see there are several hots that are using the HotTracker which keeps track of the remaining duration.  Is this the best method to do this?  Unlike hots and dots there is no extension added when rebuffing someone before the current buff expires, I'm not sure if this will effect the HotTracker.
Thanks,

**Comment by 5chmidt** [comment]
Merged into master from PR 3178
https://github.com/WoWAnalyzer/WoWAnalyzer/pull/3178
