### ISSUE TITLE
error from interaction with lastpass

### ISSUE THREAD

**Issue by hendrikreimann** [WoWAnalyzer/WoWAnalyzer#3209]
I am getting a persistent error when trying to use the site:

l.LegacyGlobal.should_do_lastpass_here is not a function. (In 'l.LegacyGlobal.should_do_lastpass_here(document)', 'l.LegacyGlobal.should_do_lastpass_here' is undefined)

initialize@safari-extension://com.lastpass.lastpassmacdesktop.safariext-N24REP3BMN/20fcac33/extension/content-script.js:75:869276
forEach@[native code]
initialize@safari-extension://com.lastpass.lastpassmacdesktop.safariext-N24REP3BMN/20fcac33/extension/content-script.js:75:850461
initialize@safari-extension://com.lastpass.lastpassmacdesktop.safariext-N24REP3BMN/20fcac33/extension/content-script.js:75:872698
safari-extension://com.lastpass.lastpassmacdesktop.safariext-N24REP3BMN/20fcac33/extension/content-script.js:75:887819
l@safari-extension://com.lastpass.lastpassmacdesktop.safariext-N24REP3BMN/20fcac33/extension/content-script.js:75:837097
a@safari-extension://com.lastpass.lastpassmacdesktop.safariext-N24REP3BMN/20fcac33/extension/content-script.js:75:835936
promiseReactionJob@[native code]

Looks like it doesn't play well with the lastpass extension.

**Comment by MartijnHols** [comment]
Looks like this is a common issue with the extension on Safari: https://forums.lastpass.com/viewtopic.php?f=14&t=335125

Nothing we can do about it.
