### ISSUE TITLE
Add support for Outlaw Rogue

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#3220]
Since I do not know Outlaw Rogue, I can not specify a definition of done. If you think it's ready to be marked as supported, you'll have to somehow convince us of this as well. That probably means it has to check similar things to what guides tell you to look for, such as in Icy Veins' [how to improve](https://www.icy-veins.com/wow/how-to-improve-outlaw-rogue) section.

**Comment by MartijnHols** [comment]
Added a bounty to equal a 12 month subscription to the game:

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=77338825)](https://www.bountysource.com/issues/77338825-add-support-for-outlaw-rogue)

**Comment by Coywolf** [comment]
With the checklist merged, I think Outlaw can be called supported. The only thing I think is missing is a rarely used talent, 'Loaded Dice'. It very slightly changes Roll the Bones logic, but is picked <5% of the time according to WCL, even in Normal.

I'm not sure how best to prove it, as the 'How to Improve' section on Icy Veins is pretty bare for Outlaw (it actually links to WowAnalyzer :) ). Would it help if I copy over the rotation from Icy Veins and then list out how each step is covered?

**Comment by MartijnHols** [comment]
Sorry for responding so late, I never realised this notification was something I had to do about. Feel free to ping me on Discord to look at an issue in the future if my action is required.

Sound good to me. Could you update the supported flag, supported version and description in [the config](https://github.com/WoWAnalyzer/WoWAnalyzer/blob/master/src/parser/rogue/outlaw/CONFIG.js) to reflect this please? Then I can close the issue and you'll be able to claim the bounty.

**Comment by soloxcx** [comment]
The current build is not complete. Wasted combo points for Sinister Strike are tracked incorrectly, the Roll the Bones logic and efficiency tests are outdated, proper Adrenaline Rush usage is not working, Vanish usage should be omitted and Blade Rush should be tested to see if it used at high energy or not. among other changes. I want to tackle this issue.

**Comment by tyndivelspaz** [comment]
Working on this as part of #3743 
I'll make sure these points are addressed in it as well.
