### ISSUE TITLE
Tank Essences

### ISSUE THREAD

**Issue by emallson** [WoWAnalyzer/WoWAnalyzer#3221]
# General
- [x] Crucible of Flame
- [ ] Conflict and Strife
- [x] Worldvein
- [ ] Vision
- [ ] Lucid Dreams

# Tank-Only
- [x] Null Dynamo
- [ ] Sphere
- [ ] Undying Gift
- [ ] Anima (maybe #wontfix)
- [ ] Aegis

**Comment by Pewtro** [comment]
Goodbye BFA, Goodbye Azerite.
