### ISSUE TITLE
Add support for Enhancement Shaman

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#3222]
Since I do not know Enhancement Shaman, I can not specify a definition of done. If you think it's ready to be marked as supported, you'll have to somehow convince us of this as well. That probably means it has to check similar things to what guides tell you to look for, such as in Icy Veins' [how to improve](https://www.icy-veins.com/wow/how-to-improve-enhancement-shaman) section.

**Comment by MartijnHols** [comment]
Added a bounty to equal a 12 month subscription to the game:

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=77338846)](https://www.bountysource.com/issues/77338846-add-support-for-enhancement-shaman)

**Comment by Yoiro** [comment]
Hey, I'm playing Enhancement and I'd like to contribute here, but I'm not sure where to start or what to look for.

**Comment by abelito75** [comment]
[https://github.com/WoWAnalyzer/WoWAnalyzer/wiki](url)
Is a good starting place but its a pretty manual process of going through all the files in the enhancement parser and making sure they are all valid :P

**Comment by djanse** [comment]
I've a friend playing Enhancement Shaman at the moment. In order to help him improve in his raiding situations I'll be making a lot of changes in order too get the analyser up-to-date. Expect a lot to be updated in the current month.

**Comment by kenrms** [comment]
I can help, too. I play enhance now and plan on continuing in SL. Already got a chunk of it started on my fork.

**Comment by abelito75** [comment]
Sound great!
