### ISSUE TITLE
"this.manaTea.casts is null" - Error Occurred While Rendering Page

### ISSUE THREAD

**Issue by SamBaldwin93** [WoWAnalyzer/WoWAnalyzer#3236]
The following log analysis doesn not display correctly and has an error - https://wowanalyzer.com/report/ptR9jFMyPYNzTb83/4-Mythic++Tol+Dagor+-+Kill+(44:08)/Krixian

Here are some screenshots of the error messages: 

https://gyazo.com/584a027ef8be644554bc722634c5eddf

https://gyazo.com/cd97bec50cc4b7773c1e97391c528181

**Comment by abelito75** [comment]
Alright got a fix in for this 👍

**Comment by MartijnHols** [comment]
Since the issue has been fixed I am closing this
