### ISSUE TITLE
Healer Essence: Well of Existence

### ISSUE THREAD

**Issue by 5chmidt** [WoWAnalyzer/WoWAnalyzer#3244]
Create a statistic for the well of existence azerite trait.  It has its own spell id and should be pretty easy to track in a log.  Important things to track are: number of triggers, HPS and healing per trigger.

https://www.warcraftlogs.com/reports/MpZ18yYwvnVTNmgb/#type=healing&boss=-2&difficulty=0&wipes=2&source=4&ability=296184

**Comment by Sharrq** [comment]
Was resolved by #3199
