### ISSUE TITLE
Add support for TypeScript

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#3252]
TypeScript is starting to become really popular and with good reason. We should offer people the possibility of coding with TS which might be easier for people new to the project. This should also make the core more robust.

I think this might come free with #3251, otherwise still follow the CRA instructions. No more ejecting or forking though. Keep things simple which keeps them easy to maintain

I'd also like to require TS files to be formatted with prettier. Just TS for starters.

**Comment by MartijnHols** [comment]
Should be just a matter of making a tsconfig.json

**Comment by darthelit** [comment]
How far are you wanting to go with this? A project I'm hoping off of used CRA v3 with redux, typescript, eslint, and prettier. I can give this is a stab after this week.

**Comment by MartijnHols** [comment]
Hey I just made a PR introducing TypeScript as I've been setting it up a lot for other projects lately so it wasn't that hard for me anymore: https://github.com/WoWAnalyzer/WoWAnalyzer/pull/3426

I hope you didn't spend any time on this yet. If you want to play around with TypeScript, please consider picking any file and converting it to TypeScript.

**Comment by darthelit** [comment]
I didn't spend any time on this luckily. I can go through and work on converting files into Typescript and adding the types, interfaces and classes as necessary.
