### ISSUE TITLE
Wild Growth HPCT is incorrectly calculated (halved?) in the Mana Efficiency Table

### ISSUE THREAD

**Issue by qikink** [WoWAnalyzer/WoWAnalyzer#3309]
https://wowanalyzer.com/report/pY1bTJkWt2cMq7aG/35-Mythic+Orgozoa+-+Wipe+18+(8:13)/Eluv/statistics

That log shows the issue. It has 23 Wild Growth casts for a total healing of 4.78M, but only shows an HPCT of 81k. Assuming that HPCT, each cast would have taken an average of 2.56s. I double checked the timeline to ensure there weren't any cancelled casts inflating the number. In the same log, Swiftmend shows an average cast time of 1.24s, almost exactly half the supposed cast time of Wild Growth. Assuming the variance is due to variable haste, it seems possible the Wild Growth number is exactly half what it should be.

**Comment by niseko** [comment]
Should be resolved now. The issue was indeed a doubling of the cast time somewhere as you assumed and it affected all spells with cast time.

Thanks for the report!
