### ISSUE TITLE
Cannot convert undefined or null to object when viewing Character page of example Specs

### ISSUE THREAD

**Issue by Marcarrian** [WoWAnalyzer/WoWAnalyzer#3366]
When viewing the Character page on the example specs it throws the following JavaScript error:

`Cannot convert undefined or null to object`

Routing with the back button becomes difficult after the error has been thrown.

example: https://wowanalyzer.com/report/wptPT3mfWavbj9KY/33-Heroic+Conclave+of+the+Chosen+-+Kill+(6:22)/Jakedk/character

**Comment by MikeCook9994** [comment]
Fixed by #3367
