### ISSUE TITLE
[Core] 8.3 Corruptionforging bonuses

### ISSUE THREAD

**Issue by Juko8** [WoWAnalyzer/WoWAnalyzer#3398]
https://www.wowhead.com/news=295789/corrupted-items-is-the-new-titanforging-details-how-it-works
Could be great with some stat boxes on the various bonuses. Be aware of PTR numbers being likely to change with balancing. 

### Beneficial effects
- [ ] Avoidance from haste. Average avoidance gained and DRPS
- [ ] Extra secondaries from all sources. Average stat gained. 
- [ ] Health regen during combat. HPS.
- [ ] Extra healing received. HPS
- [ ] Leech. HPS.
- [ ] Cooldown reduction proc. Breakdown of spells that benefited and procs that were wasted (currently being consumed by spells without cooldown)
- [ ] Critical damage increase. DPS.
- [ ] DoT damage reduction. DRPS.
### Detrimental effects
- [ ] Death recap note about dying to effects caused by high corruption

**Comment by Pewtro** [comment]
Has been added (and again deleted on shadowlands branch)
