### ISSUE TITLE
Add statistic box "progress" bars

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#340]
To show healing vs absorbed vs overhealing and damage vs absorbed and active vs downtime it would be nice to be able to show bars underneath statistics that show this.

![image](https://user-images.githubusercontent.com/4565223/30670137-7659eb38-9e61-11e7-9cc7-21069f06a44f.png)

In this screenshot *Healing done* and *Overhealing* could be merged into a bar underneath *Healing done* that shows [healing done (green)|absorbed (darker green)|overhealing (black)]. Tooltip then reveals the overhealing percentage.
Non healing time should probably become downtime to simplify things and should show [active time (green)|downtime (red)].
Damage done would show normal vs absorbed damage.

Holy Paladin's IoL FoL to HL cast ratio could also use this. Filler cast ratio as well. Maybe unused infusion of lights.

**Comment by anom0ly** [comment]
@MartijnHols I know you implemented this with some of the damage and healing taken statistic boxes. Is there anything outstanding or can we close this one down and reference those statistics as guides?

**Comment by MartijnHols** [comment]
Yeah that's done, thanks.
