### ISSUE TITLE
Balance Druid Analysis: Stellar Flare Pandemic Coding Problem

### ISSUE THREAD

**Issue by TheArcticWolf** [WoWAnalyzer/WoWAnalyzer#3439]
The Wow Analyser is currently incorrectly marking Stellar Flare refreshes as early in the current iteration of the Balance Druid Analysis. 

Stellar Flare is a talented Balance Druid dot lasting 24s with a pandemic of 7.2s. Currently the analysis is marking certain casts as early i.e. 'before the pandemic window' despite being clearly inside the window. Example given below; A fresh Stellar Flare was applied at 2:56.868, and refreshed at 3:16.023 (~5.6s left on the dot). Wow Analyzer has marked this as an early refresh with feedback 'Stellar Flare was refreshed 0:02 seconds before the pandemic window. It should be refreshed with at most 0:07 left or part of the dot will be wasted'. 

![Screenshot_436](https://user-images.githubusercontent.com/59130856/71317385-f9b30f00-24ba-11ea-9f15-14c1b1a08d96.png)

![Screenshot_435](https://user-images.githubusercontent.com/59130856/71317386-fcadff80-24ba-11ea-8216-000652bd928e.png)

![Screenshot_437](https://user-images.githubusercontent.com/59130856/71317389-fe77c300-24ba-11ea-8db5-d5e331171f8d.png)

I have had a look at the other refreshes during the fight (some good and some bad), and have been unable to figure out why the analyser is doing this, without further investigation. I have limited knowledge of coding or GitHub so I apologise for formatting errors etc.

**Comment by MikeCook9994** [comment]
There was a known issue with early refreshes that we checked in a fix for I believe the same day you made this issue. Not sure if it was before or after. Please check your report again and let us know if you see the same issue.

**Comment by TheArcticWolf** [comment]
Thanks for getting back to me. I will make sure to let you know if I see the same issue.

________________________________

**Comment by MartijnHols** [comment]
In that case I'll close this ticket for now. We'll reopen if you run into it again.
