### ISSUE TITLE
Will it support wow classic ?

### ISSUE THREAD

**Issue by infinity8942** [WoWAnalyzer/WoWAnalyzer#3441]
I use this analyzer on retail, and it helps me a lot. Wonderful work!

Will it support wow classic? I wanna help these friends as well.

**Comment by Sharrq** [comment]
There is no one working on supporting classic at the moment and there are no plans to do so at this time.

**Comment by MikeCook9994** [comment]
just press 1

**Comment by MartijnHols** [comment]
Primarily due to time constraints we will not be able to provide support for classic.
