### ISSUE TITLE
Evangelism, Atonement and Overcharge Mana HPS calculation broken.

### ISSUE THREAD

**Issue by xelakais** [WoWAnalyzer/WoWAnalyzer#3457]
Commit ef8fa8a broke 3 modules with a variable name change namely modules AtonementHealingDone.js, Evangelism.js, and TheEverRisingTide.js. Reverting the variable name from actualHealing to healing seems to fix the issue.

You can see the HPS showing as 0 and an error [here](https://www.wowanalyzer.com/report/aVWhXkHtz8FrpvRm/1-Mythic+The+Queen's+Court+-+Kill+(7:15)/Raikkonen/standard/statistics) and [here](https://www.wowanalyzer.com/report/dYBvJRac413pwtWM/40-Mythic+Za'qul+-+Kill+(4:48)/Ninjaristic/standard/statistics).

Apologies for the terseness. Previous issue submission broke on me and I had to rewrite everything.

**Comment by MartijnHols** [comment]
Thanks for the clear report! This issue should now be fixed.
