### ISSUE TITLE
Arms Warrior Azerite Traits

### ISSUE THREAD

**Issue by torothin** [WoWAnalyzer/WoWAnalyzer#3538]
The following Azerite Traits are Arms Warrior specific and need to be added:

Test of Might
Gathering Storm
Crushing Assault
Lord of War
Striking the Anvil
Seismic Wave

I am using the following document to track changes and work for Arms Warrior:
https://docs.google.com/document/d/1v6OmuUTdAZuY9AZeajh4nsVmnCR0bwX0Zx3My_eE5VQ/edit?usp=sharing

**Comment by Sharrq** [comment]
Bfa is over, dont need azerite traits anymore
