### ISSUE TITLE
Wow analyzer listing me as a bloodelf.

### ISSUE THREAD

**Issue by Cptnubbins** [WoWAnalyzer/WoWAnalyzer#3571]
This is just a small issue but wow analyzer has been listing me as a blood elf for a while now, when i use it it'll show that i'm not using cooldowns enough cause i'm not using arcane torrent. How would i go about to making it my current race which is a pandaren?

**Comment by MartijnHols** [comment]
Thanks for the report. This should be fixed since https://github.com/WoWAnalyzer/server/pull/17
