### ISSUE TITLE
Current version of Node not functioning

### ISSUE THREAD

**Issue by djanse** [WoWAnalyzer/WoWAnalyzer#3572]
I had to unfortunatly re-setup my development environment. Only to receive an error upon running `yarn install` [See Screenshot](https://cdn.discordapp.com/attachments/316864385052049420/709137893247156234/unknown.png)

After completely removing node (v14.2) and installing an earlier version (v13.14), it all started working.

**Comment by MartijnHols** [comment]
node-sass is a PITA but replacing it would be too much effort for now. We should probably update it.

**Comment by djanse** [comment]
> node-sass is a PITA but replacing it would be too much effort for now. We should probably update it.

What would node-sass be replaced with? I might want to look into it.

**Comment by MartijnHols** [comment]
CSS in JS. It would be a gigantic project, probably not worth doing without simultaneously doing several other refactors.
