### ISSUE TITLE
Discipline priest analyzer does not count Death Throes trait DPS/HPS correctly

### ISSUE THREAD

**Issue by lossril** [WoWAnalyzer/WoWAnalyzer#3617]
https://www.wowanalyzer.com/report/qDhA61Rpv8zydXm4/1-Mythic++The+Underrot+-+Kill+(25:00)/Lossril/standard/statistics
Here I can see that Death Throes DPS/HPS is 0, which is obviously not correct (character has one trait equipped).

Same goes for any log for this character with Death Throes equipped. For example, this one:
https://www.wowanalyzer.com/report/VcxmRJytwCGKp2q1/1-Mythic++Freehold+-+Kill+(19:49)/Lossril/standard/statistics

**Comment by Pewtro** [comment]
A note regarding Mythic+ logs is that WoWAnalyzer is not made for them, and there can be unforeseen issues throughout M+ logs that are not handled properly (downtime is a big one) within WoWAnalyzer. We're made for raids. 

However, I see this issue for a raid log also: https://wowanalyzer.com/report/AfNDRBr1HZJCwyXb/11-Mythic+Maut+-+Kill+(4:09)/%E5%9B%9B%E9%9B%B6%E5%85%AB/standard/statistics

**Comment by lossril** [comment]
Possible cause of the bug: Purge The Wicked has two SpellIDs in warcraftlogs

**Comment by Pewtro** [comment]
Goodbye BFA, Goodbye Azerite.
