### ISSUE TITLE
Improve initial page load/performance

### ISSUE THREAD

**Issue by vpicone** [WoWAnalyzer/WoWAnalyzer#3644]
<img width="680" alt="Screen Shot 2020-06-27 at 7 03 14 PM" src="https://user-images.githubusercontent.com/4078018/85934503-ebe6a800-b8a8-11ea-98e4-dd5b5244e097.png">

The problem:
The initial page load is burdened by the massive change log. There's an incredible amount to scroll through, it makes the pagination at the bottom very difficult to use/discover.

The current heuristic for which changes to show is [all of the changes since five articles ago](https://github.com/WoWAnalyzer/WoWAnalyzer/blob/master/src/interface/news/List.js#L84). Considering the last article was written roughly a year ago, this is a substantial amount and the _5th_ article (the one we print changelogs through) was roughly 2 years ago.

Potential Solutions:
1. Combine Articles and changelogs, set a max number of "entries" and increase the number of pages
3. Move the change log and articles to a separate page. We could remove the pagination all together and not care about performance.

**Comment by Sharrq** [comment]
I believe this was resolved by #3645

**Comment by Pewtro** [comment]
It would indeed seem so.
