### ISSUE TITLE
[Holy Paladin] Shadowlands Beta Issues

### ISSUE THREAD

**Issue by Decnalabnu** [WoWAnalyzer/WoWAnalyzer#3656]
Use your primary skills as often as possible:  Needs to be updated to where LoD and WoG are spenders and other spells are builders and might have less possible casts.

LoD Casting Efficiency should be looked at in general.  Reliant on HP now.

Statistics Page: Aura damage reduction doesn't show up.  
Holy avenger HPS likely to be incorrect.  Now grants a HP generation boost.  Perhaps track "additionally generated HP" instead of direct hps.
Infusions are currently worthless so depending on live tuning might need to drop this category.

Cooldowns Page:

Currently showing passive procs  under the cooldowns window.  Example: Hit wings and "Valiant Strikes" procs.  Shouldn't appear as it is not a casted spell.

Character Page:  This should probably be updated to include covenant and soul binds if the api allows.

Side note: on the triage spec it would be nice to see an aggregate view of the raids healers doing triage healing and then if you click on a healer it shows their particular breakdown.  It's quite annoying to have to open a tab for each healer to compare how their triage healing went but is purely personal preference.

Thanks for your great work!

**Comment by 5chmidt** [comment]
@decnalabu Thanks for writing this up!
I don't have beta access, to test things but some stuff like counting the extra holy power in Holy Avenger seems pretty straight forward.  Here is an English log I was able to find:
https://www.warcraftlogs.com/reports/yRwaCGm6BMVAqfdD#fight=17&source=11

I should have some time this weekend to look at a few of these items.

**Comment by 5chmidt** [comment]
Word of Glory is on the GCD in Shadowlands correct?
![image](https://user-images.githubusercontent.com/3276248/93671963-1ba2e780-fa75-11ea-9357-11645bf71222.png)

**Comment by abelito75** [comment]
This isn't an issue anymore
