### ISSUE TITLE
Mistweaver Shadowlands Update

### ISSUE THREAD

**Issue by abelito75** [WoWAnalyzer/WoWAnalyzer#3659]
Changes Mistweaver needs for shadowlands, this will be updated as blizzard releases new things or implements them.

### Core
- [x] Update Mistweaver's Abilities.json
- [x] Update Mistweaver core spells
- [x] Update Mistweaver talents
- [x] Add Touch of Death module (should track damage and healing if they add healing orbs to it)
### Covenants
- [x] Add Fallen Order Covenant (track all the numbers it makes)
- [x] Add Weapons of Order Covenant (track the aoe heal and mastery gained on average)
- [x] Add Bonedust Brew Covenant (track extra gusts healing and any bonus healing it provides)
- [x] Add Faeline Stomp Covenant (track extra bolt, # of resets, total healing, extra mastery procs because of it)
### Conduits
- [x] Track Rising Sun Revival's healing
- [x] Track Rising Sun Revival's CDR
- [x] Fortifying Ingredients (track extra shield value gained)
- [x] Track Jade bond's healing increase 
- [x] Track Jade Bond's cdr
- [x] Track Grounding Breaths hps
- [x] Track Grounding Breaths mana saved

**Comment by darthelit** [comment]
Are there logs out there that can be used to test changes for those who don't have beta?

**Comment by abelito75** [comment]
Typically class discords will have logs of their spec

**Comment by darthelit** [comment]
Gotcha. Thanks.

**Comment by abelito75** [comment]
These have been done for a hot minute
