### ISSUE TITLE
[Core] Remove Azerite

### ISSUE THREAD

**Issue by Pewtro** [WoWAnalyzer/WoWAnalyzer#3667]
This should be merged once the expansion is live. 
This includes all the azerite spells, and all their mentions and files throughout the codebase.
- [ ] Death Knight
- [ ] Druid
- [ ] Hunter
- [x] Mage
- [ ] Monk
- [ ] Paladin
- [ ] Priest
- [ ] Rogue
- [ ] Shaman
- [ ] Shared
- [ ] Warlock
- [ ] Warrior

**Comment by Sharrq** [comment]
Mage azerite and such has been removed in the shadowlands branch
