### ISSUE TITLE
[Death Knight] Shadowlands Update

### ISSUE THREAD

**Issue by joshinat0r** [WoWAnalyzer/WoWAnalyzer#3669]
**This issue contains all currently listed legendaries, conduits and soulbinds on wowhead as of 27.07.2020**
Unholy & Frost spec changes are not listed, feel free to edit this issue (if you can) or ping me on discord

### DK Specific Covenant Abilities
- [x] [Swarming Mist](https://shadowlands.wowhead.com/spell=311648/swarming-mist)
- [ ] [Shackle the Unworthy](https://shadowlands.wowhead.com/spell=312202/shackle-the-unworthy)
- [ ] [Abomination Limb](https://shadowlands.wowhead.com/spell=315443/abomination-limb)
- [ ] [Deaths Due](https://shadowlands.wowhead.com/spell=315442/deaths-due)

### Conduits
https://www.wowhead.com/guides/death-knight-soulbind-conduits-shadowlands

Potency
- [ ] [Proliferation](https://shadowlands.wowhead.com/spell=338664/proliferation)
- [ ] [Impenetrable](https://shadowlands.wowhead.com/spell=338628/impenetrable-gloom)
- [ ] [Brutal Grasp](https://shadowlands.wowhead.com/spell=338651/brutal-grasp)
- [ ] NYI

Endurance
- [ ] [Hardened Bones](https://shadowlands.wowhead.com/spell=337972/hardened-bones)
- [ ] [Insatiable Appetite](https://shadowlands.wowhead.com/spell=338330/insatiable-appetite)
- [ ] [Reinforced Shell](https://shadowlands.wowhead.com/spell=337764/reinforced-shell)

Finesse
- [ ] [Chilled Resilience](https://shadowlands.wowhead.com/spell=337704/chilled-resilience)
- [ ] [Fleeting Wind](https://shadowlands.wowhead.com/spell=338093/fleeting-wind)
- [ ] [Spirit Drain](https://shadowlands.wowhead.com/spell=337705/spirit-drain)
- [ ] [Unending Grip](https://shadowlands.wowhead.com/spell=338311/unending-grip)

### Legendaries
https://shadowlands.wowhead.com/spells/legendary-item-effects/death-knight

*Tried to sort them properly into generic/spec legendaries, move them to the proper spec if I made a mistake*

- [x] [Superstrain](https://shadowlands.wowhead.com/spell=334974/superstrain) (Tripple Plagues)
- [ ] [Phearomones](https://shadowlands.wowhead.com/spell=335177/phearomones) (Minions? Unholy only?)
- [ ] [Death's Certainty](https://shadowlands.wowhead.com/spell=334898/deaths-certainty) (DS/DC reduce DnD CD)
- [ ] [Grip of the Everlasting](https://shadowlands.wowhead.com/spell=334724/grip-of-the-everlasting)
- [ ] [Death's Embrace](https://shadowlands.wowhead.com/spell=334728/deaths-embrace)

### Runeforges
- [x] [Rune of Hysteria](https://shadowlands.wowhead.com/spell=326911/rune-of-hysteria)
- [ ] [Rune of Sanguination](https://shadowlands.wowhead.com/spell=326805/rune-of-sanguination)
- [ ] [Rune of Spellwarding](https://shadowlands.wowhead.com/spell=326855/rune-of-spellwarding)
- [ ] [Rune of Unending Thirst](https://shadowlands.wowhead.com/spell=326977/rune-of-unending-thirst)
- [ ] [Rune of the Apocalypse](https://shadowlands.wowhead.com/spell=327082/rune-of-the-apocalypse)
- [x] Fallen Crusader
- [x] Create module to create generic runeforge suggestions (eg Blood is only using FC/Hysteria, all others should throw a generic `You might want to use FC instead suggestion`) (DW frost needs some more tweaks)

### Talents
- [ ] [Death Pact](https://shadowlands.wowhead.com/spell=48743/death-pact)

### Old new spells
- [x] add [Lichborne](https://shadowlands.wowhead.com/spell=49039/lichborne)
- [x] add [Anti-Magic Zone](https://shadowlands.wowhead.com/spell=51052/anti-magic-zone)
- [x] add [Raise Dead](https://shadowlands.wowhead.com/spell=46585/raise-dead) to all specs (was Unholy only previously)
- [x] add [Sacrificial Pact](https://shadowlands.wowhead.com/spell=327574/sacrificial-pact)
- [x] add [Chains of Ice](https://shadowlands.wowhead.com/spell=45524/chains-of-ice)
- [x] add [Death Coil](https://shadowlands.wowhead.com/spell=47541/death-coil) to all specs

## Blood
- [x] Remove unused spells/buffs/debuffs from src/common/SPELLS/
- [x] Remove unused talents and associated buffs/debuffs from src/common/SPELLS/talents/
- [x] order new talent tree
- [x] Rune Tap is baseline & off GCD
- [x] Blood Tap is now a talent
- [x] Ossuary is now baseline
- [x] add new Talent 
- [x] [Relish in Blood](https://shadowlands.wowhead.com/spell=317610/relish-in-blood) (heal & RP on DnD after CS proc)
- [x] Talent 'Rune Strike' is gone

### Soulbinds
Potency
- [ ] [Withering Plague](https://shadowlands.wowhead.com/spell=337884/withering-plague)
- [ ] [Debilitating Malady](https://shadowlands.wowhead.com/spell=338516/debilitating-malady)

Endurance
- [ ] [Blood Bond](https://shadowlands.wowhead.com/spell=337957/blood-bond)
- [ ] [Meat Shield](https://shadowlands.wowhead.com/spell=338435/meat-shield)

Finesse

### Legendaries

- [ ] [Crimson Rune Weapon](https://shadowlands.wowhead.com/spell=334525/crimson-rune-weapon)
- [ ] [Vampiric Aura](https://shadowlands.wowhead.com/spell=334547/vampiric-aura)
- [x] [Bryndaor's Might](https://shadowlands.wowhead.com/spell=334501/bryndaors-might)
- [ ] [Gorefiend's Domination](https://shadowlands.wowhead.com/spell=334580/gorefiends-domination)

## Frost
- [x] Remove unused spells/buffs/debuffs from src/common/SPELLS/
- [x] Remove unused talents and associated buffs/debuffs from src/common/SPELLS/talents/
- [x] [Hypothermic Presence](https://shadowlands.wowhead.com/spell=321995/hypothermic-presence)
- [x] [Frostwyrm's Fury](https://shadowlands.wowhead.com/spell=279302/frostwyrms-fury) is baseline
- [x] [Empower Rune Weapon](https://shadowlands.wowhead.com/spell=317230/empower-rune-weapon) CD reduced by 15 sec.
- [x] [Icecap](https://shadowlands.wowhead.com/spell=207126/icecap) increase CDR from 3 to 4
- [ ] Add resource usage block for RP

### Conduits
https://www.wowhead.com/guides/death-knight-soulbind-conduits-shadowlands

Potency
- [ ] [Accelerated Cold](https://shadowlands.wowhead.com/spell=337822/accelerated-cold)
- [ ] [Biting Cold](https://shadowlands.wowhead.com/spell=337988/biting-cold)
- [ ] [Eradicating Blow](https://shadowlands.wowhead.com/spell=337934/eradicating-blow)
- [ ] [Unleashed Frenzy](https://shadowlands.wowhead.com/spell=338501/unleashed-frenzy)

Endurance

Finesse

### Legendaries
- [ ] [Koltira's Favor](https://shadowlands.wowhead.com/spell=334583/koltiras-favor)
- [ ] [Biting Cold](https://shadowlands.wowhead.com/spell=334678/biting-cold)
- [ ] [Absolute Zero](https://shadowlands.wowhead.com/spell=334692/absolute-zero)

## Unholy
- [x] Remove unused spells/buffs/debuffs from src/common/SPELLS/
- [x] Remove unused talents and associated buffs/debuffs from src/common/SPELLS/talents/
- [x] [Summon Gargoyle](https://shadowlands.wowhead.com/spell=317250/summon-gargoyle) baseline
- [ ] [Sudden Doom](https://shadowlands.wowhead.com/spell=49530/sudden-doom) works for Epidemic now
- [x] [Apocalypse](https://shadowlands.wowhead.com/spell=316961/apocalypse) CD reduced by 15 sec.
- [x] [Army of the Damned](https://shadowlands.wowhead.com/spell=276837/army-of-the-damned) needs implementation
- [x] [Death Coil Rank 2](https://shadowlands.wowhead.com/spell=316941/death-coil) needs to be verified/implemented 
- [ ] [Unholy Blight](https://shadowlands.wowhead.com/spell=115989/unholy-blight) Affects minion damage
- [ ] [Unholy Pact](https://shadowlands.wowhead.com/spell=319230/unholy-pact) New talent, requires implementing
- [ ] Add resource usage block for RP

### Conduits
https://www.wowhead.com/guides/death-knight-soulbind-conduits-shadowlands

Potency
- [ ] [Embrace Death](https://shadowlands.wowhead.com/spell=337980/embrace-death)
- [ ] [Eternal Hunger](https://shadowlands.wowhead.com/spell=337381/eternal-hunger)
- [x] [Convocation of the Dead](https://shadowlands.wowhead.com/spell=338553/convocation-of-the-dead)
- [ ] [Lingering Plague](https://shadowlands.wowhead.com/spell=338566/lingering-plague)

Endurance

Finesse

### Legendaries
- [ ] [Reanimated Shambler](https://shadowlands.wowhead.com/spell=334836/reanimated-shambler)
- [ ] [Frenzied Monstrosity](https://shadowlands.wowhead.com/spell=334888/frenzied-monstrosity)
- [ ] [Deadliest Coil](https://shadowlands.wowhead.com/spell=334949/deadliest-coil)

**Comment by jjs451** [comment]
Updated with Frost changes

**Comment by jjs451** [comment]
Updated with Unholy changes

**Comment by yajinni** [comment]
blood tap moved from baseline to talent
ossuary moved from talent to baseline.
changes to appocalypse.
https://www.wowhead.com/news=317904/shadowlands-beta-build-35854-class-and-spell-changes-tank-tuning
