### ISSUE TITLE
[Shadowlands][Discipline Priest] Shadowlands Update

### ISSUE THREAD

**Issue by rp4rk** [WoWAnalyzer/WoWAnalyzer#3726]
# Prepatch
These are the changes that should be prioritised in the event that we would like to support prepatch, this is unlikely but it makes sense to prioritise them just to be safe. 

## Spellbook
* [ ] Add Shadow Covenant module to encompass new mechanics
* [x] Add Mind Blast to the list of spells considered for Atonement
* [x] Add Mind Sear to the list of spells considered for Atonement
* [x] Update cooldown information for Power Word: Solace
* [ ] Add Spirit Shell module

# Shadowlands
These changes will not be needed until the logs for Shadowlands raid content start becoming available, meaning they can be undertaken as part of hacktober safely.

## Legacy
* [x] Delete Azerite Power modules

## Spellbook
* [ ] Power Infusion

### Covenant Abilities
* [x] Mindgames
* [x] Boon of the Ascended
* [ ] Unholy Transfusion (_Low priority, at risk of being changed before launch_)
* [ ] Fae Blessings (_No Discipline specific interactions, reach out to other priest developers_)

### Covenant Signatures
> _Note these may be implemented at a much more generic level, be sure to check before starting work on them._

* [ ] Door of Shadows
* [ ] Phial of Serenity
* [ ] Fleshcraft
* [ ] Soulshape

## Legendaries
- [ ] Clarity of Mind
- [ ] The Penitent
- [ ] Kiss of Death

## Conduits
- [ ] Exaltation
- [ ] Shattered Perceptions
- [ ] Courageous Ascension
- [ ] Clear Mind
- [x] Shining Radiance
- [ ] Fae Fermata (_No Discipline specific interactions, reach out to other priest developers_)
- [ ] Chartiable Soul
- [ ] Light's Inspiration
- [ ] Swift Penitence
- [ ] Pain Transformation
- [ ] Rabid Shadows
- [ ] Festering Transfusion
- [ ] Mind Devourer

## Soulbinds
_There are currently no Discipline specific interactions from Soulbinds that are known._

**Comment by ThePkell** [comment]
Hey guys, I'm really new to this, but is there something that you can task out to me that I can work on?

**Comment by karlpralow** [comment]
hey @ThePkell there's still alot to be done so your help would be great. There's multiple things to do right now, if you want to hit me up on discord we can discuss this (Oratio in Focused Will)

**Comment by Ogofo** [comment]
Hello,
I submitted a PR for the Boon of the Ascended module see #3851 . 
I will work on the Spirit Shell module next :)
