### ISSUE TITLE
Update Retribution Paladin for Shadowlands

### ISSUE THREAD

**Issue by Juko8** [WoWAnalyzer/WoWAnalyzer#3728]
Changes Retribution needs for shadowlands, this will be updated as blizzard releases new things or implements them.

### Core
- [x] Update Spellbook
- [x] Update cast efficiency
- [x] Update Hammer of Wrath to use new execute module
- [ ] Update Execution Sentence module
### Covenants
- [ ] Kyrian
- [ ] Venthyr
- [ ] Necrolord
- [ ] Night Fae
### Legendaries
- [x] Final Verdict
- [ ] The Mad Paragon
- [ ] Relentless Inquisitor
- [ ] Tempest of the Lightbringer
### Conduits
- [ ] Expurgation
- [ ] Templar's Vindication
- [ ] Truth's Wake
- [ ] Virtuous Command

**Comment by abelito75** [comment]
@Juko8 I think i made a HoW module for you in shared
