### ISSUE TITLE
[Shadowlands][Rogue] Shadowlands Update

### ISSUE THREAD

**Issue by darthelit** [WoWAnalyzer/WoWAnalyzer#3743]
_I am not a Rogue main, nor have I ever played a Rogue as my main. I am updating some backend code for Rogue to catch it up to some of our other specs and I will be updating their spellbook for the base shadowlands changes. I will be attempting to learn all 3 specs and keep this class up to date to the best of my abilities. If you have suggestions for functionality you would like added to the class, feel free to comment._

_I will fill in the below once I have had a chance to dig through all the changes_

**Shared Changes**
- [x] Convert to Typescript
- [x] Remove BFA Items
- [x]  Add Event Listeners
- [x] Update `StatisticBox` components to `Statistic` components
- [ ] Address needs in #3220 
- [ ] Address needs in #2411 

### Specs
**Subtlety**
- [x] [Black Powder](https://shadowlands.wowhead.com/spell=319175/black-powder)

### Generic
**Rogue Specific Covenant Abilities**
- [X] [Echoing Reprimand](https://shadowlands.wowhead.com/spell=323547/echoing-reprimand)
- [X] [Flagellation](https://shadowlands.wowhead.com/spell=345285/flagellation)
- [X] [Sepsis](https://shadowlands.wowhead.com/spell=328305/sepsis)
- [X] [Serrated Bone Spike](https://shadowlands.wowhead.com/spell=328547/serrated-bone-spike)

**Conduits**
Potency
- [x] [Deeper Daggers](https://shadowlands.wowhead.com/spell=341549/deeper-daggers)

Endurance

Finesse

**Legendaries**
Rogue
- [x] Essence of Bloodfang 

Assassination
- [X] Dashing Scoundrel (Energy gained)
- [x] Dustwalker's Patch

Subtlety
- [X] Akaari's Soul Fragment (Extra Shadowstrike Damage)
- [x] The Rotten (Combo Point generation)

Outlaw
- [X] Guile Charm (Damage Buff)

**Comment by darthelit** [comment]
First iteration is in the PR phase. Going to be adding the remaining legendaries that may need to be tracked then focus on each spec individually to wrap up any loose ends.

**Comment by Tradanel** [comment]
Hello,

I play Assassination Rogue as my main since LK. If you need help understanding this spec, i'm here to help.

Unfortunately, I'm not very good at coding. The only things i know is how to rewrite some luacode in some addon files but no more.

If you are interested in this, I would be happy to help you.

My regards,
Perfectø.

PS : sorry for some bad english, i'm french :)
