### ISSUE TITLE
[Demon Hunter] Shadowlands Update

### ISSUE THREAD

**Issue by yajinni** [WoWAnalyzer/WoWAnalyzer#3747]
## Shared
- [ ] Now share the Fury resource.
- [ ] Immolation Aura now baseline.
- [ ]  Shattered Souls - heal/damage increase calculations changes
- [ ] Torment now baseline.
- [ ] Throw Glaive  now baseline.

## Demon Hunter Specific Covenants
https://www.wowhead.com/guides/demon-hunter-covenant-abilities-shadowlands
- [x] Elysian Decree
- [x] Sinful Brand
- [ ] Fodder to the Flame
- [x] The Hunt

## Soulbind Conduits
https://www.wowhead.com/guides/demon-hunter-soulbind-conduits-shadowlands
**Potency Conduits: Four for Havoc, two for Vengeance, and four Covenant specific Conduits.**

**Havoc**
- [ ] Dancing with Fate
- [ ] Demon's Touch
- [x] Growing Inferno
- [ ] Serrated Glaive

**Vengeance**
- [ ] Soul Furnace 
- [ ] NYI

**Covenant**
- [ ] Repeat Decree
- [ ] Increased Scrutiny
- [ ] Brooding Pool
- [ ] Unnatural Malice 

**Endurance Conduits: There are three Endurance Conduits available to both specs and another two available only to Vengeance.**

**Both**
- [x] Fel Defender
- [ ] Shattered Restoration
- [ ] Viscous Ink 

**Vengeance**
- [ ] Demon Muzzle
- [ ] Roaring Fire

**Finesse conduits: Each class has four Finesse Conduits which are usable by both specs.**

**Both**
- [ ] Demonic Parole
- [ ] Felfire Haste
- [ ] Lost in Darkness 
- [ ] Ravenous Consumption

## Legendary
https://www.wowhead.com/guides/demon-hunter-legendary-powers-in-shadowlands

**Both**
- [x] Collective Anguish
- [ ] Darkglare Boon
- [ ] Fel Bombardment
- [ ] Half-Giant Empowerment

**Havoc**
- [x] Chaos Theory
- [ ] Darkest Hour
- [ ] Erratic Fel Core
- [ ] Inner Demons

**Vengeance**
- [ ] Fel Flame Fortification
- [ ] Fiery Soul 
- [ ] Razelikh's Defilement
- [ ] Spirit of the Darkness Flame

## Vengeance Changes
**Spells**
- [ ] Fel Devastation now baseline.
- [ ] Fiery Brand dot calculations
- [ ] Lesser Soul Fragment heals changed from 8% to 6%

**Talents**
- [ ] Remove  Flame Crash
- [ ] Remove Gluttony 
- [ ] Remove Razor Spikes
- [x] Add Demonic
- [ ] Add Infernal Armor
- [ ] Add Bulk Extraction

## Havoc Changes
**Spells**

- [ ] Check to see if the AOE caps cause any calculation problems.
- [ ] Cycle of Hatred now reduces the CD of Eye Beam instead of Meta
- [ ] Demonic Eye Beam causes you to enter demon form for 6 sec after it finishes dealing damage instead of 8.
- [ ] Blade Dance has a 15 sec cd instead of 9.

**Talents**

- [ ] Dark Slash becomes Essense Break. Check if calculations need to be reworked.
- [ ] Fel Mastery removed
- [ ] Nemesis  removed
- [ ] Netherwalk 3 min instead of 2 min cd
- [ ] Soul Rending 105 reduced to 5% leech. Gain an additional 25% Leech while Metamorphosis is active instead of 10.
- [ ] Desperate Instincts +DR is 10% instead of 15%

**Comment by joshinat0r** [comment]
# Known Bugs
- [ ] Havoc is missing talents which lead to crashed when opening the character-pane (Burning Hatred, Unbound Chaos, Glaive Tempest, Essence Break)
