### ISSUE TITLE
[Shadowlands] Spellbook updates for unmaintained specs

### ISSUE THREAD

**Issue by Sharrq** [WoWAnalyzer/WoWAnalyzer#3781]
Along with the Shadowlands release, we should also at the very least update the spellbooks for the specs that are not currently maintained so that the specs are at least semi functional

The below list is based on the last time the spec was updated (Patch Level).

- [x] Havoc Demon Hunter
- [x] Vengeance Demon Hunter
- [x] Balance Druid
- [x] Guardian Druid
- [x] Restoration Druid
- [x] Protection Paladin
- [x] Shadow Priest
- [x] Outlaw Rogue
- [x] Assassination Rogue
- [x] Subtlety Rogue
- [x] Affliction Warlock
- [x] Destruction Warlock
- [x] Demonology Warlock

**Comment by DylanDirlam** [comment]
Shadow priest can be marked off here.

**Comment by abelito75** [comment]
Closing this.
