### ISSUE TITLE
Internationalization of old strings

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#3803]
A lot of older files were made without i18n support. We need to add i18n support to those files. Please help us update all older files. This does not require any WoW or spec knowledge.

First import i18n.
```
import { i18n } from 'interface/RootLocalizationProvider';
```

then

Props:
```
error="The API is down."
```
=>
```
error={i18n._(t('visualPath.apiDown.error')`The API is down.`)}
```
Strings:
```
.actual(`${formatPercentage(actual)}% overhealing`)
```
=>
```
.actual(i18n._(t('visualPath.overhealing.actual')`${formatPercentage(actual)}% overhealing`))
```
Components:
```
<Link to="/">Home</Link>
```
=>
```
<Link to="/"><Trans id="visualPath.home">Home</Trans></Link>
```

Please use ids for all i18n strings (older i18n code has omitted this, that will need to be updated separately). The id should be `visualPath.id`, e.g. the "search" button in the report selector on the home page would be `home.reportSelector.search`.

Tutorials:

- https://lingui.js.org/tutorials/react.html#introducing-internationalization
- https://lingui.js.org/tutorials/react-patterns.html
- https://lingui.js.org/tutorials/javascript.html#localizing-your-app

**Comment by jafowler** [comment]
@MartijnHols Hi! Is there a list for the `visualPath.id`? For example looking at the following error : 
`<FullscreenError
          error="An API error occured."
          details="Something went wrong talking to our servers, please try again."
          background="https://media.giphy.com/media/m4TbeLYX5MaZy/giphy.gif">`

Would that just be something like `visualPath.api.error'? 

Or

`<FullscreenError
          error="A wild INTERNET EXPLORER appeared!"
          details="This browser is too unstable for WoWAnalyzer to work properly."
          background="https://media.giphy.com/media/njYrp176NQsHS/giphy.gif">`

Not sure what that would classify as other than maybe a `visualPath.notSupported.error` or something of the like, but i don't know if there is a pre-determined list for these.

**Comment by MartijnHols** [comment]
It doesn't really have to be perfect, just give a translator an idea where they can find a certain string. Since the API error can occur on any page, I would use `fullScreenError.error`, but `home.api.error` would be fine too.

**Comment by jafowler** [comment]
@MartijnHols would you prefer updates in phases? Or one giant lump of a PR?

**Comment by MartijnHols** [comment]
I would prefer many small PRs, but for something like this I do not mind the alternatives so long as there are 0 other changes apart of it. With small PRs, that is easier to handle.

**Comment by jafowler** [comment]
https://github.com/WoWAnalyzer/WoWAnalyzer/pull/3826 -- unsure what branch to make the PR against, but its easy to switch. I can't add any reviewers for some reason, and i can't seem to link it against this issue either. Not sure what I did wrong in creating the PR.
