### ISSUE TITLE
[Core] Move Stat constants out of StatTracker

### ISSUE THREAD

**Issue by Pewtro** [WoWAnalyzer/WoWAnalyzer#3835]
We have a lot of stat constant used in StatTracker.js, that should probably be in its own separate StatConstants.js file or similiar.

**Comment by anontyro** [comment]
hey @Pewtro I can look into this if you like :)

**Comment by Pewtro** [comment]
Specifically we have SPEC_MULTIPLIERS, DEFAULT_BUFFS, statMultiplierBuffs and statMultiplier that could possibly deserve moving out.

**Comment by anontyro** [comment]
sure I can look into moving these :)

**Comment by Pewtro** [comment]
I don't think all need moving tbh 😄

**Comment by anontyro** [comment]
sure I'll look at what makes sense to move and aim to move only those

**Comment by anontyro** [comment]
@Pewtro made a PR for this let me know if there is anything that should be updated/ changed :) and I'll fix it tomorrow

**Comment by abelito75** [comment]
Reading the attempted PR on this it seems its not an issue anymore. Closing.
