### ISSUE TITLE
Is it possible to consider supporting classic?

### ISSUE THREAD

**Issue by ieiayaobb** [WoWAnalyzer/WoWAnalyzer#3850]
I saw this issue (https://github.com/WoWAnalyzer/WoWAnalyzer/issues/3441) and it seems more and more requirements for wow classic.
Is it possible to consider creating a separate branch to support wow classic?

**Comment by Pewtro** [comment]
I can only give the same answer that was given in December 2019. There are no plans for it, there is no (widespread) interest for it amongst current maintainers and there is definitely not enough time in the day for the current maintainer team to also have to maintain a classic branch of wowanalyzer. 

These are the same reasons other optimizing tools such as simc don't work for classic either.

**Comment by ieiayaobb** [comment]
Thank you for answering @Pewtro
