### ISSUE TITLE
Prot Paladin Checklist: show "missed" SotR casts

### ISSUE THREAD

**Issue by emallson** [WoWAnalyzer/WoWAnalyzer#3872]
SotR can be cast without a target, or without being in range of the current target. However, it is currently a HUGE damage source and it is bad to be constantly casting it w/o being in range.

**Comment by hpabst** [comment]
I'd like to take on this issue if possible.

**Comment by emallson** [comment]
Go for it

**Comment by hpabst** [comment]
Analyzer is ready for CR, just waiting on the Consecration Typescript conversion to be merged in so there aren't more conflicts with the integration test snapshots.

As an aside, what thresholds do you think are appropriate for "missed" SotR suggestions? So far looking at logs I've seen mostly 100% hit scenarios so I feel something like 98% is a suitable minor suggestion threshold.

**Comment by emallson** [comment]
Starting at 98/95/92 is probably good.

**Comment by emallson** [comment]
Closed by #3901
