### ISSUE TITLE
Prot Paladin Checklist: Available WoGs

### ISSUE THREAD

**Issue by emallson** [WoWAnalyzer/WoWAnalyzer#3874]
Similar to old "Available Purifying Brew charges" functionality: calculate # of Holy Power available while maintaining 100% effective uptime on SotR, and use that to calculate # of available non-free WoG casts.

**Comment by 5chmidt** [comment]
Is there anything else to do on this issue?
It looks like: [WordOfGlory.txs](https://github.com/WoWAnalyzer/WoWAnalyzer/blob/shadowlands/analysis/paladinprotection/src/modules/spells/WordOfGlory.tsx) is handling all the items mentioned.
I think this can be closed.

**Comment by abelito75** [comment]
Is this issue closeable?
Have we completed and/or invalidated this task?
