### ISSUE TITLE
Prot Paladin Checklist: "Bad" WoG Casts

### ISSUE THREAD

**Issue by emallson** [WoWAnalyzer/WoWAnalyzer#3876]
A WoG cast is bad if:

- it is not free, and
- it causes you to get hit w/o SotR up, and
- the healing from WoG did not save your target's life (or close enough)

OR

- it is free, and
- it overheals a substantial amount (say, 25%)

**Comment by abelito75** [comment]
Is this issue closeable? 
Have we completed and/or invalidated this task?

**Comment by emallson** [comment]
Will be closed by guide stuff I think.
