### ISSUE TITLE
Prot Paladin: Update Talents

### ISSUE THREAD

**Issue by emallson** [WoWAnalyzer/WoWAnalyzer#3877]
Prot actually got talent updates (jealous) in Shadowlands. Need to go through and add support for the relevant ones.

**Comment by abelito75** [comment]
You might want to look at shared as it does handle some of the generic talnets :D 
Edit: src/parser/paladin/shared

**Comment by hpabst** [comment]
# Shadowlands Prot Paladin Talents:
## SL Talent List
### Row 1
- Holy Shield (Unsupported)
- Redoubt (Unsupported)
- Blessed Hammer (Unsupported)

### Row 2
- First Avenger (Unsupported)
- Crusader's Judgement (Unsupported)
- Moment of Glory (Unsupported)

### Row 3
- Utility talents, likely no need to support.

### Row 4
- Utility talents, likely no need to support.

### Row 5
- Divine Purpose (updated by Abe)
- Holy Avenger (updated by Abe)
- Seraphim (needs to be updated for SL)

### Row 6
- Utility talents, likely no need to support.

### Row 7
- Sanctified Wrath (Unsupported)
- Righteous Protector (Unsupported)
- Final Stand (AoE taunt, likely no need to support)

## Priority Support
Wowhead recommends the following raiding talents at the moment: Holy Shield, Crusader's Judgement, Divine Purpose, Sanctified Wrath. I'll start working on these going backwards from row 7.

**Comment by abelito75** [comment]
I haven't checked but you might want to implement the HoW module I made so you can have accurate cast efficiency suggestions for the spell

**Comment by hpabst** [comment]
Addendum: Crusader's Judgment is somewhat supported through the GrandCrusader and SpellUsable modules for prot paladin. We could leave as is, modify to make it more explicit that Judgment charges were added, or refactor to make GrandCrusader proc tracking shared between it's own analyzer and a separate Crusader's Judgment analyzer (which could track something like wasted Grand Crusader procs because Judgment was sitting at 2 charges already).

Thoughts? Regardless I'll work on converting the existing GrandCrusader work to TS.

**Comment by emallson** [comment]
I say leave it as-is. Unfortunately, SpellUsable is required to handle it
so we can never get it into its own module. At the same time, the analysis
makes the most sense as part of GrandCrusader (since the reset is tied to
that) and checklist/suggestions already exist for munching too many procs
by way of cast efficiency.

**Comment by abelito75** [comment]
Is the list above talking about (supported/not supported) still valid? Do we need to support any of the talents current not supported? Can we close this?

**Comment by emallson** [comment]
I say we close. There are a couple that are unsupported but they're also unused.
