### ISSUE TITLE
List all legendaries in items

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#388]
To make it easier to see what legendaries someone is using it would be nice to show all legendaries regardless of them being supported with its own module.

**Comment by anom0ly** [comment]
With PR #511 I believe all legendaries have now been added to the `ITEMS` files. I don't believe there are any outstanding at this time.

Just want to confirm before this is closed.

**Comment by sMteX** [comment]
Most likely all of them added (probably 7.3.5 Aman'thul's Vision is missing but that can be added once the tier lands).
