### ISSUE TITLE
[Arcane Mage] Arcane Orb multiple target

### ISSUE THREAD

**Issue by Nova900** [WoWAnalyzer/WoWAnalyzer#3948]
The tooltip of the "Use your talents effectively" category says for Arcane Orb Avg. Hits Per Cast: "Arcane Orb is primarily an AoE Spell, so you should only choose it on fights with multiple targets [...]"
Well, the whole talent row doesn't have any single target spells. Reverberate ist useless in pure single target, and Supernova is in all practical purposes less damage than Arcane Orb. So yeah, Arcane Orb *is* the singletarget choice. ^^

**Comment by Sharrq** [comment]
Yep you are right. Forgot to change that. Thanks for the suggestion, I'll work on getting that changed
