### ISSUE TITLE
Stat collapses open overtop of items below on WebKit

### ISSUE THREAD

**Issue by kfinch** [WoWAnalyzer/WoWAnalyzer#396]
On WebKit (iOS, it's the same on Chrome and Safari)

**Comment by kfinch** [comment]
Just a minute as I figure out how to upload a screenshot on mobile -_-

**Comment by kfinch** [comment]
![dc98b141-ab4d-4c53-a1f2-a4902c92782c](https://user-images.githubusercontent.com/7143486/30869749-f8fe93b6-a2af-11e7-9797-b822ef1f492f.png)

**Comment by buimichael** [comment]
This bug affects all statistics that uses the ExpandableStatisticBox

**Comment by MartijnHols** [comment]
This is working as intended. The alternative was to move all items below it down which would make the entire layout jump.

For this specific statistic I think you could show it in the cooldowns tab instead, and remove the expansion statistic.
