### ISSUE TITLE
The service worker doesn't always automatically start the app

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#397]
It fixes upon any form of refresh. This only start happening recently (I'm using Google Chrome), probably broke something. Finding it impossible to reproduce reliably or get any data on it, might just have to disable the offline version for now.

**Comment by kfinch** [comment]
I can confirm that I've also encountered this (Google Chrome on Windows 10)

**Comment by MartijnHols** [comment]
I just realized this has a fair chance of being an issue related to CloudFlare.
