### ISSUE TITLE
Convert all gives X amount of stat rating to a % value

### ISSUE THREAD

**Issue by Pewtro** [WoWAnalyzer/WoWAnalyzer#3979]
I don't think showing people the amount of rating gained from a trinket, proc, talent etc makes any sense in a world with diminishing returns. 
We should instead figure out a way to transform the rating given by something to a % value, and show that instead.

**Comment by abelito75** [comment]
I'm pretty sure this was done. I'll close it on Friday if nobody speaks up about seeing issues
