### ISSUE TITLE
Convert tab panel to horizontal tab list so it can work on mobile too and there's more space in general. Like the dev tools in chrome

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#398]
Like the dev tools in chrome
![image](https://user-images.githubusercontent.com/4565223/30874446-9e866d46-a2f0-11e7-8d17-30c3bed23161.png)

**Comment by anom0ly** [comment]
With PR #528 merged, can this issue now be closed?

**Comment by MartijnHols** [comment]
Looks really sweet, on mobile too! 👍
