### ISSUE TITLE
Protection Warrior Fixes / Suggetions

### ISSUE THREAD

**Issue by SorethroatWoW** [WoWAnalyzer/WoWAnalyzer#401]
**What browser are you using?**
Google Chrome

**Link to an example report with the issue**
https://wowanalyzer.com/report/FVDpm3AdaRqKxMTj/5-Heroic+Maiden+of+Vigilance+-+Kill+(6:58)/Sorethroat

Best example I could find.

**Expected behavior**

I will start by saying I see that the guide is labeled "Needs more work" and that this is not a complaint, rather a suggestion to hopefully get it working to its full potential. As of rite now it appears as though the guide is assuming you (the player) are always using the talents Indomitable and Heavy Repercussions as the recommendations it gives are impossible to meet unless using those specific talents. One example being it suggests at least an up time of >90% on Shield Block during blockable damage, which depending on your characters haste, is still tough to obtain when running Heavy Repercussions. The main reason I would point this out is due to the fact that Heavy Repercussions is starting to become less common among Protection Warriors. It is a talent that does fairly well early in progression, but once gear comes into play and survivability becomes easier Anger Management becomes a much more desirable choice. (You can see this but looking at the majority of Protection Warrior logs from anyone who is even semi-progressed.) Perhaps lowering the recommended Shield Block up time when noting that the player is not using the Heavy Repercussions talent would make much more sense. 

I would also put much more emphasis on Berserker Rage if the player is using the T20 2-piece as it should be used off cool down 100% of the time. 

The other issue I noted is how the guide tries to recommend a >80% usage of Thunder Clap. Thunder Clap loses priority greatly when running the Vengeance talent due to Revenge use weaving into cheaper Ignore Pains. Thunder Clap up time of >80% would make sense assuming you were running Indomitable, but as of live (7.3) Indomitable is extremely situation and is the weaker choice of talents 100% of the time. The suggested up time on Thunder Clap should be much lower if the player is using Vengeance. 

One suggestion I would add is how well the player actually managed the talent Vengeance. For those unfamiliar it requires the player to use Ignore Pain and Revenge back to back in order to maintain the 50% reduced cost on the spell. The amount of impact that can have is extremely huge depending on if it was manager correctly. The player does get a buff(s) called "Vengeance: Ignore Pain" and "Vengeance: Revenge". Both of which can be seen by looking under the players logs. The up time of each buff is not as important as how many counts of the buff came up. More counts would indicate the player was making use of the talent more. As you can see in the log I provided I had a count of 72 on "Vengeance: Revenge" and 74 on "Vengeance: Ignore Pain". If someone had numbers that were very different such as 20 on Revenge and 65 on Ignore Pain, that would indicate they are not making use of the talent and are losing out drastically on survivability. 

Another suggestion would be similar to how "You only had the Shield Block Buff buff for 54.55% of physical damage taken." but instead one similar for Spell Reflect. I feel like it would be tough to impliment something like this as Spell Reflect only has a 5 second duration on a 25 second CD, but something along the lines of this would be very useful.

I think with those changes it would make the guide much more accurate and helpful to any Protection Warriors using the WoW Analyzer. 

If you have any questions about Protection Warrior I would be more than willing to help out. 
Feel free to contact me.

Ryan
rk92505@gmail.com
Real ID: Bone#12336
Discord: Sorethroat#7355

**Comment by anom0ly** [comment]
Closed - Reference #402 to track spec feedback.
