### ISSUE TITLE
Implement Prettier

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#403]
PRs are too often about code style, this is a waste of time. With Prettier this is automatically resolved.

I implemented Prettier in a React project in the past and code quality only degraded because it had terrible JSX support. I think this has since been improved enough, but not sure.

**Comment by anom0ly** [comment]
Potentially we could utilize something similar to this: https://www.codacy.com/

I don't have any experience, just thinking of some potential alternatives to Prettier.

**Comment by anom0ly** [comment]
On second look through - This is basically just another level of ESLint. Not what we are looking I believe.

**Comment by Southpaw17** [comment]
Prettier takes half the rules of eslint and runs them for you.  It can also be added as a pre-commit hook so that contributors never need to worry about it, it just runs itself automatically

**Comment by MartijnHols** [comment]
I dislike that Prettier has no way to disable the max-length setting. I think this setting is detrimental to our code style quality.

This does not improve readability:
![image](https://user-images.githubusercontent.com/4565223/34343400-6bd730f0-e9cd-11e7-9c89-108728e6eb5d.png)
![image](https://user-images.githubusercontent.com/4565223/34343405-ac8af17c-e9cd-11e7-8587-2c5786003d44.png)
![image](https://user-images.githubusercontent.com/4565223/34343421-2cde1a48-e9ce-11e7-8e99-eab58190056c.png)

There are a lot more instances where the line length just makes things more messy.

It has more rules that make things slightly worse but as far as I've seen they're forgivable enough.

I personally believe line length is purely a preference thing that should be configurable in the editor of choice (through soft-wrapping). Long length should be avoided but not at the cost of readability and maintainability.

Closing this issue as a definitive *will not implement*. I'll probably setup more eslint-autofixers, but the sad thing is it's a lot more work, a lot more opinionated, a lot less complete, but at least not majorly detrimental.

**Comment by MartijnHols** [comment]
Reopening since eslint does not suffice. It can't even fix indentation; the one thing most commonly inconsistent. Maybe `--print-width 999` can work if we add ignores to the rules we do want to keep indented manually...

**Comment by MartijnHols** [comment]
I've been using it at work for a while and I still hate the code it produces with a vengeance, but at least it is a standard that requires no manual intervention during reviews. This is most important since that is completely wasted time. I am very interested in implementing this now.

Still, work enforces this style in a precommit git hook. This makes committing very painful and I absolutely do not want to introduce that here. Committing should remain quick and easy to do. I also do not want builds to fail on code style (unless it can't be fixed automatically, e.g. when a console.log is left).

I see a single solution for this; if we were to integrate Prettier we should implement a bot/builder that runs prettier --write for us and adds a commit to PRs and/or master. I can imagine it's easier to do on master since not every PR has "allow contributors to make changes" enabled. This seems hard to build.

I do not know of any existing solution that avoids painful commits or painful PRs (due to builds failing on code style). Suggestions are welcome.

**Comment by MartijnHols** [comment]
This may be possible: https://github.com/peter-evans/create-pull-request

**Comment by MartijnHols** [comment]
We can do this with a github action: https://github.com/ad-m/github-push-action

**Comment by MartijnHols** [comment]
https://github.com/creyD/prettier_action
