### ISSUE TITLE
Arcane Torrent doesn't show up on any classes Cast Efficiency

### ISSUE THREAD

**Issue by CollCrom** [WoWAnalyzer/WoWAnalyzer#408]
https://wowanalyzer.com/report/8arNFv3hG1HQZy6z/1-Mythic+Goroth+-+Kill+(2:59)/Holypalaswe/cast-efficiency

https://www.warcraftlogs.com/reports/8arNFv3hG1HQZy6z#fight=1&type=resources&source=4&spell=100

It is defined on line 104 in the holy pally cast efficiency.
Contact at @Zerotorescue on Discord / @MartijnHols

**Comment by MartijnHols** [comment]
This should have been fixed when I changed the AT spells to differentiate mana from the alternative versions (and added checking that no duplicate spells can be added again).

Thanks for the issue, please confirm that it is fixed.
