### ISSUE TITLE
Suggestion: For overall HPS, add a small note that overall overhealing is only something to truly worry about if you're having mana issues.

### ISSUE THREAD

**Issue by Emarline** [WoWAnalyzer/WoWAnalyzer#410]
<img width="651" alt="screen shot 2017-09-27 at 4 39 42 am" src="https://user-images.githubusercontent.com/32325603/30904138-0fcc3ee2-a33f-11e7-9f6d-2096088fc246.png">
Screenshot is an example of the overhealing bar. I think it should mention that overall overhealing isn't a massive concern unless you find yourself running OOM with high overhealing.

**Comment by anom0ly** [comment]
I would disagree. Just because you never run out of mana doesn't mean overhealing isn't an issue. High overheal with extra mana can be attributed to any of the other 3 comments already in the tool tip. 

I don't think modifying it makes sense, but I'll others weigh in also.

**Comment by MartijnHols** [comment]
I agree with @anom0ly and think the current tooltip offers enough information. Closing this issue for now.
