### ISSUE TITLE
HPM and HPSC are too truncated.

### ISSUE THREAD

**Issue by Daemeous** [WoWAnalyzer/WoWAnalyzer#4137]
HPM is rounded/truncated to the nearest whole number, at least for Holy Priest. Seeing Holy Word: Serenity, Heal and Halo at the same HPM of 3, for example, isn't as useful infomration as seeing that one is 3.49, the other 3.24, and if you round numbers possible even 2.51. Something simillar happens with HPSC which rounds/truncates to 1000, so you see 1000, 2000, 3000 etc. This level of precision was fine in BFA which much larger numbers but here it's no longer useful.

**Comment by abelito75** [comment]
I'll fix this tonight

**Comment by abelito75** [comment]
This is done
