### ISSUE TITLE
[Core] Weapon Enchants are good differing on a spec by spec basis

### ISSUE THREAD

**Issue by Pewtro** [WoWAnalyzer/WoWAnalyzer#4160]
Example: 
Optical Target Embiggener & Sinful Revelation are good for MM (depending on ST and AOE but probably not checking for that, so just say both are good) 
Infra-green Reflex Sight is the good one for Beast Mastery.

**Comment by joshinat0r** [comment]
I created a somewhat similar thing for DKs. [This](https://github.com/WoWAnalyzer/WoWAnalyzer/blob/shadowlands/src/parser/deathknight/shared/runeforges/RuneForgeChecker.tsx) is a generic checker that gets a [config](https://github.com/WoWAnalyzer/WoWAnalyzer/blob/shadowlands/src/parser/deathknight/blood/modules/core/RuneForgeChecker.tsx) from the specs.
Essentially going beyond the `Have a strong enchant on your weapon` and throwing a suggestion `Hey you should use enchant Y as Blood DK`. It's not in the checklist though, just a simple suggestion.

**Comment by Pewtro** [comment]
This was implemented as all scopes are good for both specs, since they're so close to each other - if the gap widens massively, I might need to add support for proper distinction
