### ISSUE TITLE
Marksmanship Hunter

### ISSUE THREAD

**Issue by sMteX** [WoWAnalyzer/WoWAnalyzer#418]
Please use this issue to discuss any suggestions, features or bugs for this spec. Let us know if you're doing something or plan on adding some feature.

Currently maintained by @Jlassie82 (@JLassie82 on WoW Analyzer Discord).

**Comment by Pewtro** [comment]
These are the things I propose together with the rest of the expert team on the hunter discord, as well as stuff I've talked with Jlassie about. If you're feeling up for working on any of the mentioned modules below, throw a comment to check on the current status on our own work on the modules, so we don't end up working double for no reason.

### Planned Modules
- [ ] Tier 20 2p utilization
- [ ] Aimed Shots inside/outside of vulnerarable
- [ ] Focus tracker
- [ ] Patient Sniper tracker
- [ ] Fix CD and CDR on trueshot
- [ ] Bullseye tracker, possibly count Bullseye as a cooldown?

#### Possible ideas
- [ ] Check for haste % and then check for rotational changes (marked shot -> 1x or 2x arcane -> 2x aimed fx)

##### Known Issues
- [ ] Trueshot showing less possible usages then actually used (resulting in stuff like 3/1 uses - 300% effectiveness)

**Comment by MartijnHols** [comment]
Add `DISENGAGE_TALENT` to cast efficiency, and it might also belong to ABC (if not because it's off the GCD, I'd still add it commented out with a comment stating it's off the GCD).

**Comment by Pewtro** [comment]
Addressed in latest PR
