### ISSUE TITLE
[Mistweaver Monk] Mana tea is displayed even when not talented

### ISSUE THREAD

**Issue by CasperKjaerhus** [WoWAnalyzer/WoWAnalyzer#4191]
Under statistics page , Mana Tea is displayed even though Spirit of the Crane is talented (and i imagine the same applies for the other talent) [Link to analyzer page](https://wowanalyzer.com/report/a:yAmXzfDgWcT3JadB/42-Mythic+Shriekwing+-+Kill+(6:46)/Player+(19)/standard/statistics)

![image](https://user-images.githubusercontent.com/56830573/102598904-0180b000-411d-11eb-8657-bf0159687fbe.png)
![image](https://user-images.githubusercontent.com/56830573/102598932-0b0a1800-411d-11eb-982d-2c9a276936ee.png)

**Comment by abelito75** [comment]
This isn't a bug. 
![Screenshot_20201218-084825](https://user-images.githubusercontent.com/25177817/102621668-e5294700-410d-11eb-8b96-4c3bbda307e6.jpg)
