### ISSUE TITLE
Page Crash

### ISSUE THREAD

**Issue by davep1553** [WoWAnalyzer/WoWAnalyzer#4220]
https://wowanalyzer.com/report/P7ZpbvM6gxWCDaRJ/2-Normal+Shriekwing+-+Kill+(6:12)
Click on Annei and the webpage and big page error pops up.

**Comment by Sharrq** [comment]
Just a heads up, it is crashing because you do not have a weapon equipped.

We will do what we can to stop it from crashing though

**Comment by Scotsoo** [comment]
Why do you not have a weapon equipped? 😂 
I've hopefully fixed this here: https://github.com/WoWAnalyzer/WoWAnalyzer/pull/4283
