### ISSUE TITLE
[Rogue] Shadow Dance Uptime Calculation

### ISSUE THREAD

**Issue by tyndivelspaz** [WoWAnalyzer/WoWAnalyzer#4222]
Double check the calculations. Cooldown reduced by 1 second for each finishing move combo point spent.

**Comment by hpabst** [comment]
From the looks of things we need to change some of these calculations. The current calculation is of a 1.5s CDR + 1s CDR if Enveloping Shadows is taken whereas the new calculation should for a 1s CDR + 0.5s CDR if Enveloping Shadows is taken.

**Comment by hpabst** [comment]
Updated within DeepeningShadows analyzer, will be put up for review in later PR.

**Comment by Magellol** [comment]
I was curious to know how it was being calculated. Often times during encounters, it suggests me to cast shadow dance more. I was curious to see how boss downtimes were taken into account. For instance on Destroyer, we have to inevitably run away when it does its AOE damage. During that time, Shadow dance might come off cooldown but I can't use it right away.

Here's an example of a report https://wowanalyzer.com/report/91k8yxnFDB2d3mwv/9-Heroic+Hungering+Destroyer+-+Kill+(5:51)/Ayae/standard — This is something I see very often on most of my reports. I'm not saying I do the best job at casting it all the time but I wanted to double check if something wasn't off about how we're calculating it.

**Comment by Pewtro** [comment]
Downtime is not taken into account.

**Comment by hpabst** [comment]
Resolved by #4371 .
