### ISSUE TITLE
[SUGGESTIONS] Symbols of Death should have been used as often as possible

### ISSUE THREAD

**Issue by tyndivelspaz** [WoWAnalyzer/WoWAnalyzer#4223]
Make sure this is properly accounted for in Suggestions section

**Comment by hpabst** [comment]
Confirmed that Symbols of Death usage efficiency is account for in suggestions:
![image](https://user-images.githubusercontent.com/6363390/104128638-10c2da00-5326-11eb-8586-a14bd470ae2b.png)
Suggestion is populated as a default spell suggestion in `rogue/subtlety/modules/Abilities.js`. As the treatment for `Symbols of Death` is to cast on CD, I think we can mark this as resolved with the current state.
