### ISSUE TITLE
[SUGGESTIONS] Shadow Dance Casts

### ISSUE THREAD

**Issue by tyndivelspaz** [WoWAnalyzer/WoWAnalyzer#4224]
Suggestion making sure there are 5 GCDs spent during Shadow Dance. 

Figure out how best to show this, possibly an average per Shadow Dance window

**Comment by hpabst** [comment]
Current version is definitely bugged, a sample log I've been using is reporting 140% cast usage in Shadow Dance:
![image](https://user-images.githubusercontent.com/6363390/104128308-1a4b4280-5324-11eb-8907-77dc0b9b31b7.png)
Sample log: https://www.warcraftlogs.com/reports/A67n9QN8VfwtJK1B/#fight=35&source=20

**Comment by hpabst** [comment]
Potential bug cause: Weaponmaster talent causes Shadowstrike and Backstab to have a 15% chance to hit the target twice on a cast. This results in multiple damage events per cast (See log slice [here](https://www.warcraftlogs.com/reports/A67n9QN8VfwtJK1B/#fight=35&source=20&type=casts&start=8516294&end=8524351)) which is not accounted for in DanceDamageTracker which is currently used to determine the number of casts made in ShadowDance.

**Comment by hpabst** [comment]
Performed more investigation and found that we were tracking cast events properly, but the `CastsInShadowDance` analyzer had failed to be updated for the new base max casts value of `8` rather than `5`. The analyzer has been updated accordingly and will be in a future PR.
