### ISSUE TITLE
[SUGGESTIONS] No Nightblade casts during Shadow Dance

### ISSUE THREAD

**Issue by tyndivelspaz** [WoWAnalyzer/WoWAnalyzer#4226]
If the Dark Shadow talent is selected

**Comment by hpabst** [comment]
We might want to confirm with the Ravenholdt discord regarding this suggestion. I don't believe that Nightblade still exists as an ability. @darthelit

**Comment by tyndivelspaz** [comment]
I'll confirm with them on all of the Sub suggestions. It was taken from a document made by the previous maintainer. I'll reach out and update.
