### ISSUE TITLE
[SUGGESTIONS] Sepsis

### ISSUE THREAD

**Issue by tyndivelspaz** [WoWAnalyzer/WoWAnalyzer#4233]
Use on cooldown without overcapping Combo Points. Use Ambush without overcapping as the use of an stealth ability granted when Sepsis runs out

**Comment by hpabst** [comment]
I will be taking on this suggestion.

**Comment by hpabst** [comment]
Confirmed the information with the Ravenholdt discord. Sepsis should be used on CD regardless of CB (as it does not generate any) and Ambush used as the stealth ability after the final dot proc.

I'll be dividing this into 2 Analyzers. One for the CD efficiency and the other for use of stealth abilities following the last Sepsis DoT proc.

**Comment by hpabst** [comment]
I misread, Sepsis does generate 1 CB but should be used on CD regardless.

**Comment by hpabst** [comment]
This has been resolved following #4477 being merged.
