### ISSUE TITLE
[SUGGESTIONS] Echoing Reprimand

### ISSUE THREAD

**Issue by tyndivelspaz** [WoWAnalyzer/WoWAnalyzer#4234]
- Use on Cooldown without overcapping Combo Points. Finish at the Animacharged Combo Point (either 2, 3 or 4 at random), but don’t try to force landing on the Combo Point.

- If using Pelagos Soulbind, collect Sorrowful Memories orbs to extend the Combat Meditation buff (not sure if this belongs here since it’s not outlaw specific but part of the soulbind)

**Comment by hpabst** [comment]
I will be taking on this suggestion.
