### ISSUE TITLE
[SUGGESTIONS] Blade Rush

### ISSUE THREAD

**Issue by tyndivelspaz** [WoWAnalyzer/WoWAnalyzer#4237]
- Single target: use only when under ~80 energy. Delay for up to 20 seconds if multiple targets are coming.
- Multi-target: use on cooldown when Blade Flurry is active.

**Comment by alex-bau** [comment]
I'll try and take a stab at this, looks like an easyish fix. Will try and send a PR later this week.

How would this be shown ideally? Esp for fights where phases switch between ST and AoE? (ex: Denathrius P2 vs P3, SLG add spawn)

I was thinking of having a few different trackers and displaying all if the fight is a mix and displaying some if it's AoE/ST. So something like:
if fight_aoe_time > 20%:
  You should be using BR on CD for AoE portions of the fight, your usage for these portions was Y%.
if fight_st_time > 20%:
  You wasted Z energy generated by BR. You should use BR for Energy Regen in ST scenarios.
  You spent X% of the fight under N energy while having BR active, try to cast it if you drop low in energy to be able to use your finishers and combo generators more often.

I'll ask on Ravenholdt what the logic would be for mixed fights: is it better to hold BR for AoE or just use it for Energy Regen if current_energy < some_number.
