### ISSUE TITLE
[SUGGESTIONS] Between the Eyes

### ISSUE THREAD

**Issue by tyndivelspaz** [WoWAnalyzer/WoWAnalyzer#4238]
- Use on cooldown. Normal finisher rules apply.

**Comment by alex-bau** [comment]
Is this suggestion still applicable? 
Going by the thresholds here https://github.com/WoWAnalyzer/WoWAnalyzer/blob/shadowlands/analysis/rogueoutlaw/src/modules/spells/BetweenTheEyes.tsx#L54-L65
And the tool tip here
https://github.com/WoWAnalyzer/WoWAnalyzer/blob/shadowlands/analysis/rogueoutlaw/src/modules/spells/BetweenTheEyes.tsx#L96-L99

It seems BtE is already recommended to be cast on CD. What other changes need to happen here?

**Comment by CasperKjaerhus** [comment]
Hi! This issue just hasn't been closed, but should've been with https://github.com/WoWAnalyzer/WoWAnalyzer/pull/4351 where that suggestion you mentioned was implemented
