### ISSUE TITLE
[SUGGESTIONS] Roll the Bones

### ISSUE THREAD

**Issue by tyndivelspaz** [WoWAnalyzer/WoWAnalyzer#4239]
- Use first Roll the Bones 1 Second before Pull (2 seconds if talented into Marked for Death)

- Reroll single True Bearing, Buried Treasure and Grand Melee as soon as possible.

- Reroll other buffs with 3 seconds left.

- In the current RTB implementation, unsure what exactly “low/mid/high value efficiency” is describing. The player either has to reroll ASAP, or they don’t, depending on what buffs are active. Perhaps track how long RTB was off cooldown when a single True Bearing, Buried Treasure or Grand Melee are active -- instances where they should have rerolled.

> Outdated script seems to work okay for the basic needs, but the buff priority had changed according to the following logic:
> 
> (cumulative value) ≤ 2 - recast
> (cumulative value) > 2 - wait out full duration
> 
> Broadside (BS) = 3
> True Bearing (TB) = 3
> Ruthless Precision (RP) = 2
> Skull and Crossbones (SC) = 2
> Buried Treasure (BT) = 1
> Grand Melee (GM) = 1
> 
> However, if Sleight of Hand conduit is being used, the values change to:
> 
> BS = 2
> TB = 2
> Rest stays the same
> 
> (This is because if using the conduit, we should always try to get 2+ buffs but not BT+GM)
-- @tomovka

**Comment by CasperKjaerhus** [comment]
It should be noted if you have the sleight of hand conduit you should always roll for 2 buffs no matter what 1-buff you get

**Comment by soloxcx** [comment]
> It should be noted if you have the sleight of hand conduit you should always roll for 2 buffs no matter what 1-buff you get

when this was tested by users in Ravenholdt, it seemed to be a gain for some profiles but a loss for others. So we generally didn't recommend it to people. I imagine if WoWAnalyzer started telling people to do that it might cause some confusion. I think in the future when we get higher Sleight conduit ranks, this may be a gain all the time but for now I would not implement it.

**Comment by tyndivelspaz** [comment]
Thanks for the updated comment. I will put this at the bottom of the list.

**Comment by alex-bau** [comment]
Sent https://github.com/WoWAnalyzer/WoWAnalyzer/pull/4461 which changes the prio and uses a cumulative instead of ifing between good buffs (and treating BT+GM the same as for ex S&C+RP)
