### ISSUE TITLE
No Major Issue is a Major Issue

### ISSUE THREAD

**Issue by rjalic** [WoWAnalyzer/WoWAnalyzer#425]
As the title suggests, no major issues is listed as a major issue.
Doesn't affect the log analysis it's just weird that it's showing it like that.

Link: https://wowanalyzer.com/report/rGJ4V17TcYxpdPHj/17-Mythic+Sisters+of+the+Moon+-+Kill+(8:00)/Notsogood/suggestions

Picture in attachment
![image](https://user-images.githubusercontent.com/24410431/31017459-d44f03b8-a528-11e7-8c58-c1acde570a9a.png)

Discord contact: Vanths#2567

**Comment by MartijnHols** [comment]
It was intended a silly joke, but I don't think it works :(

**Comment by rjalic** [comment]
Oh I see, could possibly put something that will make it more obvious that it's a joke then haha

**Comment by MartijnHols** [comment]
Thanks for the report, I just pushed a change that fixes this. It should been visible on the site in about 5 minutes.
