### ISSUE TITLE
error js code

### ISSUE THREAD

**Issue by deadka1313** [WoWAnalyzer/WoWAnalyzer#4251]
https://wowanalyzer.com/report/CX1xyz6GjBDRNckp/2-Normal+Sludgefist+-+Kill+(4:31)

**Comment by Scotsoo** [comment]
That link works for me, are you sure you linked the right page? More detail would be appreciated.

**Comment by abelito75** [comment]
I loaded this and all people on it. Imma close it but if it happens again please recreate the issue and give more detail
