### ISSUE TITLE
[Mistweaver Monk] Tier 45 vs Tier 30

### ISSUE THREAD

**Issue by NelsonMinar** [WoWAnalyzer/WoWAnalyzer#4252]
I'm a little confused by the code and language for the Mistweaver suggestions around "Correct Tier 45 Talent".

The code is called "Tier30Comparison.tsx" and is about Shadowlands tier 30 mana talents; Mana Tea, etc.

The language in the UI calls this "Tier 45". I think that may be a holdover from BfA when these talents were at level 45. So maybe all that needs to happen is the language is updated for Shadowlands to say "tier 30".

But I'm also still a bit confused by the report. I'm not seeing the suggestion "With your current playstyle you are not using the most effective tier 45 talent." even though I think I should be (see [here](https://wowanalyzer.com/report/YD7J9fqMTNVycmnw/4-Normal+Sludgefist+-+Kill+(4:50)/Flym/standard/overview)). Also it's talking about my Jade Serpent Statue, which is a tier 45 talent, not a tier 30 talent. I wonder if some of the suggestion calculation code needs to also be updated for the 45 to 30 change.

**Comment by abelito75** [comment]
Yup. looks like i missed 1 instance of 45 when converting it over to 30

**Comment by abelito75** [comment]
This should be fixed in like 20 minutes
