### ISSUE TITLE
Grammar Mistakes

### ISSUE THREAD

**Issue by lexxieblack** [WoWAnalyzer/WoWAnalyzer#4386]
Blooddrinker suggestion:

![image](https://user-images.githubusercontent.com/30494658/105853494-ad030700-5fdd-11eb-8472-2fb6b9a2c665.png)

"you're" and "can't". That's all :D

**Comment by TrellinXp** [comment]
Log to test https://www.warcraftlogs.com/reports/Kwry2Q7Tgn3pvYdx#fight=30&type=damage-done

**Comment by DylanDirlam** [comment]
Fixed by #4392
