### ISSUE TITLE
Add a "you died and were dead for x seconds" suggestion

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#443]
It could also check if the user had a CD available, and if he had used a Healthstone the fight. It might also be nice to suggest using abilities that might help (to point out the available CDs).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=49979110)](https://www.bountysource.com/issues/49979110-a-you-died-and-were-dead-for-x-seconds-suggestion?utm_source=49979110&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by janvavra** [comment]
this module should be able to be to deal with or be disabled on Antorus final boss fight (multiple deaths are part of the encounter design)
