### ISSUE TITLE
Auto select right fight & player if this is provided in the URL

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#444]
Currently we only extract the report code from WCL URLs, picking up the fight id and player id could make importing even easier.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=49980158)](https://www.bountysource.com/issues/49980158-auto-select-right-fight-player-if-this-is-provided-in-the-url?utm_source=49980158&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by awlego** [comment]
Opened a PR for this issue. See https://github.com/WoWAnalyzer/WoWAnalyzer/pull/729.

**Comment by Pewtro** [comment]
Pretty sure this is already being done?

**Comment by awlego** [comment]
Yes I did it a while ago. There in an upgrade to it that puts their name in
the URL instead of the player ID, but the actual auto selection is done.

-awlego / gao
