### ISSUE TITLE
Discord webhook: respond to WCL links with a link to the analyzer

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#445]
I guess this would require a server-side bot, so this should probably be done as a separate Docker container.

Related: #444

**Comment by JoshYaxley** [comment]
If it helps, here's the source code for the Wipefest bot that does pretty much the same thing: https://gist.github.com/JoshYaxley/055b9f3c2ffc2e55be55cc89607157d8 

The code isn't representative of my usual standards because I threw it together rather quickly ;)

.Net Core. I'm currently running it on my Raspberry Pi.

**Comment by MartijnHols** [comment]
Thanks, that looks very useful! 👍

**Comment by MartijnHols** [comment]
If someone does end up implementing a Discord bot, please note that it should be done with JavaScript (preferably ES6) so we use the same language across the entire project. The example above acts as a good example of how to implement it, but we'd obviously need a different library to interact with Discord.

**Comment by fasib** [comment]
Here is a simple `discord.js` bot (https://discord.js.org/)
`yarn add discord.js` or `npm install --save discord.js`

```js
const Discord = require('discord.js')
const client = new Discord.Client()

client.on('ready', () => {
  console.log(`Logged in as ${client.user.tag}!`)
})

client.on('message', msg => {
  const content = msg.content
  // TODO: create a group for the # part of the WCL URL
  const match = content.trim().match(/^(.*reports\/)?([a-zA-Z0-9]{16})\/?(#.*)?(.*)?$/)
  if (match && match[2]) {
    // TODO: filter for fight=XX and source=XX for #444
    msg.channel.send(`https://wowanalyzer.com/report/${match[2]}`)
  }
})

client.login(process.env.DISCORD_TOKEN)

```

**Comment by MartijnHols** [comment]
Thanks @fasib that helped a great deal. Never expected it to be this easy, expected to have to summon a bot for every single server 😱 but this is much easier.

Progress is visible in https://github.com/WoWAnalyzer/WoWAnalyzer/tree/master/DiscordBot. I won't be running the bot much outside of development, and it will need some more work before it's considered finished. I'll close this issue once it will be on 100% of the time.

I want to at least add:
- [ ] Fetch fight list from the API (our API so it gets cached/uses cache)
- [ ] When a fight is selected in the WCL link show fight name in the returned link (e.g. `14-Mythic+Sisters+of+the+Moon+-+Kill+(7:02)`
- [ ] When a player is selected show player name in the returned link
- [ ] Run it in a docker container, preferably with a new docker tag that also auto relaunches upon app update (or reconsider this; bot might desire higher uptime)

Adding the bot can be done with this link, but it will be off most of the time for now.
https://discordapp.com/oauth2/authorize?&client_id=368144406181838861&scope=bot&permissions=3072

**Comment by MartijnHols** [comment]
It's now live: https://github.com/WoWAnalyzer/DiscordBot

Thanks everyone!
