### ISSUE TITLE
Outlaw Rogue Improvements suggest incorrect roll the bones values 

### ISSUE THREAD

**Issue by NicholasWSmith** [WoWAnalyzer/WoWAnalyzer#4462]
"Your efficiency with refreshing  Roll the Bones after a low value roll could be improved.  Ruthless Precision and  Grand Melee are your highest value buffs from  Roll the Bones. If you roll a single buff and it's not one of the two highest value, try to reroll it as soon as you can."

But the wowhead articles and high level outlaw rogue players say different things.

**Comment by alex-bau** [comment]
https://github.com/WoWAnalyzer/WoWAnalyzer/issues/4239 Known issue, have an active PR that aims to fix it.
