### ISSUE TITLE
[BM Monk] Gift of the Ox Healing not correctly reporting orbs consumed with expel harm

### ISSUE THREAD

**Issue by nicholasRutherford** [WoWAnalyzer/WoWAnalyzer#4480]
From[ this example](https://wowanalyzer.com/report/7ZwWpynfCtRaQMTA/8-Normal+Sludgefist+-+Kill+(4:35)/Poro/standard/statistics) it says:

> You generated 29 healing spheres and consumed 28 of them, healing for 94k. **0 of these were consumed with Expel Harm** over 4 casts.

I don't know what the correct number of orbs consumed with Expel Harm was, but I'd wager it was more than 0! :stuck_out_tongue: 

Screenshot:
![image](https://user-images.githubusercontent.com/4751193/116166818-a3a83a00-a6b3-11eb-81ca-9d361505a301.png)

**Comment by Carglass** [comment]
After discussion on Discord, I am working on a fix, and I proposed a PR #4510

**Comment by DylanDirlam** [comment]
Fixed in #4510
