### ISSUE TITLE
nelts cast efficiency 

### ISSUE THREAD

**Issue by tankzalot** [WoWAnalyzer/WoWAnalyzer#449]
Thanks for reporting a new issue, it's much appreciated!

The following questions might help achieve a faster resolution, but you're in no way required to answer any them. Please remove this text and any questions you don't deem relevant.

 - What browser are you using? (if experiencing a bug)
 - What spec?
 - Link to an example report with the issue
 - What's your Discord nickname? (if we can contact you on our Discord server)
 - Expected behavior

chrome
prot
https://imgur.com/cyXUppw pic of the site showing 0 casts
https://www.warcraftlogs.com/reports/3J9QqhB2xPWvfjdn#view=analytical&type=damage-done&source=5 log of the fight showing 4 casts

gaarashatan

should have nelts cast time in there, perhaps an id issue. as well as have it play time into shield block if shield block is down, and add vengenance weaving

**Comment by sMteX** [comment]
Moved the issue to the Protection Warrior thread (#402) to keep it in one place, closing this issue.
