### ISSUE TITLE
[Demonology] Wrathguard's Wrathstorm is not correctly shown in suggestions

### ISSUE THREAD

**Issue by NicoMF** [WoWAnalyzer/WoWAnalyzer#450]
- What spec?
 Demonology Warlock

- Link to an example report with the issue
https://wowanalyzer.com/report/nq3xNQ98yPtD21p7/12-Mythic+Sisters+of+the+Moon+-+Wipe+10+(5:55)/Kaezzu#spec-information

 - What's your Discord nickname? (if we can contact you on our Discord server)
Kaesu#2600

 - Expected behavior
Wrathguard's Wrathstorm should be equal to Felguard's Felstorm in the suggestions as it is in practice (Wrathguard Glyph is just cosmetic)
---

I'll support the issue with images:

- Suggestions recommending to use Felstorm: https://imgur.com/NsAkssM

- Log showing Wrathstorm usage: https://imgur.com/1OKIoJB

---
Thank you for your work

**Comment by sMteX** [comment]
Thank you for using the tool and thanks for very detailed issue :) I've run into this myself and it's an issue I already know (see #386), just didn't get to fix it yet.

**Comment by NicoMF** [comment]
Oooh sorry for being redundant, I just made a quick search in the current issues, I hope I can give you a hand soon, I'm getting started with js in class

**Comment by sMteX** [comment]
Any suggestions regarding the analyzer (not just Demo, other specs as well) are welcome, i.e. new features, changes to existing features, any feedback is appreciated :)
