### ISSUE TITLE
Disciplinary Command during Combustion

### ISSUE THREAD

**Issue by castsaku** [WoWAnalyzer/WoWAnalyzer#4515]
Just ran an analysis on my fire mage log, and it seems like it's telling me to do something I'm doing

![chrome_1fIpRpQvKp](https://user-images.githubusercontent.com/33944728/119765567-88cb1000-be81-11eb-9feb-534952f06c4f.png)

You had the buff from  Disciplinary Command up for 100% of your  Combustion. In order to get the most out of  Disciplinary Command you should ensure that you are triggering it with your  Combustion cast, or within a couple seconds before, so that it is up for the entire duration of  Combustion.

100% Buff Uptime During Combustion (100.00% is recommended)

**Comment by DylanDirlam** [comment]
Could you link the log you're seeing this on? I tested it with one with 100% usage and it didn't display so using the log you have would be helpful. Thanks!
