### ISSUE TITLE
[TBC] Fix mapping for spell 31842

### ISSUE THREAD

**Issue by snowhorn** [WoWAnalyzer/WoWAnalyzer#4605]
The tooltip correctly maps the TBC spell 31842 to https://tbc.wowhead.com/spell=31842/divine-illumination, but other components use https://wowanalyzer.com/i/spell/31842, which incorrectly returns Avenging Wrath:

![image](https://user-images.githubusercontent.com/91165942/134789532-11a55d01-e58b-4fd5-a9c4-de8d61b5ea51.png)

**Comment by abelito75** [comment]
It appears that the checklist has changed to remove this so Its not longer reproduceable. Closing
