### ISSUE TITLE
Garrote uptime% statistic is miscalculated when reapplied early

### ISSUE THREAD

**Issue by calummitchell** [WoWAnalyzer/WoWAnalyzer#4737]
Garrote (https://www.wowhead.com/spell=703/garrote) is an 18 second bleed. It's common to reapply this bleed before it has expired during it's pandemic window (<= 30% of total duration remaining). Garrote uptime% statistic is miscalculated when reapplied early.

Here's an example of Garrote expiring before being reapplied. If you put this into WoWAnalyzer and filter to the first 30 seconds of the fight, the uptime% statistic matches warcraftlogs.
https://www.warcraftlogs.com/reports/cqYxMj6f2h7pXTvF#fight=5&type=auras&spells=debuffs&hostility=1&source=119&target=95&start=11875023&end=11905063&ability=703

Here's an example of Garrote being reapplied early. If you put this into WoWAnalyzer and filter to the first 30 seconds of the fight, the uptime% statistic (48%) is different from warcraftlogs (87%).
https://www.warcraftlogs.com/reports/81qazrCLNZt3vThd#fight=1&type=auras&spells=debuffs&hostility=1&target=8&start=378948&end=408998&ability=703

Rupture doesn't have this problem.

**Comment by emallson** [comment]
Interesting. Both should be using shared uptime trackers for that stat but maybe they don't 🤔
