### ISSUE TITLE
General Updates for Patch 9.2

### ISSUE THREAD

**Issue by emallson** [WoWAnalyzer/WoWAnalyzer#4753]
- [x] Add boss images
- [x] Bump current patch
- [x] Bump spec supported versions (where applicable)
- [x] Update current zone
- [x] Add a wiki page describing the steps to do this.

**Comment by abelito75** [comment]
You know what would be great to do while we do this?
Document it so in the future new people can do it if something happens to us

**Comment by emallson** [comment]
Added to the list :+1:

**Comment by emallson** [comment]
new wiki page for patch support TODOs: https://github.com/WoWAnalyzer/WoWAnalyzer/wiki/New-Patch-Checklist
