### ISSUE TITLE
Enhancement shaman showing 'cheap weapon enhancement'

### ISSUE THREAD

**Issue by kedearian** [WoWAnalyzer/WoWAnalyzer#4782]
https://wowanalyzer.com/report/GrdjhBnxXbwqF6vW/13-Normal+Dausegne,+the+Fallen+Oracle+-+Kill+(3:41)/Zeashaman/standard

example, it's showing that windfury/flametongue are cheap enhancements. This should hopefully be a easy fix.

**Comment by danny-janse** [comment]
I believe this issue was resolved back in april. I have yet to run into this issue myself.

**Comment by ToppleTheNun** [comment]
This issue should be able to be closed; the linked report is showing as not cheap.
