### ISSUE TITLE
Stormstrike Ability Set as Spell Object Instead of Spell ID

### ISSUE THREAD

**Issue by ausmat** [WoWAnalyzer/WoWAnalyzer#4803]
The spell field in `Abilities` for Stormstrike is passed the entire spell object instead of just the spell IDs.

![image](https://user-images.githubusercontent.com/7423873/159801867-226db611-0d84-42ab-8060-2db228a3ff57.png)

https://github.com/WoWAnalyzer/WoWAnalyzer/blob/5d2ed2cd3f8af2f3c28b38e8e9b75c427dacb3b9/analysis/shamanenhancement/src/modules/Abilities.tsx#L102

https://github.com/WoWAnalyzer/WoWAnalyzer/blob/eab44f978368210cc65aec9e3a41200c785896e4/analysis/shamanenhancement/src/constants.tsx#L3

**Comment by abelito75** [comment]
Pushing a fix in a few minutes
