### ISSUE TITLE
[core] Prepull haste rating buffs are double counted

### ISSUE THREAD

**Issue by kfinch** [WoWAnalyzer/WoWAnalyzer#482]
There is a bad interaction between the Haste module and the ApplyBuffFixer module. **Haste rating buffs that are applied prepull will be double counted because they will be present in both base haste rating from combatantinfo and in the fabricated applybuff events pulled from combatantinfo.** I don't think this is as simple as making Haste ignore events with `__prepull`, because then haste _percentage_ buffs applied prepull won't be handled at all. It seems likely that haste rating and haste percentage buffs should be handled differently.

I don't yet have hard proof of this, but it looks to be the case from the code.

**Comment by MartijnHols** [comment]
I removed the usage of combatantinfo, so I am unsure where else it would double count.

**Comment by kfinch** [comment]
Unless I misunderstand something, we get the player's base haste from the value in combatantinfo, but that value is actually whatever the player's haste rating was at the moment of pull. If the player uses a prepull haste rating buff, the power of that buff will be applied once as part of base haste, then applied again from the fabricated applybuff. Obviously this only affects haste rating buffs hard coded in the Haste module

**Comment by MartijnHols** [comment]
Yes, haste rating buffs are poorly supported. Luckily we don't have many of them so the issue is minimal (doesn't mean we don't have to fix it).

**Comment by kfinch** [comment]
Yeah this is a super edge case right now. Will probably end up fixing as part of "current stat rating" module I intend to implement as part of stat weights generator

**Comment by MartijnHols** [comment]
That was what I was hoping for as well.
