### ISSUE TITLE
"Something went wrong talking to warcraft logs"

### ISSUE THREAD

**Issue by oBusk** [WoWAnalyzer/WoWAnalyzer#4826]
On page https://wowanalyzer.com/character/EU/Daggerspine/Basically/ when hitting refresh.

> 500: <div class="content"> <div class="title">Something went wrong.</div> <div class="subtitle">Error ID: d0f6dad148f6404e8bd86e8529b4da3d</div> <script src="https://browser.sentry-cdn.com/5.15.5/bundle.min.js" integrity="sha384-wF7Jc4ZlWVxe/L8Ji3hOIBeTgo/HwFuaeEfjGmS3EXAG7Y+7Kjjr91gJpJtr+PAT" crossorigin="anonymous"></script> <script> Sentry.init({ dsn: 'https://7179b9a9ce164f589c5164e28aae2880@o140143.ingest.sentry.io/609878' }); Sentry.showReportDialog({ eventId: 'd0f6dad148f6404e8bd86e8529b4da3d' }); </script> </div>

Been like this for a few days now.

**Comment by oBusk** [comment]
So the wclogs api is failing for my character if you set `includeCombatantInfo=1`. Created [a post in the forum](https://forums.combatlogforums.com/t/parses-characer-api-error/12680/1) but it got anti-spammed. We'll see if it's allowed.

**Comment by abelito75** [comment]
I no longer see this error happening nor can I find the character on WCL at all so I'm going to close the ticket
