### ISSUE TITLE
[VDH] [Conduits] Viscous Ink

### ISSUE THREAD

**Issue by ljosberinn** [WoWAnalyzer/WoWAnalyzer#4844]
want to show (especially in contrast to Shattered Resto) how much damage viscous ink prevents. this is a bit more involved likely, since vers will play a role (esp with blind faith)

- base magic mitigation is 20%
- ink is additive to these 20%, max rank being 12% => 32% reduced
- ink = `0.06 + (rank - 1) * 0.05 + (empoweredConduits ? 0.01 : 0)`

damage ink would have mitigated = damage taken - damage taken * ((0.8-ink) * (1 - vers% / 2)) / (0.8 * (1-vers%/2))

if you have ink:
damage ink mitigated = damage taken * (0.8 * (1- vers%/2)) / ((0.8 - ink) * (1 - vers% / 2)) - damage taken

https://canary.discord.com/channels/213770335735119873/660181958155960340/961669587982762055 for more context

**Comment by ljosberinn** [comment]
fwiw, this might as well return in some form as Fel Flame Fortification is a fairly similar talent in DF so the dmg calculation might be relevant for @ToppleTheNun ? 🤷‍♂️

**Comment by ToppleTheNun** [comment]
Appreciate the callout, I'll definitely look into it for the current #5084.
