### ISSUE TITLE
Sephuz secret bug

### ISSUE THREAD

**Issue by buimichael** [WoWAnalyzer/WoWAnalyzer#490]
![Image](https://cdn.discordapp.com/attachments/315246361916473362/367511620819091458/sephu.png)

https://www.wowanalyzer.com/report/QZytn8d2Tx3BJX64/18-Mythic+Mistress+Sassz%27ine+-+Kill+(6:04)/Bastas

**Comment by kfinch** [comment]
Oh god our sephuz module is still that custom thing that makes up a number. My preferred solution here is to delete our version and use the core version, FYI.

**Comment by buimichael** [comment]
Sounds like a solid solution

**Comment by buimichael** [comment]
Looking more closely, the current core sephuz simply displays uptime, this says nothing to the user regarding performance/throughput of the legendary, this is especially important when comparing to other legendaries. The core module also ignores the 2% passive haste.

My proposed solutions:
1. Fix the bug and keep it as is, and show throughput based that 1 haste = 1 int. 
2. Fix the bug but instead of showing throughput, show average haste gained from it.
3. The ultimate would be to have stat weights implemented, this way we could show a more accurate throughput %.

**Comment by MartijnHols** [comment]
`My proposed solutions` which would you choose?

**Comment by kfinch** [comment]
I like #2 best, show average percent haste gained, uptime in tooltip. Honestly that sounds like a good enhancement to core module.

**Comment by buimichael** [comment]
I'd remove the resto druid sephuz module, and improve upon the core module to show uptime and average haste gained (including the passive haste).

**Comment by kfinch** [comment]
Sounds like we're in agreement. You want to implement or should I?

**Comment by buimichael** [comment]
You may take it :)
