### ISSUE TITLE
Readme - docker image

### ISSUE THREAD

**Issue by danny-janse** [WoWAnalyzer/WoWAnalyzer#5010]
Small issue with the readme; The docker image is 'missing'. Im not sure how to best replace this to avoid this issue in the future.

![image](https://user-images.githubusercontent.com/3527340/180997444-2d743afb-d21e-4f3b-9e2e-f457232a6bd7.png)

**Comment by Pewtro** [comment]
Fixed in 10882802e190140d02537520bf4464f17fff40bd

It now uses an image from https://www.docker.com/company/newsroom/media-resources/
