### ISSUE TITLE
Enhancement Shamen - 9.2.7 Project

### ISSUE THREAD

**Issue by danny-janse** [WoWAnalyzer/WoWAnalyzer#5011]
This is more of a project rather than an issue for the things i'll be working on for the Enhancement Shaman analysers. They will not be on order and this might get updated along the way. 

The aim is to work this spec towards 9.2.5 compatibility, If you have any suggestions feel free to drop a comment below.

- [ ] Update `Elemental Blast` to display correct uptime information.
- [x] Support `Haste` gained from `Elemental Blast`.
- [x] Initial Single Target APL Check
- [ ] APL CHeck optimized based on feedback
- [ ] Remove `filler Flame Shock` casts from `bad Flame Shock` casts (enhancement only)
- [ ] Suggestions for bad rotational priority
- [ ] Integration Tests

**Comment by danny-janse** [comment]
Hi @Seriousnes i believe you're primairly working on the Enhancement Shaman spec now. You recon we can close this issue?

**Comment by Seriousnes** [comment]
Yeah I don't think any of these apply any more, or are resolved.

**Comment by danny-janse** [comment]
Awesome, will close this issue then.
