### ISSUE TITLE
How to determine distance-moved information

### ISSUE THREAD

**Issue by spacct** [WoWAnalyzer/WoWAnalyzer#5026]
Hi I'm trying to understand how distance moved (as seen on timeline) is determined from the log.

**Comment by danny-janse** [comment]
Hey Spacct, You followed this up with the same question over on the discord's #support channel.
To summarise @Pewtro answer; Distance is calculated from X and Y coordinates from certain events read through the WCL API. 

The specific event types are; `cast`, `heal` (On Heal received), `damage` (on damage taken) ,`resourcechange` (eg; Mana)

An example of such an event passed through the api;

```json
{
  "timestamp": 1271053,
  "type": "cast",
  "sourceID": 2,
  "sourceIsFriendly": true,
  "targetID": 151,
  "targetIsFriendly": false,
  "ability": {
    "name": "Distracting Shot",
    "guid": 27020,
    "type": 64,
    "abilityIcon": "spell_arcane_blink.jpg"
  },
  "fight": 14,
  "resourceActor": 1,
  "classResources": [
    {
      "amount": 8473,
      "max": 8473,
      "type": 0,
      "cost": 140
    }
  ],
  "hitPoints": 100,
  "maxHitPoints": 100,
  "attackPower": 3357,
  "spellPower": 0,
  "armor": 9257,
  "x": -93548,
  "y": 172888,
  "facing": -541,
  "mapID": 335,
  "itemLevel": 149
}
```

If you'd like to dig into the code responsible for the calulations I recommend you checkout [the DistanceMoved module](https://github.com/WoWAnalyzer/WoWAnalyzer/blob/shadowlands/src/parser/shared/modules/DistanceMoved.tsx)
Feel free to ask any follow up questions.

**Comment by Pewtro** [comment]
Closing as it has been answered 👍🏼
