### ISSUE TITLE
Possibility to download multiple character images at once

### ISSUE THREAD

**Issue by TuulaP** [WoWAnalyzer/WoWAnalyzer#5044]
Is there way to download the character image of all players of certain log? Via character page it succeeds individually, but is there any bulk operation available or api to use ?

**Comment by danny-janse** [comment]
To be quite frank, WoWAnalyzer isnt a tool to download chatacter images and i'm uncertain where you'd need this exactly aside from the [Player Selection View](https://wowanalyzer.com/report/XcL31MkZGNDw8jzx/8-Mythic+Anduin+Wrynn+-+Kill+(9:22)) (see link for example)

The link of these avatar thumbnails are provided to use via the reports of WCL. I recommend you checkout [their api](https://www.warcraftlogs.com/v1/docs/)

**Comment by TuulaP** [comment]
ok, thank you for info.
