### ISSUE TITLE
What to do with mega objects ITEMS and SPELLS?

### ISSUE THREAD

**Issue by sMteX** [WoWAnalyzer/WoWAnalyzer#5050]
There has been a discussion over the items, provoked by PR #5041. For the discussion to not get lost in #development, I'm starting this issue.

Known issues and why it's a good idea to figure something out with it:
- while the referenced PR managed to strongly type the objects (so now the autocompletion offered by IDEs should work), *indexing* the object is quite simply a nightmare (pressing Ctrl + Space on `SPELLS` takes me upwards to several seconds)
- specific modules (**not** core ones) rarely need to have reference to any kind of spells, usually just a tiny subset (e.g. spec/class spells, or just dungeon trinkets etc.)
- additional properties like `icon` or `name` are also very rarely used (mostly for UI components like `SpellLink` or debugging reasons (`debug && console.log(SPELLS[spellId].name)`))
- indexing by ID itself is also seldom used (few modules use that, but it can be refactored to a local `Spell[]` of those concerned spells, and indexing just a few objects, instead of 3000+), but is still quite often in core modules

Mainly a few ideas I get regarding this, feedback is welcome:
- spec modules should be fine with importing just a subset of SPELLS/ITEMS they need (`import SPELLS from 'common/SPELLS/druid'`)
- I think we should also be fine with even removing the objects themselves and moving to spell IDs only as that is usually enough
    - if additional properties are needed (like `manaCost`, `effectId` for enchants), I think a separate exported object should be pretty clear 
    ```ts
    const manaCosts = { 
      [SPELLS.VIVIFY]: 1500, 
      ... 
    } as const;
    export default manaCosts;
   ```
- for those few places where getting name/icon just by spell ID without any knowledge of what it could be (so for core modules), maybe we can use some external API for that? `SpellLink` already has a fetch for that kind of info (but primarily uses `SPELLS` still, while it's fetching in the background)

**Comment by sMteX** [comment]
Copying @emallson's thoughts from Discord:

> - splitting SPELLS is good, progress on that is desireable
> - we effectively never use the name/icon data from SPELLS except when debugging locally, so I could see us dropping it.
> - switching the type ffrom Spell to number would be a loss
> - pulling spell data from dbc would be awesome, but likely hard to effectively integrate into the build process

**Comment by emallson** [comment]
So my thinking right now is that we commit to spec-level spells files for DF. I would like to continue to have a distinct `Spell` type that can be distinguished from `number` for typechecking purposes. TypeScript doesn't do opaque newtypes, but we can do [this](https://www.typescriptlang.org/play?#code/MYewdgzgLgBFCGBzAXDArmAlgRzQUxggE8BbAIxABsYBeGAZVIsoAoAiCABz0srYEoA3AChheAB6cQAJ1hQi3GACF4EPPW69aMAN7CYBmJgAmqMGnJ5pIwzDDwSeAPypo0zGEQ3DmUGBeEUO6eIgC+ImKSMnIKBBo8lAA8ACowElB4YMYQyqrqmtR0KmrxvAB82qkAZLr6htJ48MbglEQwAPrtCChwsSAAZnBIYaLyigCqYN2IeMalSanpmdkMBYnwYEQVdPPbMADyJJhQKQA0MADknd0XZRGRUrIw-RjAUJjghAUsJmYWZFZ+Kh5iIJI9YC8wG8PmAvgkUmlxBksjlivkEmUflh3vBKJgAF5WVDJIGreHJO6iMHRZ6vd6fLjkxHIlZo3ZY46YXEEol2f5WGAAHxgJOBawpQrJWj0tkwgxYYzwAyM2K5eMJ0loNDoF3MlmkF34tVstgaUDQ0lhMpNNt+Ks53I1pzqNts1yQqG6ztdMHCLt9aUoamNrrNFqtMAAdNGPA71VZzu6et1fd4DKFhBnhAB6bP2nHxmDwOFafrSEAkOAACwIJgeNL80BgAGkAKIAcXa9AAsgBBegACW0jN4LAAjAAmScAVgAzEIc3mZOgIB5EEWS9QQGQAFZ4N71p6N2DJACS7dbACV2gAFXsAGW7w++1oMdrHAAYPwB2AAcH+9Qx7EcVALmSTAZk1G9cRIC5ALfPxQPgMhMDxeR2hIcAAGsuggqxOBguDMwXRdq0wHIAHdUOoTgGjUaQADcCAgNAyEVCBzn6ZcJAcThKDwZBhEVGBWyhKsNlgIo8nmGAalfNIxIk08ABE-n1MIImPBTgHEqZn3hUSdIkylhC0+hTwAOQAMXGe92kvVsADVtEyIyphYeS7VnCcABYJwANgA-1XN0qAVNQfyJwnX9nVCEitMc09EqsgBNfTR080wYDHMd-P878gtsEgNngABhEBoFQD9Iw-WdfxgAAqGBpy-L9YoXIA):

```ts
const tag: unique symbol = Symbol("spell");

export type BaseSpell = {
    id: number;
    name?: string;
    icon?: string;
};

export type Spell<T extends BaseSpell = BaseSpell> = T & {
    readonly __tag: typeof tag;
}

type UntaggedSpell<T extends Spell<any> = Spell> = Omit<T, '__tag'>;


export function spell(id: number): Spell;
export function spell<T extends BaseSpell>(initializer: T): Spell<T>;

export function spell<T extends BaseSpell>(initializer: number | T): Spell<T> | Spell {
    if (typeof initializer === 'number') {
        return {
            id: initializer,
            __tag: tag,
        };
    } else {
        return { ...initializer, __tag: tag };
    }
}

// initialize a spell from the id
export const KEG_SMASH = spell(121253);
// or using a spell object
export const TIGER_PALM = spell({
    id: 100780,
    name: 'Tiger Palm',
    icon: 'ability_monk_tigerpalm',
});

// this will preserve subtypes, for example:
type Enchant = BaseSpell & {
    enchantID: number;
};

const enchant = spell<Enchant>;

const SINFUL_REV = enchant({
    id: 324260,
    enchantID: 6228,
}); // type: Spell<Enchant>

const VIVIFY = spell({
    id: 116670,
    manaCost: 0.038 * 50000,
});
```

The `__tag` field pushes people towards using the `spell` constructor rather than directly using objects or ids. My reasoning for that is that this spell constructor could later be used to build database lookup for spells based on the parameter to autofill any relevant properties.

What this accomplishes then is:

1. We move entirely off of the massive SPELLS objects even within a spec, and instead mostly have `export const MY_SPELL = spell(id);`
2. The resulting values are typed as spells. The `Spell` (and `Spell<Foo>`) types can be used as parameter types, etc safely.
3. This sets us up to later build something that uses the parameter here and does more than just apply the `__tag` field, whether that is looking up other spell properties from a DB or something else.

**Comment by Sharrq** [comment]
I like it. 👍

**Comment by ToppleTheNun** [comment]
I concur with emallson's proposal. I also think we should recommend a consolidated spells file per spec with individual exports. Having all of the spells defined together is useful instead of spreading them out throughout a spec's files. Example with the file structure from #5049:

```typescript
// src/analysis/demonhunter/havoc/spells.ts
import { spell } from "...";

export const CHAOS_STRIKE = spell(162794);
export const CHAOS_STRIKE_MH_DAMAGE = spell(222031);
export const CHAOS_STRIKE_OH_DAMAGE = spell(199547);
export const ANNIHILATION = spell(201427);
// ...
```

**Comment by Sharrq** [comment]
Yea I think one per spec plus one for class stuff in the class shared

Alternatively if a spell was only relevant for one module you could just define it there I suppose

**Comment by MartijnHols** [comment]
@sMteX thanks for this issue!

> So my thinking right now is that we commit to spec-level spells files for DF. I would like to continue to have a distinct `Spell` type that can be distinguished from `number` for typechecking purposes. TypeScript doesn't do opaque newtypes, but we can do [this](https://www.typescriptlang.org/play?#code/MYewdgzgLgBFCGBzAXDArmAlgRzQUxggE8BbAIxABsYBeGAZVIsoAoAiCABz0srYEoA3AChheAB6cQAJ1hQi3GACF4EPPW69aMAN7CYBmJgAmqMGnJ5pIwzDDwSeAPypo0zGEQ3DmUGBeEUO6eIgC+ImKSMnIKBBo8lAA8ACowElB4YMYQyqrqmtR0KmrxvAB82qkAZLr6htJ48MbglEQwAPrtCChwsSAAZnBIYaLyigCqYN2IeMalSanpmdkMBYnwYEQVdPPbMADyJJhQKQA0MADknd0XZRGRUrIw-RjAUJjghAUsJmYWZFZ+Kh5iIJI9YC8wG8PmAvgkUmlxBksjlivkEmUflh3vBKJgAF5WVDJIGreHJO6iMHRZ6vd6fLjkxHIlZo3ZY46YXEEol2f5WGAAHxgJOBawpQrJWj0tkwgxYYzwAyM2K5eMJ0loNDoF3MlmkF34tVstgaUDQ0lhMpNNt+Ks53I1pzqNts1yQqG6ztdMHCLt9aUoamNrrNFqtMAAdNGPA71VZzu6et1fd4DKFhBnhAB6bP2nHxmDwOFafrSEAkOAACwIJgeNL80BgAGkAKIAcXa9AAsgBBegACW0jN4LAAjAAmScAVgAzEIc3mZOgIB5EEWS9QQGQAFZ4N71p6N2DJACS7dbACV2gAFXsAGW7w++1oMdrHAAYPwB2AAcH+9Qx7EcVALmSTAZk1G9cRIC5ALfPxQPgMhMDxeR2hIcAAGsuggqxOBguDMwXRdq0wHIAHdUOoTgGjUaQADcCAgNAyEVCBzn6ZcJAcThKDwZBhEVGBWyhKsNlgIo8nmGAalfNIxIk08ABE-n1MIImPBTgHEqZn3hUSdIkylhC0+hTwAOQAMXGe92kvVsADVtEyIyphYeS7VnCcABYJwANgA-1XN0qAVNQfyJwnX9nVCEitMc09EqsgBNfTR080wYDHMd-P878gtsEgNngABhEBoFQD9Iw-WdfxgAAqGBpy-L9YoXIA):

I think that's a very nice solution. I still prefer `number` as I really like working with basic types as they make everything simpler (it leads to reduced complexity), but this would work nicely nonetheless.

**Comment by Pewtro** [comment]
@emallson Is there a reason to not go with something as simple as what I did for the talents? 

```typescript
type EnforceObjectType<T> = (v: T) => T;

export interface Talent extends Spell {
  maxRanks: number;
  //These three are currently not exported in the script - but they could be if we deem the information necessary
  reqPoints?: number;
  talentType?: ClassNodeType;
  spellType?: EntryType;
}

export const createTalentList: EnforceObjectType<{ [key: string]: Talent }> = (v) => v;
```

It could simply be 
```typescript
export const createSpellList: EnforceObjectType<{ [key: string]: Spell }> = (v) => v;
```

Then you simply do: 
```typescript
//class spells file (or spec, whichever really)
const spells = createSpellList({ 
  //... spells, with/without icon/name if that's important since they're optional in your type
  //Bloodworm summon spell by the Bloodworms talent
  BLOODWORM: {
    id: 196361,
    name: 'Bloodworm',
    icon: 'spell_shadow_soulleech',
  },
  //Bloodworm death/heal spell
  BLOODWORM_DEATH: {
    id: 197509,
  },
}); 

export default spells; //now accessible by default as this class/specs spells 
export {spells as SPELLS_CLASS/SPEC}; // can be grouped together with the other spells if necessary
```
having to write const = something or export const = something for every single spell is a lot of unnecessary boilerplate to me. 
It's very easy to create a new "type" of list too, as you simply make a new createXList function taking in the type that's necessary (Enchants, Items, whatever) and use that 

[Playground of my proposal. 
](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoAcIBsvIN4BQyywAJgFzIgCuAtgEbQDcRVctEA-JQM5hSgA5i2LAEAexDdkfASGEEAvgQKhIsRCgAqcLBHDIIAD0ghSPNJhz5WtOEYBKcEAGselGg2ZKVYAJ6YyACiIDDiUEgA8vQAVhAIYFoBEAA8WgB8yAC8yAAUAG6UWgCU2ZlaLAQSIHzICFAQcJA6euAAMsB8lCFhERDRcQlJmCl4yADaLhB+vPxCALpFuvpgyIqZOQWlWZn5ldW1YMvgFjn1jc3HYB18uYTEAPQPqAAWcA2krABiQW0A+gARSIAWQAkgA5ACCWlBkXBfy0kLaQXBWko92IJAoyAAzHiABz4gCcABpWMQQOwIJQAORfbDIAHiWigJrASQ0smYkjVWk8KxYP48N6kcQAdz+MGwHDMQk55OQdkczjclAAjFy1pqAMIAVQcqCCqD+kS+fxRPyCACFkcCUVoEUj7eiFWRKDj8QA2NUABgArJriEqnK53MgNaxFGTFMVKk9weJVrosOKIKRkHALGp9KQ01VJLVQBIoA0hldTnUGk0IC0VjcwHcFTCAOJBBx-AAKSOBLu53Ld4Z9PoA7PifYG+5SOLStMBBNBkB3dLR5X3MWJJLS4PRgFhgP4-rRJC4-mA59B0MvV2vkGLxOJKAAiHjMiBgF5CR8TqNKYoqbMaEgwQgAgbwGMYpjmJY2C4BixD6KBzhgKCAIeHQjBQCwyj5jUqznNWISIe0nRgN0oThFEsTxIkySjBMUwzDIczyIswFEas6zZHk+TbLs+wFqsCFgWAFb4ZAhHCfWjbcqgEJfLq-wOEEABqvY3gOOIAEwACyaZ644KtyQlIShlCeppmn4t+v5MMgBBAA)

A different issue with your solution, to me, is also that something like this would compile without issue even though it doesn't follow the spell type at all, thus allowing any arbitrary additional values added into spells
```typescript
export const TIGER_PALM = spell({
    id: 100780,
    name: 'Tiger Palm',
    icon: 'ability_monk_tigerpalm',
    woo: "something",
});
``` 
Maybe I'm missing something, but I don't see how the `__tag` field would in your example push anyone to use the spell() functionality?

**Comment by sMteX** [comment]
> Maybe I'm missing something, but I don't see how the __tag field would in your example push anyone to use the spell() functionality?

That's what I thought too, maybe it's because it forbids people using literals without the `__tag` field (e.g. `const foo = (spell: Spell) => {...}`, you can't use just a literal `{ id: 125 }` as `Spell`).

**Comment by Pewtro** [comment]
Sure something like 
```typescript
const MY_SPELL = {
    id: 123,
};
```
wouldn't be allowed into a 
```typescript 
const someFn = (spell: Spell) => {
    console.log(spell);
}
```

but you could do
```typescript 
const MY_SPELL_CAST = {
    id: 123,
} as Spell;
```
and it would pass without issues. There's ofc no way around preventing someone from typecasting, but is this added functionality worth all the additional types/functions surrounding it?

**Comment by emallson** [comment]
Yea the `tag` was just to introduce friction around YOLOing spells in w/o using our blessed spell constructor. We could ditch it to simplify types for sure.

I personally prefer the `export const` approach to spells to the `createSpellList({ object })` approach but tbh that is just preference, there isn't a strong technical reason to pick one over the other IMO. I think it is easier to have autocompletion / auto-import "just work" if they're standalone constants but we've successfully worked out typing these objects in a way that allows autocomplete to work so I don't think that will really be a problem.

Worth noting that we could define `createSpellList` as:

```ts
const createSpellList = (object) => Object.entries(object)
  .reduce((result, [key, value]) => { 
      result[key] = spell(value); 
      return result; 
    }), 
    {});
```

and could likewise define `spell` as:

```ts
const spell = (value) => createSpellList({ value }).value;
```

so they're fairly interchangeable on a technical level.

**Comment by Pewtro** [comment]
in the `export const` approach do you expect all consts to be collected into a singular object elsewhere, or how is it planned to allow someone to easily access multiple at once?

I haven't had an instance of autocompletion/autoimport not work with the `createXList` approach yet on the DF branch despite trying to break it

**Comment by emallson** [comment]
> in the export const approach do you expect all consts to be collected into a singular object elsewhere, or how is it planned to allow someone to easily access multiple at once?

you can `import * as spells ...` or `import { KEG_SMASH} from ...`, whatever makes sense for what you're doing. A lot of modules only need a couple and could do individual imports. But again: I think this is just a preference thing. No strong reason to prefer it over what you've got.

> I haven't had an instance of autocompletion/autoimport not work with the createXList approach yet on the DF branch despite trying to break it

i'm actually a little surprised that the autocomplete works for that type after all the shenanigans with the `SPELLS` stuff, but I guess `indexById` was the main thing breaking `SPELLS`, not the regular indexed object type. (I obvs haven't played much with the DF stuff yet.)

**Comment by sMteX** [comment]
I mean, the problem with autocompletion with current `SPELLS` is mostly in the sheer size. If the amount of keys is reduced (which would be in any case where using class/spec spells only), I'm sure the performance issue would be gone and it's down to mostly code style. I think I'm in favor of providing both options:
```ts
// .../monk/spells.ts
export const KEG_SMASH = ...

export const ROLL = ...

export default {
  KEG_SMASH,
  ROLL,
  // ...
};
```

That allows you to import individual spells if you only need a few, or the entire spell collection (which is comparatively tiny to what we have now, so it should be still fine to index). However you wish to define the spells is relatively free.

I think we can all agree that using individual/smaller subset of spells is the way to go, I'm more worried about the few places in core modules, where they still have a solid reason to work with spell references only by `id`.

**Comment by Pewtro** [comment]
> you can `import * as spells ...` or `import { KEG_SMASH} from ...`, whatever makes sense for what you're doing. A lot of modules only need a couple and could do individual imports. But again: I think this is just a preference thing. No strong reason to prefer it over what you've got.

Yeah this is actually how importing all talents (if you for whatever reason wanted that) is at the moment on my PR, while still allowing you to only access the subset (class right now) by a default. 
```typescript 
import * as ALL_TALENTS from 'common/TALENTS'; //all talents
import talents from 'common/TALENTS/warrior'; //all warrior talents 
import {default as TALENTS_WARRIOR} from 'common/TALENTS/warrior'; //all warrior talents renamed 
```

I do still think the non-const option is ad infinitum boilerplatey though. 

> i'm actually a little surprised that the autocomplete works for that type after all the shenanigans with the `SPELLS` stuff, but I guess `indexById` was the main thing breaking `SPELLS`, not the regular indexed object type. (I obvs haven't played much with the DF stuff yet.)

Yeah autocompletion seems to have been caused by indexById and non-typed in general when I did talents

**Comment by emallson** [comment]
Yea, actually `export default <object>` should already let you import individual fields shouldn't it. Ezpz we're all on the same page then, we just take the work that putput already did on the DF branch and run with it.

**Comment by sMteX** [comment]
Cool, I'd like to turn attention to the core modules once more - things like `SpellResourceCost`, `SpellUsable`, `StatTracker` etc. etc. 

If we ditch indexing by spellId (which I think we still should to reduce the bloat), we need to figure out some performant way to load spell data by ID. I was thinking of using `useSWR()` with a fetcher that could dynamically import files until it finds a match (the hook should be cacheable by default) but I'm sure y'all would have a better idea 😄

**Comment by MartijnHols** [comment]
Using export const has the added benefit that unused spells get tree shaken as well as can be highlighted by tooling. In addition you can place spells anywhere, e.g. if you make a racial module you can colocate the spell with the module. It gives a lot more freedom, and isn't really more to type when you can CMD+D to duplicate a line.

**Comment by emallson** [comment]
> If we ditch indexing by spellId (which I think we still should to reduce the bloat), we need to figure out some performant way to load spell data by ID. I was thinking of using useSWR() with a fetcher that could dynamically import files until it finds a match (the hook should be cacheable by default) but I'm sure y'all would have a better idea smile

Thinking about this in the context of our discord discussion today: we can keep the ability to index by id, but without merging those ids into the main object(s). If we actually need the ability to index by id, that is. I haven't done a pass on what the use case for that is right now, but it sounds like @sMteX may know.

**Comment by ToppleTheNun** [comment]
> If we actually need the ability to index by id, that is. I haven't done a pass on what the use case for that is right now, but it sounds like @sMteX may know.

A lot of the current cases are when there's iteration through a list of possible casts and trying to get the display value.

## Examples

### Mage

For instance:
```tsx
// src/analysis/retail/mage/frost/modules/talents/LonelyWinter.tsx

  statistic() {
    let totalDamage = 0;
    const tooltip = Object.keys(this.bonusDamage).map((spellId) => {
      const spellBonus = this.bonusDamage[Number(spellId)];
      totalDamage += spellBonus;
      return (
        <li key={spellId}>
          Bonus <strong>{SPELLS[Number(spellId)].name}</strong> damage: {formatNumber(spellBonus)}
        </li>
      );
    });
    
    return (
      <Statistic
        position={STATISTIC_ORDER.CORE(90)}
        size="flexible"
        tooltip={
          <>
            When analyzing this talent, take into account any DPS you lost by not having a Water
            Elemental.
            <ul>{tooltip}</ul>
            Total damage increase: {formatNumber(totalDamage)}
          </>
        }
      >
        <BoringSpellValueText spellId={SPELLS.LONELY_WINTER_TALENT.id}>
          {this.owner.formatItemDamageDone(totalDamage)}
        </BoringSpellValueText>
      </Statistic>
    );
  }
```

The spells that can be in `Object.keys(this.bonusDamage)` are already listed further up in the same file:
```tsx
const BUFFED_SPELLS = [SPELLS.FROSTBOLT_DAMAGE, SPELLS.ICE_LANCE_DAMAGE, SPELLS.FLURRY_DAMAGE];
```

This means we can change the tooltip declaration to the below, rendering the `indexById` not necessary for this type of usage:
```
    const totalDamage = Object.keys(this.bonusDamage).reduce(
      (acc, spellId) => acc + this.bonusDamage[Number(spellId)],
      0,
    );
    const tooltip = BUFFED_SPELLS.map((spell) => (
      <li key={spell.id}>
        Bonus <strong>{spell.name}</strong> damage: {formatNumber(this.bonusDamage[spell.id])}
      </li>
    ));
```

### Shaman

Similarly, another example from the ele shaman section:
```tsx
// src/analysis/retail/shaman/elemental/modules/talents/PrimalFireElemental.tsx

const damagingCasts = [
  SPELLS.FIRE_ELEMENTAL_METEOR,
  SPELLS.FIRE_ELEMENTAL_IMMOLATE,
  SPELLS.FIRE_ELEMENTAL_FIRE_BLAST,
];

// ...

  get unusedSpells() {
    return Object.keys(this.usedCasts).filter((spellId) => !this.usedCasts[Number(spellId)]);
  }

// ...

    const unusedSpellsString = this.unusedSpells
      .map((spellId) => SPELLS[Number(spellId)].name)
      .join(', ');
```

In this case, all we have access to is the stringified spell ID. If we do a bit of tweaking, we can achieve a similar state as the mage tooltip change:
```tsx
const damagingCasts = [
  SPELLS.FIRE_ELEMENTAL_METEOR,
  SPELLS.FIRE_ELEMENTAL_IMMOLATE,
  SPELLS.FIRE_ELEMENTAL_FIRE_BLAST,
];

// ...

  get unusedSpells() {
    return damagingCasts.filter(ability => !this.usedCasts[ability.id]);
  }

// ...

    const unusedSpellsString = this.unusedSpells
      .map((spell) => spell.name)
      .join(', ');
```

**Comment by ToppleTheNun** [comment]
> If we actually need the ability to index by id, that is.

Another use case is in `useSpellInfo`, which is used by all `SpellLink` components:
```
  useEffect(() => {
    if (data) {
      SPELLS[spellId] = data;
    }
  }, [data, spellId]);
```

This one's fairly trivial and we could probably just get rid of it once we're rid of the other uses of `SPELLS`.

**Comment by sMteX** [comment]
Yeah, most of the use cases in class analyzers are for arrays of spells. That could be refactored to be a `Spell[]` and while iterating you know you can access `MY_SPELLS[spell.id].name` for example. However, there are bunch of core modules that still use indexing by ID and that might be more problematic to refactor.

**Comment by emallson** [comment]
There is a new typescript feature that is basically exactly what we need for the existing mega objects, without all the complex typings: [the `satisfies` operator](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9-beta/#the-satisfies-operator). This is a part of the TypeScript beta, but should be available in a production release soon:tm:. We can ditch our complex types/type assertion functions at that time and switch to using `satisfies` for existing options.

**Comment by ToppleTheNun** [comment]
I think we can call this done?

**Comment by emallson** [comment]
Yup, I think so
