### ISSUE TITLE
Update Specializations Page

### ISSUE THREAD

**Issue by emallson** [WoWAnalyzer/WoWAnalyzer#5091]
Currently, the [specs](https://dragonflight.wowanalyzer.com/specs) page has a jumble of all specs. This would benefit greatly from better organization.

- [x] Divide into two sections: Classic & Retail
- [x] Organize Retail specs into rows
- [ ] Move unsupported *classes* to the bottom of the list. (Unsupported specs of a supported class should stay in their row)

**Comment by emallson** [comment]
Will need another pass once the rest of the druid specs are supported.

Also want to do a pass once we handle #5090 / #5093.

**Comment by ToppleTheNun** [comment]
Are we good to close this?
