### ISSUE TITLE
Fire Mage

### ISSUE THREAD

**Issue by fyruna** [WoWAnalyzer/WoWAnalyzer#519]
This is for discussion regarding the Fire Mage Spec/Modules.

_Disclaimer: I have been playing Fire throughout most of Nighthold and Tomb of Sargeras, but one of my guildies on Draenor (EU) has stuck with Fire every since vanilla and is my usual source for theories and knowledge. Also the game doesn't want me to have the Sun King bracers._

**Comment by fyruna** [comment]
Suggestions for statistics:
* Add statistic for wasted casts when hot streak was up (cast anything but Pyro) and list which casts / how many
* Add statistic for overwritten Hot Streak procs (these two could be combined)
* Uptime on Pyretic Incantation
* Combustion reduction via Kindling

Suggestions for items:
* Contained Infernal Core (Meteor after 30 stacks)
* Koralon's Burning Touch ( Increases Scorch's damage by 350% against targets below 30% health.)
* Marquee Bindings of the Sun King (Grants a 15% chance to empower   Pyroblast after consuming  Hot Streak. The next non-instant  Pyroblast will deal 300% more damage.)

**Comment by Pewtro** [comment]
Made this milestone to replace: https://github.com/WoWAnalyzer/WoWAnalyzer/milestone/18

**Comment by Sharrq** [comment]
This can be closed
