### ISSUE TITLE
Holy Paladin: Wasted Judgment of Light stacks statistic

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#52]
I think `Wasted Judgment of Light statistic` would be interesting to see, especially to compare the "cast on CD and forget" and "cast only when debuff dropped" approaches; now that there's no cooldown on the JoL healing the wasted JoL should be low enough for tracking it to be negligible.

Would be great if anyone contributes this ;)

**Comment by torothin** [comment]
By wasted do you mean that judgement of light is not present often enough indicating potential healing lost?  Or, do you mean wasted by overriding stacks by casting judgement while judgement of light is still >0 stacks?

**Comment by MartijnHols** [comment]
Ah this was closed by #3416

**Comment by MartijnHols** [comment]
It shows the amount of stacks not consumed to heal players. The cast efficiency is handled separately by looking at the cast interval.
