### ISSUE TITLE
Add Estel, Dejahna's Inspiration (Priest)

### ISSUE THREAD

**Issue by Pastaaa** [WoWAnalyzer/WoWAnalyzer#533]
Estel (http://www.wowhead.com/item=132861/estel-dejahnas-inspiration) give a haste buff for using plea, depending on how many targets have atonement. 

The average haste buff of this would be nice to know.

**Comment by awlego** [comment]
I implemented this feature. There is an open PR for it now.

**Comment by Pastaaa** [comment]
Thank you =)   
Legy is implemented, so should be closed.
