### ISSUE TITLE
Rework frontpage

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#535]
Frontpage is a mess and can use another rework. I think the features panel can be dropped by now, and the changelog might be done differently. Also header obviously needs to be changed.

Ohh and while at it the background has gotten dull. Maybe just redo the entire layout.

**Comment by fyruna** [comment]
I'll gladly help out with this!

**Comment by MartijnHols** [comment]
I added a panel for the Discord bot:

![image](https://user-images.githubusercontent.com/4565223/31853461-e777d1c4-b688-11e7-88a4-7327ce6e67b5.png)

(right side is a gif)

**Comment by MartijnHols** [comment]
I started work on this. I'll try to post progress when it's good enough for feedback. Here's the first thing:

![image](https://user-images.githubusercontent.com/4565223/33152048-e8ac875e-cfda-11e7-9da9-f1c3f36f2889.png)

**Comment by MartijnHols** [comment]
The below version is probably not going to receive many major changes anymore:
![image](https://user-images.githubusercontent.com/4565223/33186561-a9d4b820-d08a-11e7-8218-b9add92c6c77.png)

**Comment by MartijnHols** [comment]
Added an icon to the header, changed contributor names to an orangy yellow so it doesn't get confusing with other things using the legendary color and can be used in more places in the analyzer, added a GitHub link directly to a spec's source.

![image](https://user-images.githubusercontent.com/4565223/33224978-e11f6de4-d16f-11e7-9dd1-7be4182ad79a.png)

Moved changelog undearneath the spec listing:

![image](https://user-images.githubusercontent.com/4565223/33224991-0cfe0efc-d170-11e7-921c-3d3a08bb942a.png)

**Comment by MartijnHols** [comment]
Redid the header and the default background is no longer an image since it looked weird being cut off in combination with the full detail header;

![image](https://user-images.githubusercontent.com/4565223/33235317-2f9e29bc-d236-11e7-903f-ce2d5f0633f1.png)

**Comment by kfinch** [comment]
Looks pretty rad, keep up the good work. I've got no complaints (and I usually have complaints about everything)

**Comment by MartijnHols** [comment]
Full version so far
![image](https://user-images.githubusercontent.com/4565223/33239262-631edae4-d29e-11e7-8edc-8fdfbef2cf23.png)
