### ISSUE TITLE
[Brewmaster Monk] Suggests Rushing Jade Wind even if the character does not have that talent.

### ISSUE THREAD

**Issue by SanaraLethon** [WoWAnalyzer/WoWAnalyzer#537]
- Firefox, Chrome
 - Brewmaster Monk
 - https://wowanalyzer.com/report/yWXTCt1G2zvVLNaq/15-Normal+Maiden+of+Vigilance+-+Kill+(4:56)/Sanara
 - What's your Discord nickname? N/A
 - Do not suggest RJW if it is not talented.

**Comment by sMteX** [comment]
Fixed with #563 .
