### ISSUE TITLE
Distance moved leadboard

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#542]
let's make a distance moved leaderboard because it's useless but fun!
the more I talk about it the more I want to do it
Seemingly the biggest challenge would be server side computing it, but I figured we could just let users submit their scores and if they're ever faked we'd just remove and ban them. Would be much simpler. Then we need a database table, np, and a new interface
could use some obfuscation and generate a random verification token to make faking it too hard for 99% of the users

**Comment by janvavra** [comment]
Something like that should be done for feedback reasons. Knowing the distribution of moved distance for you spec can tell you if you moved too much in a fight. But maybe you dont want to store a lot of info server-side in this project.

**Comment by MartijnHols** [comment]
Closing this since it falls outside the scope of the project and needn't be tracked
