### ISSUE TITLE
Fix the DistanceMoved statistic.

### ISSUE THREAD

**Issue by sMteX** [WoWAnalyzer/WoWAnalyzer#551]
While fundamentally correct, there seems to be a missing conversion factor of some sort. Don't know why we're dividing by 100 in calculating the distance but if it wasn't there the distance would be even larger. My only guess is that the `x` and `y` coordinates are not in yards but something else and we need to figure out the conversion ourselves. Highly unlikely to run 29k yards in Mythic Goroth fight when the straight line from Orgrimmar to Ramkahen, Uldum is about 11,8k yards. We've disabled the module temporarily till we figure out the problem.

**Comment by sMteX** [comment]
Thought occured - maybe it was mixing the distances from other players too (the x and y wasn't always the player's but from others) so I tried adding `_byPlayer_` filter to the events. Dropped by a factor of 7 - 8 to more reasonable numbers but I still think 11k yards during Goroth M are too much for a Demo Warlock (that pretty much loves standing still).

**Comment by MartijnHols** [comment]
Aha it's missing the byPlayer/toPlayer checks. That's specific per event as some events have the coordinates of the giver and others of the taker. https://github.com/WoWAnalyzer/WoWAnalyzer/blob/5821fed700e4a6098b82b3b681256e8923aa881a/src/Parser/Paladin/Holy/Modules/Features/MasteryEffectiveness.js#L37-L39

**Comment by anom0ly** [comment]
I saw this was reenabled and it looks as though the `byPlayer` and `toPlayer` checks have been added. Can we close this issue?

**Comment by sMteX** [comment]
Fixed with https://github.com/WoWAnalyzer/WoWAnalyzer/commit/f674f68a418d16dbc1612ada2ae43f1c22babae9 .
