### ISSUE TITLE
LegEnhancementChecker not accurate

### ISSUE THREAD

**Issue by JeaneC** [WoWAnalyzer/WoWAnalyzer#5543]
Looking at https://www.wowanalyzer.com/report/hqF831BjCvLKM4pX/4-Heroic+Terros+-+Kill+(5:27)/Vireve/standard/overview, it claims I'm missing a leg enhancement but I definitely have it.

New here, but looking from the code, I think we just need to change `item.temporaryEnchant` to `item.permanentEnchant` for `LegEnhancementChecker.tsx`. Tested that change locally and seemed to work, but unfamiliar of other changes that might cause. I'm guessing permanent enchant is your standard enchants and temporary refers to oils or weapon runes?

**Comment by emallson** [comment]
this probably got missed because SL armor kits were temporary but DF ones are permanent. the fix seems reasonable, but i can look later

**Comment by JeaneC** [comment]
Happy to take as a first commit! Seems straightforward to me

**Comment by emallson** [comment]
go for it 👍

**Comment by ToppleTheNun** [comment]
Yep, was just a misunderstanding on my part.
