### ISSUE TITLE
PotionChecker for PreparationSection has maxPotions used off

### ISSUE THREAD

**Issue by JeaneC** [WoWAnalyzer/WoWAnalyzer#5568]
If you go to a guide view with the Preparation Section (e.g https://www.wowanalyzer.com/report/zf9h3vJAFXY8w6tM/11-Heroic+Eranog+-+Kill+(3:49)/Jedith), then it has a combat potion section that is falsy
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/25225547/209481388-07f10f3f-ca10-4e1b-b868-9271c6c2eb30.png">

Is there a reason we have a listener for buff and cast? Buff seems more accurate and deleting cast seems to delete the double potions count
https://github.com/WoWAnalyzer/WoWAnalyzer/blob/dragonflight/src/parser/retail/modules/items/PotionChecker.tsx#L128

**Comment by ToppleTheNun** [comment]
The buff check is there for prepull potion support afaik

**Comment by JeaneC** [comment]
Oh wait I read the code again and realized its because we put healing potion in the STRONG_POTIONS list, lol.  I think we need to track combination potions for that card
