### ISSUE TITLE
Resto Shaman

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#56]
Use this issue to discuss features for this spec. Let us know when you're working on something, or plan to work on something.

**Comment by MartijnHols** [comment]
Currently being maintained by @Versaya

**Comment by MartijnHols** [comment]
Pacer - Today at 19:48
@Zerotorescue [Retired] you should add ancestral vigor to the analyzer
so you get a gold star when someone has the buff while being under 10% hp :))

**Comment by MartijnHols** [comment]
I'd like to suggest adding an overview for the value of traits on relics. This may become even more useful in 7.3 with the NLC where you need to pick *two* traits instead of just one; example from the Holy Paladin version I did:

![image](https://user-images.githubusercontent.com/4565223/29812069-c05da602-8ca5-11e7-8954-4a0bd429c27b.png)

**Comment by hartra344** [comment]
@MartijnHols can you reactivate issue this for me?

**Comment by MartijnHols** [comment]
It's preferred to make single issues to track everything and a milestone to track everything together.

**Comment by hartra344** [comment]
Ok so just make a new Resto Shaman issue for the milestone?
