### ISSUE TITLE
Holy Priest

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#57]
Use this issue to discuss features for this spec. Let us know when you're working on something, or plan to work on something.

**Comment by TomBeckett** [comment]
I'm happy to pick this up. @Kabalis on disc.

**Comment by MartijnHols** [comment]
I'd like to suggest adding an overview for the value of traits on relics. This may become even more useful in 7.3 with the NLC where you need to pick *two* traits instead of just one; example from the Holy Paladin version I did:

![image](https://user-images.githubusercontent.com/4565223/29812069-c05da602-8ca5-11e7-8954-4a0bd429c27b.png)
