### ISSUE TITLE
[Feral Druid] Update Logic to support valid usage of finishers at >= 4CP

### ISSUE THREAD

**Issue by ChrisKader** [WoWAnalyzer/WoWAnalyzer#5833]
After a bit of theory crafting and testing, the SimulationCraft Feral APL (Retail Dragonflight) was recently [updated](https://github.com/simulationcraft/simc/commit/2315ceeebc243fbce82d617dbabae5015cfe3cf1) to allow for the use of finishers, in certain situations, at >= 4 CP. This is a bit out of the norm as it's has been encouraged in the past to only cast finishers at maximum CP.

**Comment by kakxow** [comment]
This was implemented here #5903, issue can be closed I think

**Comment by emallson** [comment]
Looks like it, thanks for pointing it out
