### ISSUE TITLE
Add "Amazing! :+1:" indicators to statistics

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#588]
Positive feedback is much appreciated by users. Showing Amazing 👍  for special performances would be great.

**Comment by yajinni** [comment]
My personal idea to this would be a toggle, similar to the minor issues one, that displays a list of the suggestions you did pass. Currently we only see the ones we failed.

**Comment by Sharrq** [comment]
Or even just remove the minor issue toggle and show all suggestions by default ... maybe with a filter/toggle to only show issues.

**Comment by MartijnHols** [comment]
@yajinni the reason for your suggestion is pretty important for considering a solution, so I'll quote it:
![image](https://user-images.githubusercontent.com/4565223/33347320-bf9b2962-d492-11e7-97d6-bb4bc1fa7324.png)

Another complaint I personally have is that we have *a lot* of issues and it's hard to get a good overview.

I was thinking it might be worth considering making a checklist for playing well where we tick boxes players pass and cross the ones they mess up. This could also be used for giving the player a rating that they could work on improving. It would probably be hard to tune well though, since as it is tuning individual suggestions is already hard.

**Comment by Pewtro** [comment]
Closed as pr Checklist implementation?
