### ISSUE TITLE
Add Healing Efficiency per Mana spent

### ISSUE THREAD

**Issue by buimichael** [WoWAnalyzer/WoWAnalyzer#60]
Similar to what checkmywow.has.

The amount of healing you did with each ability (not including overhealing), weighed by total mana spent. 
A tab for this for all healers would be nice,
![image](https://i.gyazo.com/f0f02d5d263c57bc4a0c19e2baa846c2.png)

**Comment by MartijnHols** [comment]
What's the point of such a statistic versus just calculating the HPM based on the properties of each spell like I do in my spreadsheet?

![image](https://cloud.githubusercontent.com/assets/4565223/26690648/5fbd2ffc-46fa-11e7-8a29-3c970b203601.png)
https://docs.google.com/spreadsheets/d/1wWPNjJBduiM-BSFjgJKpfoNyK3ZVXo8Qd_YYiGTMwWw/edit#gid=58904384

**Comment by MartijnHols** [comment]
I added a `manaUsed` property to the ability tracker that should make it easy to do this.

Example:
```js
const rejuvenation = getAbility(SPELLS.REJUVENATION.id);
const rejuvenationHpm = (rejuvenation.healingEffective + rejuvenation.healingAbsorbed) / rejuvenation.manaUsed;
```

All that's left is adding a tab if you really want this.

**Comment by MartijnHols** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=45792107)](https://www.bountysource.com/issues/45792107-add-healing-efficiency-per-mana-spent
)

**Comment by MartijnHols** [comment]
@joshinat0r is working on a solution

**Comment by TJMoats** [comment]
@MartijnHols Are we good to close this issue?
