### ISSUE TITLE
WarCraft Logs Link deprecated

### ISSUE THREAD

**Issue by Pexem** [WoWAnalyzer/WoWAnalyzer#6333]
Currently, if you are on a char and click on the Button to get to the WarCraft Logs Page of said Character you will run into an error. This is because the link generated is as such:

https://www.warcraftlogs.com.warcraftlogs.com/character/[Region]/[Server]/[Character]

If one removes the warcraftlogs.com portion in the front the link works. I have also had issues of WoWAnalyzer not finding Warcraftlogs for my Character with the WoWAnalyzer search. Maybe this has something to do with it aswell?

**Comment by Pewtro** [comment]
This should have been fixed in #6335
