### ISSUE TITLE
[Marksmanship] Medallion module sometimes shows more casts than possible

### ISSUE THREAD

**Issue by sMteX** [WoWAnalyzer/WoWAnalyzer#640]
Tarnished Sentinel Medallion sometimes shows "You cast X out of Y Medallion casts with trueshot." where X > Y (math degeneration, sorry 😄 ).

Example log: https://wowanalyzer.com/report/19hnvz3rNx46CHDP/20-Heroic+Maiden+of+Vigilance+-+Kill+(5:27)/Blazjoggs

**Comment by Pewtro** [comment]
I'm not seeing that? I see 2/3 on that log

**Comment by sMteX** [comment]
In Cast Efficiency it's correct, the item however:
![image](https://user-images.githubusercontent.com/5068584/32080275-14ebec56-baaf-11e7-96dd-7fdc79bc41a3.png)

**Comment by Pewtro** [comment]
I noticed afterwards 😅 Not sure why this is happening 

@leapis will probably know why

**Comment by leapis** [comment]
Thanks for finding this! Seems to be counting a Trueshot twice, not 100% sure why, but I'll push a fix for this ASAP

**Comment by leapis** [comment]
Okay, found the problem, had to do with some of the data being undefined since the parser hadn't gotten there yet. Sending a PR for the fix now
