### ISSUE TITLE
Refactoring of Code Smells.

### ISSUE THREAD

**Issue by LucasLevyOB** [WoWAnalyzer/WoWAnalyzer#6453]
Hello, WowAnalyzer team!

I am participating in a college project focused on contributing to Open Source projects. My partner, [GabrielFerreira7446](https://github.com/GabrielFerreira7446), and I find this project to be very interesting and would like to make a contribution. Our focus would be on addressing identified Code Smells in the codebase, which will assist in improving code quality, reducing technical debt, and facilitating future features and fixes. Since this would be our first contribution to the project, we are excited to collaborate and learn from your team.

After reviewing the code using the [React Sniffer](https://github.com/fabiosferreira/reactsniffer) tool, we have identified some areas where code quality can be enhanced to make it more efficient, readable, and maintainable. The types and quantities of Code Smells are listed in the table below.

| Code Smell | Quantity |
|--------|--------|
| Large Component | 5 |
| Too many props | 3 |
| Missing Union Type | 9 |
| Inheritance instead of composition | 1 |
| JSX outside the render method | 12 | 
| Any Type | 3 |

Follow the links to the detailed reports:

- [Files Smells](https://docs.google.com/spreadsheets/d/1NLi2BmoIZXvmzcyQPZDczJutRyr-ljgRmQNApi4-20M/edit?usp=sharing)
- [Components Smells](https://docs.google.com/spreadsheets/d/1KyYT9d0QHAk1ZRJvZSD1LjBpEO_VLgBh6MPH1pLk_J0/edit?usp=sharing)

We are open to any suggestions and guidance from the team.

Thank you!

**Comment by emallson** [comment]
Hello,

You are of course welcome to contribute to WoWA's development. However, I don't think that the issues identified by your tool would be of much value to work on (not counting the issues that it has found which are incorrect, such as the "large number of props" for `BreathOfEonsHelper` which lists a huge number of variables that are not props).

But regardless, if you would like to contribute to WoWA development feel free to put in some work and submit a PR and we'll take a look!

**Comment by LucasLevyOB** [comment]
Code Smell missing union type refactoring - [#6497](https://github.com/WoWAnalyzer/WoWAnalyzer/pull/6497)

**Comment by LucasLevyOB** [comment]
Any Type code smell refactoring - [#6498](https://github.com/WoWAnalyzer/WoWAnalyzer/pull/6498)

**Comment by LucasLevyOB** [comment]
refactor: refactoring large file and too many props smells [#6521](https://github.com/WoWAnalyzer/WoWAnalyzer/pull/6521)

**Comment by LucasLevyOB** [comment]
refactor: refactoring code smell large component [#6522](https://github.com/WoWAnalyzer/WoWAnalyzer/pull/6522)
