### ISSUE TITLE
Ray of Frost channeling time

### ISSUE THREAD

**Issue by earosselot** [WoWAnalyzer/WoWAnalyzer#6631]
Ray of Frost is not displaying the cast, or channeling, time on the timeline, although the channel was completed for all 5 ticks. I believe this issue is also affecting Active time calculation. Here, I am presenting a collage of the timelines, casts, and ticks for a log that highlights the problem.

![image](https://github.com/WoWAnalyzer/WoWAnalyzer/assets/32552126/cf0a379c-cc46-4c36-86c3-36a9d8151f05)

Report and WarcraftLogs:
https://wowanalyzer.com/report/7h3pnKw28dJBADQ4/5-Normal+Gnarlroot+-+Kill+(2:07)/Raistlinn/standard/overview
https://www.warcraftlogs.com/reports/7h3pnKw28dJBADQ4/#fight=5&type=damage-done

I have tried to find a solution to this problem, but I couldn't find where this is set. If anyone can tell me where to start looking, I could solve it.

Thanks!

**Comment by Sharrq** [comment]
I think you need to add Ray of frost to the channeling file

https://github.com/WoWAnalyzer/WoWAnalyzer/blob/dragonflight/src/parser/shared/normalizers/Channeling.ts

**Comment by earosselot** [comment]
that's what I was looking for, ty!
