### ISSUE TITLE
Add stats proc effects on HPS/DPS

### ISSUE THREAD

**Issue by riklaunim** [WoWAnalyzer/WoWAnalyzer#688]
Suramar armor 2-sets as well as some trinkets can proc giving extra stats. Would be handy if it was taken into account show it performance if possible (prediction for crit, while things like mastery, versatility or primary stat could be calculated accurately).

**Comment by MartijnHols** [comment]
A requirement for showing the HPS/DPS value of stats would be that a spec has stat weight calculation implemented. Currently only Resto Druid and Holy Paladin have this. This isn't an easy thing to implement, but without it we have no accurate way of knowing the value of stats and thus wouldn't be able to show any meaningful information for these procs.

**Comment by riklaunim** [comment]
MW mastery would be easiest as is a 1:1 extra healing. Versatility is a similar modifier. The system would have to know how abilities power is calculated. Like you have 100 versatility which increases your HPS by 5%. But when you get 500 versa from proc that's 30% in total (random numbers). Calculate what spells would do for 105%, subtract from 130% results and that's the effect caused by the stat proc. (not a stat value, just the effect).

Crit chance is a chance so it could be shown like - during periods without a proc you critted for 40% average, while during proc you critted for 45% on average. Haste is even more tricky.

**Comment by kfinch** [comment]
@riklaunim You should take a look at our recently added StatValue framework

**Comment by riklaunim** [comment]
checked the readme, will look at it more when I'll have some time.

**Comment by abelito75** [comment]
Is this still a valid issue? 
If it is we could do sloppy math were we just do stat value * uptime of stat = hp
There is an example of this being done in SecretInfusion.js

**Comment by MartijnHols** [comment]
This is indeed already possible by combining stat values with the average stat gain.
