### ISSUE TITLE
Holy Paladin: check if overhealing trivial content to avoid showing both cast more LoD and avoid LoD overhealing suggestions

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#690]

**Comment by abelito75** [comment]
Is this still a valid request? Not just due to glimmer but also the fact that using a log of underhealing on wowA is kind of pointless. Its like asking someone to review you doing lfr as a healer. Almost nothing is going to be valid since overhealing is crazy and healing just to heal is a waste

**Comment by MartijnHols** [comment]
Replaced with #3423
