### ISSUE TITLE
Tooltip in mana graph

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#7]
WCL shows a tooltip in the graph when hovering showing the mana level at that point and who died. Need to show something similar since users are used to having this information.

**Comment by milesoldenburg** [comment]
I looked into this a bit yesterday. As of the current version (`0.0.17`) of [chartist-plugin-tooltip](https://github.com/tmmdata/chartist-plugin-tooltip), the package only supports tooltips when hovering directly over data points on the graph. This makes it quite hard to even get one to show up. I think until that package is updated to select the closest x position of the cursor regardless of the y position like the WCL graph then it would not be very valuable.

**Comment by MartijnHols** [comment]
#327 should solve this
