### ISSUE TITLE
[Core] Show info box with stats

### ISSUE THREAD

**Issue by Pewtro** [WoWAnalyzer/WoWAnalyzer#708]
A nice little info-box with the stats the player had on this specific kill: 

Something like this: 
![image](https://user-images.githubusercontent.com/29204244/32253733-c17a2780-be9c-11e7-8625-970b9acfe8a5.png)

Maybe structured in this manner and placed under items/legendaries/tier boxes: 

Stat | Percentage | Rating | 
-----|-------------|---------
Mastery | X % | Y (number) | 
Crit | X % | Y (number) | 
Haste | X % | Y (number) | 
Verstatility | X % | Y (number) | 

Also acts as an alternative (in terms of this information possibly being more relevant to DPS) to the statweights developed for healers. 

A further development could be to include how much you **actually** critted during said encounter (maybe on mouseover tooltip or something of the like)

**Comment by MartijnHols** [comment]
Which stats would you like to see? Pull time stats? But they'd be wrong whenever someone had a buff active. Lowest stats? Highest stats? Average stats? Unbuffed stats? Unbuffed stats + flasks?

In any case I'd prefer the more visually pleasing approach from battle.net;

![image](https://user-images.githubusercontent.com/4565223/32290772-5bf634ea-bf3b-11e7-9e06-6adcc85aa635.png)

**Comment by Pewtro** [comment]
Stats on pull I reckon, which **should** not include hero etc. 

Should work well with the StatTracker if: https://github.com/WoWAnalyzer/WoWAnalyzer/issues/659 is finished

**Comment by MartijnHols** [comment]
So stats from gear + flask + food + vantus + augment rune?

Or better multiple possible views; stats from just gear, and gear + long duration buffs

**Comment by Sharrq** [comment]
I would imagine stats from gear would be more beneficial. But why not show both or some kind of total with a breakdown??

i.e. 30% Haste (28% from gear, 2% from other sources)
or to go in more detail (25% from gear, 2% from food, 3% from x buff)

But probably shouldnt include cooldowns like Lust and such. Raid Buffs, Food, Flask, Runes, etc are probably fine to include but seeing just the stats from gear is also important as well. So i think if you totaled them, thats fine, but you would need something to say x from gear and x from elsewhere. Best of both worlds?

**Comment by MartijnHols** [comment]
I think showing stats from just gear would be most consistent among pulls / bosses and reliable. We could add a toggle to show pull ratings with a disclaimer that it might be off, but then again we might also omit this as users can already go to WCL to see that.

This should be possible to do with enhancements to the StatTracker.
