### ISSUE TITLE
Character Logs - Something went wrong talking to the server

### ISSUE THREAD

**Issue by danny-janse** [WoWAnalyzer/WoWAnalyzer#7103]
As mentioned by [guru8526 over on discord](https://discord.com/channels/316864121536512000/360770373454659585/1290559310765621248). Their character logs cannot be fetched. 

Logs: https://www.warcraftlogs.com/character/EU/kazzak/Weekendgamer
Analyzer: https://wowanalyzer.com/character/EU/Kazzak/Weekendgamer/.

![image](https://github.com/user-attachments/assets/ccb1afee-de62-43d9-8c07-bd3f96a5773e)

This seems to be an issue bound to certain characters, since it does work for other charcters such as;
https://wowanalyzer.com/character/US/Tichondrius/Hawtzzw/

Possibly a WCL issue?

**Comment by danny-janse** [comment]
I've looked into this for a bit and it appears this is an error caused by the WCL code base when reaching out to the following url;

https://wowanalyzer.com/i/v1/parses/character/Weekendgamer/kazzak/EU?includeCombatantInfo=true&metric=dps&zone=38&timeframe=historical&partition=-1

> ERR_BAD_RESPONSE

> AxiosError: Request failed with status code 500
    at settle (/usr/src/app/node_modules/.pnpm/axios@1.6.0/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/.pnpm/axios@1.6.0/node_modules/axios/lib/adapters/http.js:585:11)
    at IncomingMessage.emit (node:events:531:35)
    at IncomingMessage.emit (node:domain:488:12)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)


However, checking for M+ logs seems towork just fine (zone = 39)
https://wowanalyzer.com/i/v1/parses/character/Weekendgamer/kazzak/EU?includeCombatantInfo=true&metric=dps&zone=39&timeframe=historical&partition=-1

Is this something you could look into, @emallson?

**Comment by emallson** [comment]
There is a fix under review for this on the WCL side

**Comment by danny-janse** [comment]
Parses now appear.
