### ISSUE TITLE
[Elemental Shaman] Update Maelstrom graph

### ISSUE THREAD

**Issue by fasib** [WoWAnalyzer/WoWAnalyzer#713]
- [ ] Use Chart.js
  - [ ] Calculate generated and wasted in own module (create basic resource module for all specs)
  - [ ] Remove extra WCL API call

**Comment by leapis** [comment]
since it's for a class that is attacking the boss often, it may be possible for you to remove both API calls (because you may be able to grab all the boss health data you need from damage events)

**Comment by fasib** [comment]
Thats the plan with resource module :)

**Comment by HawkCorrigan** [comment]
Also done with the resourcetracker
