### ISSUE TITLE
[Shadowpriest] Wrong / negative Downtime

### ISSUE THREAD

**Issue by Pastaaa** [WoWAnalyzer/WoWAnalyzer#734]
Atm shadowpriest are able to reach negative downtime thanks to lingering insanity [http://www.wowhead.com/spell=197937/lingering-insanity](url) (maybe something else?) is not tracked correctly which leads into false haste calculation. 

[https://wowanalyzer.com/report/jAaYdvz9pVNTBkr7/9-Heroic+Harjatan+-+Kill+(2:44)/Past%C3%A0/suggestions](url)

**Comment by MartijnHols** [comment]
This should have been fixed in https://github.com/WoWAnalyzer/WoWAnalyzer/pull/750

Thanks for your report!
