### ISSUE TITLE
[Retribution Paladin] Judgement timeline / Judgement tracker

### ISSUE THREAD

**Issue by Phwaah** [WoWAnalyzer/WoWAnalyzer#805]
Holy main just switched to ret for KJ. Zero would know me from bugging him about wowanal all the time on disco. Just wanted to suggest to have a Judgment buff applied window in the timelines tab. We currently have 'judgment on cd' but doesn't show the time when I spent HP without judge up or when the judge fell off. Would be handy to know. Thanks!

**Comment by Phwaah** [comment]
I believe I may have posted this in the wrong place 🤦‍♂️

**Comment by CollCrom** [comment]
@Phwaah There is an stat box for when you spend HP without judgment. I feel as though it would be unnecessary to also have it on the timeline as a graphic. I am open to a discussion about its merits however.

**Comment by MartijnHols** [comment]
Buff uptimes were implemented some time ago, I believe this solves your suggestions @Phwaah
