### ISSUE TITLE
[Shaman][Restoration] Cooldowns

### ISSUE THREAD

**Issue by Pramaxis** [WoWAnalyzer/WoWAnalyzer#819]
I would like to see [Astral Shift](http://www.wowhead.com/spell=108271), healing tide and other spells added to CONSTANTS as they do not feed into CBT, AG or Ascendance. Why do I want that? Because it does not feed into one of the spells and is currently shown as if. 

The next thing may be impossible or extremely limited by the design of the website but it would be a great improvement.  In the current situation we see one cooldown after another. The system fetches some spells and tracks following abilities on the timeline to line them up in separate time arrays. The problem is, that the rshaman has multiple (micro) cooldowns that can somewhat interact with each other. To get you a better picture at what I'm pointing my finger on lets look at some analyses. 

![badcooldownsrshaman](https://user-images.githubusercontent.com/20531906/32885780-d2b5280a-cabe-11e7-84d7-d3cee2dfaeda.png)

We have the first feeding string from 0:25 to 0:38 and a second one (from a legendary proc) from 0:28 to 0:43 followed by **three** other feedings from 0:28 to 0:38 (AG), 0:28 -> 0:38 (Velen's) and an innervate from 0:32 to 0:42. You know, from my perspective that is a problem. What is needed to get useful data from that tab? **Merge information**. I don't need every tiny thing so I may be able to see the value of each button I pushed separated from the next **if I pushed them together for a big firework**. 

To get you a picture of what I would like to see instead I made a schematic representation.
![bettercooldownsrshaman_schematic representation](https://user-images.githubusercontent.com/20531906/32885848-0fe1f99c-cabf-11e7-8636-2ad77af67c6e.png)

**Comment by poneria** [comment]
The newest timeline tab ([example log](https://wowanalyzer.com/report/KbQnkMHZmqWgtXwz/33-Heroic+Krosus+-+Kill+(2:55)/Doomshovel/timeline)) is already doing what you want graphically. Double check with your log it to see if it's got all the cooldowns you want displayed? 

It doesn't have the total throughput **stats** over the cooldown time, however; **the timeline tab is just a timeline**. If you want stats, an additional throughput spec module or tab would be useful. (Sorry, I'm a Warlock by main.)

**Comment by Pramaxis** [comment]
I'm sorry I can't open your link because of an "null reference" error for "Focuser of Jonat" in the log. Is someone working on the files?

I would like a list like the current cooldowns now but without the information overhead. Yes I can go and work that out on warcraftlogs but the reason I use wowanalyzer is because I'm too lazy to go and fetch stuff like these every log a new. Things like feeding and cd-overlapping is hard even if you know what you are searching for. The way it is now, it's useless to me.

**Comment by MartijnHols** [comment]
That should be fixed now.

**Comment by poneria** [comment]
The timeline tab looks like this. Admittedly, when looking at longer duration cooldowns, it's hard to use at anything less than 5x magnification. 
![screenshot_48](https://user-images.githubusercontent.com/18505808/32985111-19a852a0-cc81-11e7-826b-5d0cfc3beae3.jpg)

I was having trouble understanding what question you want answered by the tab.
* Are the cooldowns stacked together & over what time? --> the Timeline tab solves this
* Healing output & mana use stats during a period of specific cooldown(s) usage? --> more specifically Resto Shaman, but could also be solved generically, depending on the analysis

As a Warlock, I don't find the Cooldowns tab useful either, as it doesn't answer or analyze questions about proper cooldown usage. So I was interested to see if the analysis you wanted displayed was similar to what I want, or if this is a specific question that I was just misunderstanding as general. (:S sorry!)

**Comment by Pramaxis** [comment]
Yes you are misunderstanding what I want but that is because of my lack of knowledge of the English language. The information from the timeline tab is also available on warcraftlogs but I generally like the feature of wowanalyzer to show the output and the mana used for it in comparison. If I wanted to get this data from warcraftlogs I would have to run a lot of filters and calculate that myself. This is very exhausting. The value of this information lies in the combined strength of three single data strings, namely mana used, spell casts and output performed. The way it is now the cooldown tab is extremely redundant. It gives away great potential for the easy programming and only partial usability where it could be outstanding. 

What do I want from the cooldown tab?

- A skill lineup for the feeding of/into spells | Check
- An extended analyse of combined used micro cooldowns | feature to be
- Mana used for combined micro cooldowns | partial coverd
- Healing output for combined micro cooldowns | partial coverd
- Double dipping/interactions between micro cooldowns displayed (for example: AG & CBT) | feature to be

**Comment by Pramaxis** [comment]
As far as I'm aware of the beta It is not relevant anymore. Sadly it never got covered in legion in the first place (one of the reasons I stopped using this tool).

**Comment by abelito75** [comment]
Soooooooooo that means this issues can be closed now?
