### ISSUE TITLE
Fight selection redesign

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#827]
The fight selection as it is is a pretty minimal solution. I think it should be prettier.

- How about reversing the sort so latest (and thus most relevant) fight is on top?
- How about showing [pictures of the instances](https://render-eu.worldofwarcraft.com/zones/tomb-of-sargeras-small.jpg)?
- How about showing [boss images](https://render-us.worldofwarcraft.com/npcs/zoom/creature-display-74504.jpg) horizontally (grouped by instance) with underneath them all pulls with kills sorted on top?
- [Boss icons](https://www.wowhead.com/icons/name:achievement_boss_#170+1) may be useful

Users may be used to the list view as it is so it may be hard to get something that's prettier **and** works just as well.

**Comment by kyle-glick** [comment]
## Context:
If a raid group runs more than 1 raid in a single log, it would be helpful to be able to switch between raids within Fight Selection page.

## Suggestion:
Use nav-tabs to distinguish the raid(s) run during the log. Additionally, this would allow a background to be used for each raid to give the page some more color, like how the Player Selection page has backgrounds specific to the fight.

## Bad Example Screenshot
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/12898988/33531543-6d8fb6c4-d85c-11e7-99c5-fdfb443fda9e.png">

**Comment by MartijnHols** [comment]
I think adding tabs would make it harder and less straight forward to find a fight in the fight selection. Instead of showing everything in one list some things would be hidden behind tabs. A general rule of thumb is that tabs are poor interface design. Also breaks chronologic of the list. 

The fight background images might disappear or be replaced in the future. I started disliking it a bit.

**Comment by MartijnHols** [comment]
Each boss now has a "headshot" that might be usable for an interface rework;

https://github.com/WoWAnalyzer/WoWAnalyzer/tree/results-2.0/src/Raids/AntorusTheBurningThrone/Images/Headshots

**Comment by Sharrq** [comment]
It might also be cleaner and more compact (and thus solve the issue with it rolling off the edge of the screen), if this was laid out similar to WCL Where It lists the Boss Name, followed by all pulls associated with that boss, then the next boss, etc. ... but each fight has a smaller button to fit more on the screen?

Something like this bad paint drawing for example.
![image](https://user-images.githubusercontent.com/1304554/35875719-c663e0ac-0b35-11e8-86b6-4e9ea8f4e801.png)

**Comment by MartijnHols** [comment]
With the fight navigation bar coming this is too low prio to track. If someone feels like doing this because they think they have a grand idea rather than because of an issue they're more than welcome.
