### ISSUE TITLE
Timeline Tab cooldown bars aren't marked properly for spells with charges

### ISSUE THREAD

**Issue by kfinch** [WoWAnalyzer/WoWAnalyzer#837]
See Conflagrate, Dimensional Rift in http://wowanalyzer.com/report/WrqyP97mQDx4KGTd/12-Heroic+Mistress+Sassz'ine+-+Kill+(5:54)/Busk/timeline

I've noticed the issue in other timelines and other specs too, it doesn't appear to be a problem with spell definition. I've looked at the timeline code myself, but haven't yet found the issue.

**Comment by MartijnHols** [comment]
Duplicate of #793
