### ISSUE TITLE
Custom tab navigation issue

### ISSUE THREAD

**Issue by TsaboTavok** [WoWAnalyzer/WoWAnalyzer#845]
Hi, 

I  was adding a couple of tabs to Sub  Rogue, and I noticed there is some sort of issue in Results.js line 219 regarding custom tabs. Reproduced by going here https://wowanalyzer.com/report/Mf4kqRPKQjNwCpWy/5-Mythic+Sisters+of+the+Moon+-+Kill+(4:30)/%E6%9F%9A%E6%9C%A8%E8%90%8C/holy-power navigating away to another class and pressing back in your browser.

Seems like the `results.tabs` collection at this point does not contain the custom tab. It is easy to work around by just assigning any tab to be active, but I'm not familiar enough with web front end to actually fix this properly.

**Comment by Gebuz** [comment]
What exactly is/was this bug? Seems to work fine for me, I assume that means it's fixed but feel free to reopen if it is not.
