### ISSUE TITLE
Refactor buff stack handling to be more consistent and predictable

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#883]
Buff stack handling in the `Entities` class is pretty inconsistent; the `stacks` property of a buff is the last `stack` value of a `removebuffstack` event but I think that value might be the amount of stacks removed, not the actual amount of stacks remaining.

Should probably add a `maxStacks` prop for modules like Maraad's Dying Breath (which btw needs to be fixed if this is ever changed).

**Comment by MartijnHols** [comment]
I think refactoring the entire buff/debuff handling might be a good idea. Doing it via the Entities class is confusing and complicated.

**Comment by Gebuz** [comment]
When doing this it might also be a good idea to consider handling missing events (usually due to outranging or being in a different phase) similar to how warcraftlogs does it as discussed here: #969
