### ISSUE TITLE
Add a prop to modules allowing them to specify patch compatibility 

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#884]
Add a static prop to modules to allow them to specify patch compatibility. Nothing fancy, just date + message, if logs is before specified date the custom message shows that could specify what is wrong.

We considered giving modules versions but this got messy quick.

This prop could also be an object { date, warning, disabled } with disabled indicating if the module should be disabled if it's assumed to be incompatible.

**Comment by Sharrq** [comment]
would it make more sense or be cleaner to provide a "Spec updated for wow version x"

So for example, you could look at any Frost Mage analysis and maybe in the corner it said something like "This spec is updated for Patch 7.3.5" or "This spec is optimized for Patch 7.3.5" or some variation of that.

That way its a little easier to know which specs are inactive and/or for the player to know that the latest changes arent there.

You could go a step further and have some list of patch dates somewhere and if the log is before that date, display a warning saying something along the lines of "This fight was logged in a previous patch version, some statistics may not be accurate if blah blah blah spec was changed blah blah"

**Comment by MartijnHols** [comment]
We have a spec-wide version compatibility (like in-game addons), setting this per module probably doesn't have significant gains since we can't determine if a module becomes inaccurate in a certain patch
