### ISSUE TITLE
Show artifact relics equipped

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#954]

**Comment by Pewtro** [comment]
Do you have a battleplan how this would go about being added? I have some sparetime sunday to sink into something, this could be one of them

**Comment by MartijnHols** [comment]
Well still thinking about if we should do this at all. Artifact relics might be interesting because they reflect more than just stats, the only other things that do this are legendaries, trinkets and set bonuses. Still it seems weird to do this without simply showing the full gear set.

I was thinking it could go underneath the talentbox, but I realize in the results page redesign it wouldn't really fit. So a tab with the entire equipped gear visible would make more sense.
