### ISSUE TITLE
BUG - Efflorescence shows uptime even if efflorescence was never cast.

### ISSUE THREAD

**Issue by buimichael** [WoWAnalyzer/WoWAnalyzer#968]
https://www.warcraftlogs.com/reports/jQrF6DNxHwMRGnth#fight=25&type=healing&translate=true&source=25
https://wowanalyzer.com/report/jQrF6DNxHwMRGnth/25-Mythic+Felhounds+of+Sargeras+-+Kill+(4:59)/%E6%BD%AE%E7%BA%A2

According to the log this druid didn't cast Efflo a single time, yet it shows up as a 10% uptime with 0 healing done

**Comment by kfinch** [comment]
The reported uptime in seconds instead of percent is '30'.

```
on_finished() {
    // We need to take the last cast into consideration as well.
    const lastTick = this.owner.fight.end_time - this.lastCast;
    this.totalUptime += Math.min(lastTick, 30000);
    debug && console.log(`Last tick: ${lastTick}`);
    debug && console.log(`Total uptime: ${this.totalUptime}`);
  }
```

I WONDER WHY THAT IS
