### ISSUE TITLE
BUG - Lifebloom shows more than 100% uptime

### ISSUE THREAD

**Issue by buimichael** [WoWAnalyzer/WoWAnalyzer#969]
https://wowanalyzer.com/report/FWR71vhqDz4aAMP9/6-Mythic+Eonar+-+Kill+(8:40)/Blazyb

**Comment by kfinch** [comment]
Ok I looked at this one and it's actually some unexpected shit in the logs. At 41 seconds, a recently cast LB buff just fucking vanishes from its target without a removebuff or anything, and so this leaves us with an applybuff without a matching removebuff, which throws off the uptime calc.

I'm perplexed as to why the buff disappeared, the player doesn't seem to have died or anything. My best guess is that the scope of the Eonar fight is throwing off logging....

**Comment by kfinch** [comment]
Hmm tho, it looks correct on WCL.... I'll look closer.

**Comment by HawkCorrigan** [comment]
Does it look correct on WCL?
I see a few people at the entrance just vanishing at 41 seconds. If you take a look at the Blood DK for example, from 41-70 seconds he doesn't cast and doesn't take or deal any damage.
That includes the point where lifebloom should have dropped from him too, so ye i'd go with people outranging the logging.

**Comment by kfinch** [comment]
Ok in WCL the events are the same eg the double apply with no remove... But it's getting the correct uptime. Maybe WCL sees the range issue but doesn't report that as an event? I'll ask in WCL discord.

**Comment by kfinch** [comment]
Ok confirmed it's events not showing in WCL either, and WCL is also getting the calculation wrong. WCL's uptime is not as messed up because it's using the applybuffs and removebuffs differently to generate uptime.

We could harden our uptime calc algorithm to be less messed up when this happens, but otherwise there isn't much we can do. Could also add a disclaimer to Eonar logs..

**Comment by MartijnHols** [comment]
How does WCL work that makes it not run into this issue? Does it ignore 2 applybuffs on the same target or is it some other check?

**Comment by kfinch** [comment]
Basically the second apply is ignored. There's is still wrong, but not as wrong. Our uptime calc does some weird overlapping duration shit which is making the uptime silly.

**Comment by MartijnHols** [comment]
Why is it ignored? What requirements are there for it to be ignored? It doesn't just ignore every second application of a buff since that would make it severely broken everywhere.

**Comment by kfinch** [comment]
If there is an applybuff on a target that already has the buff, it's ignored. If the lifebloom applications had been on different targets I think both our way and their way would have been fucked.

**Comment by kfinch** [comment]
Here's a visual, look at the events and compare with graph: https://www.warcraftlogs.com/reports/FWR71vhqDz4aAMP9/#fight=6&type=auras&ability=33763&view=events

**Comment by MartijnHols** [comment]
Is it a rule in-game that a target can not have the same buff twice or did they just get lucky while hitting the jackpot?

**Comment by Gebuz** [comment]
see #883
