### ISSUE TITLE
[Core] BUG - HPS values in wowanalyzer isn't matching WCL

### ISSUE THREAD

**Issue by buimichael** [WoWAnalyzer/WoWAnalyzer#972]
www.warcraftlogs.com/reports/1xwLjBKTR8P9qhDp#fight=6&type=healing 

https://wowanalyzer.com/report/1xwLjBKTR8P9qhDp/6-Heroic+Varimathras+-+Kill+(4:23)/Icekoh

**Comment by MartijnHols** [comment]
We include absorbed healing (on purpose), they don't.

**Comment by kfinch** [comment]
@MartijnHols arguably this is slightly a bug, because Varimathras is one of the very few cases where absorbed healing is actually not effective healing. I guess there's nothing reasonable to do about it.

**Comment by MartijnHols** [comment]
We could exclude that.
