### ISSUE TITLE
[Vengeance] Soul Cleave recommendation

### ISSUE THREAD

**Issue by kaedys** [WoWAnalyzer/WoWAnalyzer#987]
The analyzer recommends using Soul Cleave more (as a Major issue, no less), even if the user has a Fracture + Soul Bomb build (the current dominant and recommended build).  In this build, Soul Cleave isn't used _at all_, because Fracture (and subsequent Soul Bombs) is a better use of Pain.

Another issue with this specific build is that it recommends using more Soul Fragments on Soul Barrier.  In the Soul Bomb build, Soul Fragments are better spent on Soul Bomb rather than the extra absorb from Soul Barrier.

**Comment by ronaldpereira** [comment]
@kaedys Thanks for your suggestion.

I've set a long time ago that Soul Cleave is only a tracker for it (how many times you used it in some fight). It didn't even have a recommended cast suggestion or even a 'should be improved' message in the source code.

I'm not seeing the suggestion to use Soul Fragments with Soul Barrier too. I think that is the 'This usage can be improved with Soul Carver for maximum efficiency' phrase that is close to that. But this was a recommendation I've found long ago in Icy Veins guide and confirmed it later with some people in Demon Hunter Discord channel.

Anyway, can you pass me the link of the report you are having this issue, so I can see it and correct it, please?

**Comment by kaedys** [comment]
https://www.warcraftlogs.com/reports/T1yKj6WCDRBh2Hrk

And this was the alert in question.  It's explicitly recommending (as a Major issue) casting Soul Cleave more often.  Granted, it's based on the T20 bonus, but even back during Tomb, the Fracture/Bomb build was dominant, and Soul Cleave still was not used, despite the Vers buff it granted.

http://puu.sh/yLQ7V/1b42f65e7a.png

This is another one that's questionable:

http://puu.sh/yLQd3/2bfc6c8be3.png

The Tormented buff has individual durations.  If you consume 4 fragments, you get 4 stacks of the buff.  If you consume another fragment 3 seconds later, it refreshes to full duration with 5 stacks, but 4 of those stacks still vanish 4 seconds after the *original* application.  Each stack of the buff only lasts 4 seconds, regardless of whether it was refreshed during that duration.  So "refreshing" the buff isn't really useful.  Beyond that, in a Bomb build, you typically want to build up to 5 and then consume, so uptime on Painbringer is naturally low.

My concern is that WoWAnalyzer is meant to help make players better.  It should _not_ be making suggestions that are contrary to prevailing wisdom on how to properly play the spec with their given talent choices.  The Soul Cleave suggestion is particularly egregious, since it literally shouldn't be cast in a Fracture/Bomb build (unless you have the pain and would otherwise die in the next global), even with the T20 set bonus, but the Fragment/Tormented suggestion could also lead a player to an improper usage of their Fragments for the Bomb build.

**Comment by ronaldpereira** [comment]
About the Soul Cleave:

![image](https://user-images.githubusercontent.com/12674637/34304647-c63909aa-e721-11e7-85fd-2d863d5ae5b5.png)

This only pops when you have the 4 piece tier 20 bonus. The effect of it just pops if Soul Cleave is used. Can't take it from anywhere else.
So, If you invested on having this bonus, you should be using it by casting Soul Cleave. If not, it's pointless to use it.

Now about the tormented tracker:

![image](https://user-images.githubusercontent.com/12674637/34304782-4bb4242a-e722-11e7-8876-b58da30dcc17.png)

This debuff works by flat damage reduction and it's not dependent on how many Soul Fragments you consume. The damage reduction is 5% for 6 seconds. So, if you want to maximize it's effect, you should consume the Soul Fragment even if just one is available (as it gets the same debuff amount of 2+ consumes).

At last, I built this analyzer to be a start for player that want to get some more performance from his Vengeance spec. If that player hits an cutting edge performance, he'll start to play it's own way and build his own style. The main goal of my analyzer is to get the player from nowhere and put him in the path to be better at it, then he'll be able to make his own path.

**Comment by kaedys** [comment]
> So, If you invested on having this bonus, you should be using it by casting Soul Cleave. If not, it's pointless to use it.

Unless you're only using it because that happens to be your best gear for all 4 slots (which is the case with me on that alt).  It's still never worth using in a Fracture build, regardless of whether you have the buff or not.

> This debuff works by flat damage reduction and it's not dependent on how many Soul Fragments you consume. The damage reduction is 5% for 6 seconds. So, if you want to maximize it's effect, you should consume the Soul Fragment even if just one is available (as it gets the same debuff amount of 2+ consumes).

You're right, I was thinking Painbringer, not Tormented.  However, in a Bomb build, it's still not worth using sub-optimal bombs, and _definitely_ not worth burning the Pain on Soul Cleave, just to maintain a bit higher uptime on a 5% DR.  However, the uptime on that is part of why the sit-at-5-fragements-and-passively-consume style is considered the "survivability" version of the Bomb rotation.

> The main goal of my analyzer is to get the player from nowhere and put him in the path to be better at it, then he'll be able to make his own path.

That's exactly why I'm objecting to these "optimizations" which aren't actually optimizations, especially since many of them are being justified with what frankly qualifies as cutting-edge style thinking.  Like "if you invest in this set bonus, you should use it" (even though you shouldn't do either), the a "nowhere" player is going to equip and use tier without question simply on the assumption that the bonuses are worth using (which they should be).  This analyzer should be making good suggestions for that player's build, especially if it's starting from the assumption that the player won't know any better either way.  If it's suggesting changes and ability usages that are actively _harmful_ to the player, it's worse than ineffective.

**Comment by ronaldpereira** [comment]
I think you're confusing an analyzer with a guide. Our job at the analyzer is to get a performance and tell where to improve.

The goal of a guide is to advise you of which gear is better, which rotation/talents is better at the moment, etc.

I totally can understand why you're having this confusion (I had that too when I began to develop it too), but our job here is different than guides.

**Comment by kaedys** [comment]
>  tell where to improve.

That's my point.  If the suggestions are not actually _improvements_, then the analyzer is not doing what it advertises, no?

**Comment by kaedys** [comment]
Let me put it this way, is a tool that is marketed as being there to find area a player can improve is suggesting that <something the player is doing right> is an area of improvement, and that they should do <something that the player should not be doing>, then the tool is being actively _harmful_, not helpful.

**Comment by ronaldpereira** [comment]
> That's my point. If the suggestions are not actually improvements, then the analyzer is not doing what it advertises, no?

That's exactly what the analyzer is doing. Suggestions to improve all styles of play. If we exclude the other ones (like people who actually likes to use Soul Cleave by some reason), then it would do more harm than benefit.

**Comment by kaedys** [comment]
> That's exactly what the analyzer is doing. Suggestions to improve all styles of play. If we exclude the other ones (like people who actually likes to use Soul Cleave by some reason), then it would do more harm than benefit.

You literally just pointed out in the other thread that you have to pick *some* playstyle to base it off of.  If you're willing to select the "aggressive" Bomb-at-5 style there and not willing to support the sit-at-5-for-more-survivability style because it's less common (which is perfectly reasonable), even though that's a perfectly legitimate and effective playstyle in certain situations, then why are you willing to entertain a playstyle that uses Soul Cleave in a Fracture/Bomb build, _even though that's specifically the definition of doing it wrong?!_  I mean, if they don't take Fracture/Bomb, sure.  But that's why my suggestion was specifically couched in the terms of the Fracture/Bomb playstyle, and the analyzer certainly has access to talent information when making these analyses.

**Comment by ronaldpereira** [comment]
I got your point. I'll do a hotfix in a near future by making some of these changes you mentioned above. Again, thanks for your suggestion. If you ever have something else, please, let me know.

**Comment by kaedys** [comment]
I appreciate you engaging on this one.  Thanks for considering everything, and thanks for all the hard work =)

**Comment by Gebuz** [comment]
Soul Cleave no longer has a suggestion.
